### PR TITLE
Complete the threading fix

### PR DESCRIPTION
**Pull request by friedmud**
Complete the threading fix started in #839 caused by #838

### CODE REVIEW

**Comment by dschwen** [comment]
This looks weird. Why would you not ifdef a pthreads function with a pthreads ifdef? Just curious.

**Comment by friedmud** [comment]
Look further up, it's already in and ifdef pthreads block.  Note: this is actually just reverting to what was there before @permcody fixed something else and decided to change these at the same time (most likely because it didn't "look right" to him either :-), which broke this.

**Comment by friedmud** [comment]
@dschwen a little more: OpenMP and Pthreads are comingled.  The current implementation actually has the OpenMP capability depending on PThreads for some things.  Because of this, they are wound together in the code inside `ifdef pthread` blocks... with the pthread bits separated off by `if !openmp`

**Comment by dschwen** [comment]
Ok, this probably has to do with the precedence "logic" :-)

**Pull request merged**
