### PR TITLE
Improve BoundingBox initialization

### PR DESCRIPTION
**Pull request by andrsd**
BoundingBox class assumes that x-, y- and z- coordinates are monotonically
increasing. "Sort" the coordinates before constructing the bounding, so
that users do not have to think about this.

### CODE REVIEW

**Comment by andrsd** [comment]
This is just a suggestion. If you hate it, we can deal with this on MOOSE level 😃

**Comment by jwpeterson** [comment]
Sounds reasonable to me. I wonder how the `meshgenerators/tiled_mesh_generator.tiled_mesh_generator_test` test failure is related to BoundingBoxes though...

**Comment by andrsd** [comment]
maybe somebody contributed a bad input file and were bit by the same error I was. they assumed the box was correct, but the swapped coordinates yielded an empty bounding box. with the fix, the test probably does what was the original intention - it now produces 1000 nodes, comparing to the original 729.

**Comment by andrsd** [comment]
nope, I was wrong. it wants to create "empty" bbox and it does a series of unions to come up with minimal bbox. I think if I use the c-tor with no params, it should recover the intended behavior...

**Comment by andrsd** [comment]
Ok, that fixed it...

**Comment by loganharbour** [comment]
Nice 👍

**Comment by roystgnr** [comment]
Seems like a bit of a waste of CPU to force everybody to do six redundant ternary operations, just to allow people to write

```BoundingBox bb(p1, p2);```

instead of

```BoundingBox bb; bb.union_with(p1); bb.union_with(p2);```

Would it be sufficient to instead load the constructor up with assertions, so users who don't think about the sorting issue get a clean error message at the error rather than confusing failures later?

**Comment by andrsd** [comment]
Well, there is 8 combinations how to specify a bounding box and this class will accept only 1. All 8 combinations are valid, but the user has to know which one is the correct one. To me that is not right. Users should not need to know about the internal implementation.

Thanks for considering, I will go patch MOOSE instead.

**Pull request closed without merging**
