### PR TITLE
Have ExactSolution properly handle vector variables

### PR DESCRIPTION
**Pull request by lindsayad**
This enables L2 error calculations for the scalar (at least the way I implemented it) in the RT example. I'd be fine dropping the second commit if the L2 scalar field error calculation in #3674 is better implemented

### CODE REVIEW

**Comment by nmnobre** [comment]
> This enables L2 error calculations for the scalar (at least the way I implemented it) in the RT example. I'd be fine dropping the second commit if the L2 scalar field error calculation in #3674 is better implemented

Your first commit addresses the collision-avoidance problem I was referring to in #3674! Perfect! I'll 
I think we can simplify your second commit, gimme a minute. I'll import your commit, hold on. Thanks!!!!

**Comment by lindsayad** [comment]
Oops just pushed another one. Please feel free to modify the latter two commits (the content in your example) as you desire

**Comment by lindsayad** [comment]
> I'll import your commit, hold on. Thanks!!!!

If you mean incorporate it in #3674, that sounds good, and if so, I will close this.

**Comment by nmnobre** [comment]
> Oops just pushed another one. Please feel free to modify the latter two commits (the content in your example) as you desire

Ahah, your third commit is exactly (part of) what I had on my other branch, this is perfect, I'll just tweak it slightly now.

> If you mean incorporate it in https://github.com/libMesh/libmesh/pull/3674, that sounds good, and if so, I will close this.

Will do.

**Comment by lindsayad** [comment]
closing in favor of #3674

**Pull request closed without merging**
