### PR TITLE
Write named entities to Nemesis files

### LINKED ISSUE #1094: Nemesis Named Mesh Entities
Named mesh entities (blocks, sidesets, etc.) don't seem to be getting written to Nemesis files...

### PR DESCRIPTION
**Pull request by jwpeterson**
Whenever we added named entity writing support to the `ExodusII_IO_Helper`, we never added it to the `Nemesis_IO_Helper`, which has to specialize those functions.

Fixes #1094.

### CODE REVIEW

**Comment by jwpeterson** [comment]
This also conflicted with the patch in #1086, so I rebased that again here: c9d6f9f.

**Comment by friedmud** [comment]
Coolness! Thanks!

**Comment by friedmud** [comment]
How in the heck do I checkout c9d6f9f2 ?  I fetched libMesh/libmesh... but can't find c9d6f9f2 anywhere... doesn't appear to be on any branch...

**Comment by friedmud** [comment]
Ok - got it - I don't know why... but GitHub was showing the commit in `libMesh/libmesh`... but actually it's on your fork.  Weird.

**Comment by friedmud** [comment]
This is kind of working (in simple test codes and checking the resulting Nemesis files with Paraview): but MOOSE is failing when trying to use these Nemesis files:

```
*** ERROR ***
The object 'left' contains the following boundary ids that do no exist on the mesh: 7

[0] /Users/gastdr/projects/moose/framework/src/base/BoundaryRestrictable.C, line 130, compiled nodate at notime
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
```

Do you think it's a problem with MOOSE... or is something off with _reading_ named entities in Nemesis?

**Comment by jwpeterson** [comment]
Hmm... maybe a non-local node id made it into the BoundaryInfo object and then was written out to file?  This happens with the same test mesh when you try to run a problem on it?

**Comment by friedmud** [comment]
Yep

Should be easily reproducible for you... just try to use that mesh with
2d_diffusion_test on 4 processors.

The thing is: I think MooseMesh does an allreduce on the block/boundary
names / IDs specifically to deal with the face that MOOSE objects may be
referencing mesh entities that are not on the local processor.

But something may be messed up there.

**Pull request merged**
