### PR TITLE
Unit test updates

### PR DESCRIPTION
**Pull request by roystgnr**
This is just the parts of #438 that should be currently working; we can get this all in for @pbauman to use ASAP, then hold off on the last few commits there until the new feature is working.

### CODE REVIEW

**Comment by roystgnr** [comment]
Someone want to check and see where the dbg-mode tests are hanging?  A stack trace would be fantastic.  This PR re-activated unit tests in dbg mode, since they worked for me and I figured disabling them had probably been a workaround for some atavistic system that none of us used anymore.  Apparently not.

Whereever the bug is must be in the cppunit *teardown*, too, or MooseBuild of #438 would never have made it to the new failing test there.

**Comment by jwpeterson** [comment]
Isn't there some issue with cppunit and dbg mode, @dschwen was messing with this at one point...

**Comment by permcody** [comment]
There have been in the past, but I think it works for us now. A long time
ago we couldn't even link against the cppunit libraries when using all the
normal libMesh debug flags. There were incompatibilities with the safe
containers. I haven't seen that issue though for awhile but there might
still be something here we need to look at more carefully.

**Comment by roystgnr** [comment]
There's no general issue; the combination is working fine for me.  But there has to be some issue with the config MooseBuild is using.  Open https://www.moosebuild.com/view_result/11333 and you can see it's hung, apparently in the middle of the cppunit compilation (though I suspect there's slightly more output that's buffered).

**Comment by permcody** [comment]
The client died so the server is still waiting for more data... I'll
invalidate and watch the next client that picks it up.

**Comment by roystgnr** [comment]
Huh.  Was the first MooseBuild client death just a coincidence?  I'd have expected ABI incompatibilities to be a deterministic problem...

**Comment by permcody** [comment]
Maybe not - I looked through the log on hpcbuild3 and found this near the end of the unit testing. This shouldn't have killed the client, but something unexpected happened:

```
../../tests/systems/equation_systems_test.C: In member function ‘void EquationSystemsTest::testAddSystem()’:
../../tests/systems/equation_systems_test.C:47:13: warning: unused variable ‘sys’ [-Wunused-variable]
../../tests/systems/equation_systems_test.C: In member function ‘void EquationSystemsTest::testInit()’:
../../tests/systems/equation_systems_test.C:54:13: warning: unused variable ‘sys’ [-Wunused-variable]
../../tests/systems/equation_systems_test.C: In member function ‘void EquationSystemsTest::testPostInitAddSystem()’:
../../tests/systems/equation_systems_test.C:64:13: warning: unused variable ‘sys1’ [-Wunused-variable]
../../tests/systems/equation_systems_test.C:66:13: warning: unused variable ‘sys2’ [-Wunused-variable]
  CXXLD    unit_tests-dbg
make[2]: Leaving directory `/home/moosetest/moose_build/client_0_/libmesh/build/tests'
make  check-TESTS
make[2]: Entering directory `/home/moosetest/moose_build/client_0_/libmesh/build/tests'
.....[0]PETSC ERROR: ------------------------------------------------------------------------
[0]PETSC ERROR: Caught signal number 11 SEGV: Segmentation Violation, probably memory access out of range
[0]PETSC ERROR: Try option -start_in_debugger or -on_error_attach_debugger
[0]PETSC ERROR: or see http://www.mcs.anl.gov/petsc/documentation/faq.html#valgrind[0]PETSC ERROR: or try http://valgrind.org on GNU/linux and Apple Mac OS X to find memory corruption errors
[0]PETSC ERROR: configure using --with-debugging=yes, recompile, link, and run
[0]PETSC ERROR: to get more information on the crash.
[0]PETSC ERROR: --------------------- Error Message ------------------------------------
[0]PETSC ERROR: Signal received!
[0]PETSC ERROR: ------------------------------------------------------------------------
[0]PETSC ERROR: Petsc Release Version 3.4.3, Oct, 15, 2013
[0]PETSC ERROR: See docs/changes/index.html for recent updates.
[0]PETSC ERROR: See docs/faq.html for hints about trouble shooting.
[0]PETSC ERROR: See docs/index.html for manual pages.
[0]PETSC ERROR: ------------------------------------------------------------------------
[0]PETSC ERROR: /home/moosetest/moose_build/client_0_/libmesh/build/tests/.libs/lt-unit_tests-dbg on a arch-linux2-c-opt named hpcbuild3 by moosetest Tue Jan 20 09:49:35 2015
[0]PETSC ERROR: Libraries linked from /opt/moose/petsc/mpich_petsc-3.4.3/gcc-opt/lib
[0]PETSC ERROR: Configure run at Thu Dec 19 16:01:28 2013
[0]PETSC ERROR: Configure options --prefix=/opt/moose/petsc/mpich_petsc-3.4.3/gcc-opt --download-hypre=1 --with-debugging=no --with-openmp=1 --with-pthreadclasses=1 --with-pic=1 --with-shared-libraries=1 --with-cc=mpicc --with-cxx=mpicxx --with-fc=mpif90 --download-f-blas-lapack=1 CC=mpicc CXX=mpicxx FC=mpif90 F77=mpif77 F90=mpif90 CFLAGS="-fPIC -fopenmp" CXXFLAGS="-fPIC -fopenmp" FFLAGS="-fPIC -fopenmp" FCFLAGS="-fPIC -fopenmp" F90FLAGS="-fPIC -fopenmp" F77FLAGS="-fPIC -fopenmp" PETSC_DIR=/opt/moose/stack_src/2nd_build/petsc-3.4.3
[0]PETSC ERROR: ------------------------------------------------------------------------
[0]PETSC ERROR: User provided function() line 0 in unknown directory unknown file
application called MPI_Abort(MPI_COMM_WORLD, 59) - process 0
```

**Comment by roystgnr** [comment]
I'll force-push some commit message changes and see if the problem repeats.

**Comment by roystgnr** [comment]
Sure looks like "problem repeats" to me.  I'll re-remove dbg-mode cppunit tests but with a more detailed warning this time.

**Comment by permcody** [comment]
Confirmed - The log file on hpcbuild4 has the same Signal 11 message in it. The client is still running and waiting for this process to terminate:
```libmesh/build/tests/.libs/lt-unit_tests-dbg```
(we don't have timeouts built into moose_build yet)

**Comment by roystgnr** [comment]
Really wish I could replicate that cppunit+dbg mode problem, but if we leave dbg mode disabled for the unit tests then it looks like the rest of this is fine.  I'll merge today unless anyone screams.

**Pull request merged**
