### PR TITLE
Cache dof indices when computing sparsity

### PR DESCRIPTION
**Pull request by roystgnr**
This gives me about 85% speedup on the test case in
https://github.com/idaholab/moose/issues/9480

### CODE REVIEW

**Comment by dschwen** [comment]
Does it also change the big O?

**Comment by permcody** [comment]
image

**Comment by roystgnr** [comment]
I'm afraid I don't yet understand the asymptotic complexity here.  The stuff I optimized was a loop over elements (1 in this case), over elements coupled to each (1), over target variables (N), over source variables (N), over nodes...

Hmm... and maybe there's another O(N) in the Node DofObject operations, post-Ben's-data-compression?  I need to look at that more carefully.

**Comment by roystgnr** [comment]
There's an O(N_variable_groups) var_to_vg conversion in the DofObject operations, but libMesh defaults identify_variable_groups() to true, and MOOSE doesn't futz with that IIRC, and with that setting on, adding a thousand identically typed variables should give you N_variable_groups==1.

**Comment by roystgnr** [comment]
Wait a minute, we're looking at SCALAR variables here, not variables stored on DofObjects.  And in the SCALAR_dof_indices helper the only loop is over variable order, which should be 1 for every variable.  So we're back to "I don't yet understand", except without the sliver of hope previously implied by "yet".

**Comment by roystgnr** [comment]
Profiling says my remaining time is mostly being spent in handle_vi_vj and operator(), not in the dof_indices methods anymore, so maybe I just removed an O(N^2) term with a huge constant but there's an O(N^3) term with a small constant still hiding in one of those places?

**Comment by roystgnr** [comment]
The std::equal_range search is guaranteed to be O(log2(N)), but here the range should be empty.

The std::lower_bound search that empties the range is guaranteed to be O(log2(N)), and we can probably short-circuit that in the common case (including all cases here) with a single O(1) test?  I'll try that and see if it helps for me.

SparsityPattern::sort_row() is a reverse bubble-sort, which looks insane in general (and probably needs to be reconsidered for 3D problems with lots of non-scalar variables...), but which in *this* case (an already sorted row with middle+1==end) should be O(1).

I'm just not seeing anything I'd expect to be cubic.

**Comment by roystgnr** [comment]
No luck with that short-circuiting test, and there's no other obvious improvements to try, so I'd say let's merge this ASAP and I'll try more subtle changes later.

**Comment by dschwen** [comment]
Sounds good. Thanks for working on it. I'm compiling MOOSE right now with this PR to update the plot on the MOOSE PR

**Comment by roystgnr** [comment]
Great; thanks!  I'd very much like to have my current "big O(N^2) term fixed, smaller O(N^3) term untouched" theory confirmed or denied.

**Comment by dschwen** [comment]
out

**Comment by dschwen** [comment]
I don't know. It looks like you are reducing cost by a constant factor (while keeping an O(1) contribution that comes from the way I time it)

**Comment by roystgnr** [comment]
Hm, it certainly does.  I'll keep hunting, then.  I could buy O(N^2 logN) but there's no way this should be O(N^3).

**Comment by roystgnr** [comment]
Wait - what's "nonlinear"?  Not the same as "lagrange"?

**Comment by jwpeterson** [comment]
> Wait - what's "nonlinear"?

I think it's the same as Lagrage. We often use "nonlinear" to mean "not auxiliary" when referring to variables.

**Comment by dschwen** [comment]
Yeah sorry, I saw I messed up the label but I was too lazy to fix the plot.

**Comment by roystgnr** [comment]
Going to merge this now - I've tried a dozen other possible optimizations with no improvement, so although it seems like there *must* be an O(N/log2(N)) improvement still possible somehow, I don't want the continuing search for it to delay this PR's ~85% improvement.

**Pull request merged**
