### PR TITLE
Update TIMPI; simplify sync CLI option, better enforce empty vectors

### PR DESCRIPTION
**Pull request by loganharbour**

### CODE REVIEW

**Comment by loganharbour** [comment]
@roystgnr - will up TIMPI again here once we improve empty data vector management

**Comment by loganharbour** [comment]
Sweet - looks good to me.

**Review by roystgnr — APPROVED** [review]

**Comment by loganharbour** [comment]
Make sure to merge https://github.com/idaholab/civet_recipes/pull/1214 a few min before this

**Comment by loganharbour** [comment]
MOOSE should pass after https://github.com/idaholab/moose/issues/24051 gets in

**Pull request merged**
