### PR TITLE
Add more information to MeshBase::get_info()

### PR DESCRIPTION
**Pull request by loganharbour**
@roystgnr I think this would be useful... you can be the judge

### CODE REVIEW

**Comment by loganharbour** [comment]
@roystgnr before I jump into this more - please give this a quick lookover and see if this is what you had in mind. I still need to add edgesets and nodesets.

Example output:
```
 Mesh Information:
  elem_dimensions()={2}
  spatial_dimension()=2
  n_nodes()=117
    n_local_nodes()=37
  n_elem()=144
    n_local_elem()=36
    n_active_elem()=144
  n_subdomains()=4
  n_partitions()=4
  n_processors()=4
  n_threads()=1
  processor_id()=0
  is_prepared()=true
  is_replicated()=true

 Mesh Global Bounding Box:
  Minimum: (x,y,z)=(       0,       -1,        0)
  Maximum: (x,y,z)=(       3,        1,        0)

 Mesh Element Type(s):
  TRI3, QUAD4

 Mesh Sidesets:
  Sideset 0 (bottom), 12 sides (EDGE2), 12 elems (TRI3, QUAD4), 13 nodes, side volume = 3
   Bounding box minimum: (x,y,z)=(       0,       -1,        0)
   Bounding box maximum: (x,y,z)=(       3,       -1,        0)
  Sideset 1 (right), 8 sides (EDGE2), 8 elems (QUAD4), 9 nodes, side volume = 2
   Bounding box minimum: (x,y,z)=(       3,       -1,        0)
   Bounding box maximum: (x,y,z)=(       3,        1,        0)
  Sideset 2 (top), 12 sides (EDGE2), 12 elems (TRI3, QUAD4), 13 nodes, side volume = 3
   Bounding box minimum: (x,y,z)=(       0,        1,        0)
   Bounding box maximum: (x,y,z)=(       3,        1,        0)
  Sideset 3 (left), 8 sides (EDGE2), 8 elems (TRI3, QUAD4), 9 nodes, side volume = 2
   Bounding box minimum: (x,y,z)=(       0,       -1,        0)
   Bounding box maximum: (x,y,z)=(       0,        1,        0)
  Sideset 4 (interior), 8 sides (EDGE2), 8 elems (TRI3, QUAD4), 9 nodes, side volume = 2
   Bounding box minimum: (x,y,z)=(       1,       -1,        0)
   Bounding box maximum: (x,y,z)=(       1,        1,        0)

 Mesh Subdomains:
  Subdomain 0: 24 elems (QUAD4), 41 nodes, volume = 1.5
   Bounding box minimum: (x,y,z)=(       0,       -1,        0)
   Bounding box maximum: (x,y,z)=(     2.5,        1,        0)
  Subdomain 1 (dummy): 24 elems (QUAD4), 42 nodes, volume = 1.5
   Bounding box minimum: (x,y,z)=(     0.5,       -1,        0)
   Bounding box maximum: (x,y,z)=(       3,        1,        0)
  Subdomain 2: 48 elems (TRI3), 39 nodes, volume = 1.5
   Bounding box minimum: (x,y,z)=(       0,     -0.5,        0)
   Bounding box maximum: (x,y,z)=(       2,        1,        0)
  Subdomain 3: 48 elems (TRI3), 39 nodes, volume = 1.5
   Bounding box minimum: (x,y,z)=(       0,       -1,        0)
   Bounding box maximum: (x,y,z)=(       2,      0.5,        0)
  Total mesh volume = 6
```

**Comment by roystgnr** [comment]
Looks good so far.

**Comment by roystgnr** [comment]
That complex config CI failure looked like a real -Wshadow issue, but the other failing CI I glanced at just looked like some build box filesystem issue.

**Comment by loganharbour** [comment]
@roystgnr I think this is ready for review....

The only thing I don't like is currently `print_info()` takes the stream as the first parameter. Which means if you want to do more verbose output with `print_info()`, you need to do `print_info(libMesh::out, 2)`. I could move the verbosity level to the first parameter, but I don't want to break things... we definitely don't ever pass in the stream in libMesh, but I'm not sure about other applications.

Here's an example:

```
 Mesh Information:
  elem_dimensions()={2}
  spatial_dimension()=2
  n_nodes()=25
    n_local_nodes()=25
  n_elem()=16
    n_local_elem()=16
    n_active_elem()=16
  n_subdomains()=2
  n_partitions()=1
  n_processors()=1
  n_threads()=1
  processor_id()=0
  is_prepared()=true
  is_replicated()=true

 Mesh Bounding Box:
  Minimum: (x,y,z)=(       0,        0,        0)
  Maximum: (x,y,z)=(       1,        1,        0)
  Delta:   (x,y,z)=(       1,        1,        0)

 Mesh Element Type(s):
  QUAD4

 Mesh Nodesets:
  Nodeset 0 (bottom), 5 nodes
   Bounding box minimum: (x,y,z)=(       0,        0,        0)
   Bounding box maximum: (x,y,z)=(       1,        0,        0)
   Bounding box delta: (x,y,z)=(       1,        0,        0)
  Nodeset 1 (right), 5 nodes
   Bounding box minimum: (x,y,z)=(       1,        0,        0)
   Bounding box maximum: (x,y,z)=(       1,        1,        0)
   Bounding box delta: (x,y,z)=(       0,        1,        0)
  Nodeset 2 (top), 5 nodes
   Bounding box minimum: (x,y,z)=(       0,        1,        0)
   Bounding box maximum: (x,y,z)=(       1,        1,        0)
   Bounding box delta: (x,y,z)=(       1,        0,        0)
  Nodeset 3 (left), 5 nodes
   Bounding box minimum: (x,y,z)=(       0,        0,        0)
   Bounding box maximum: (x,y,z)=(       0,        1,        0)
   Bounding box delta: (x,y,z)=(       0,        1,        0)

 Mesh Sidesets:
  Sideset 0 (bottom), 4 sides (EDGE2), 4 elems (QUAD4), 5 nodes
   Side volume: 1
   Bounding box minimum: (x,y,z)=(       0,        0,        0)
   Bounding box maximum: (x,y,z)=(       1,        0,        0)
   Bounding box delta: (x,y,z)=(       1,        0,        0)
  Sideset 1 (right), 4 sides (EDGE2), 4 elems (QUAD4), 5 nodes
   Side volume: 1
   Bounding box minimum: (x,y,z)=(       1,        0,        0)
   Bounding box maximum: (x,y,z)=(       1,        1,        0)
   Bounding box delta: (x,y,z)=(       0,        1,        0)
  Sideset 2 (top), 4 sides (EDGE2), 4 elems (QUAD4), 5 nodes
   Side volume: 1
   Bounding box minimum: (x,y,z)=(       0,        1,        0)
   Bounding box maximum: (x,y,z)=(       1,        1,        0)
   Bounding box delta: (x,y,z)=(       1,        0,        0)
  Sideset 3 (left), 4 sides (EDGE2), 4 elems (QUAD4), 5 nodes
   Side volume: 1
   Bounding box minimum: (x,y,z)=(       0,        0,        0)
   Bounding box maximum: (x,y,z)=(       0,        1,        0)
   Bounding box delta: (x,y,z)=(       0,        1,        0)

 Mesh Edgesets:
  None

 Mesh Subdomains:
  Subdomain 0: 8 elems (QUAD4, 8 active), 15 active nodes
   Volume: 0.5
   Bounding box minimum: (x,y,z)=(       0,        0,        0)
   Bounding box maximum: (x,y,z)=(     0.5,        1,        0)
   Bounding box delta: (x,y,z)=(     0.5,        1,        0)
  Subdomain 1 (dummy): 8 elems (QUAD4, 8 active), 15 active nodes
   Volume: 0.5
   Bounding box minimum: (x,y,z)=(     0.5,        0,        0)
   Bounding box maximum: (x,y,z)=(       1,        1,        0)
   Bounding box delta: (x,y,z)=(     0.5,        1,        0)
  Global mesh volume = 1
```

**Comment by roystgnr** [comment]
I don't see any obvious problems.  I'd say after those fixup commits are all rebased away we should be good to merge.

**Comment by loganharbour** [comment]
This is good to go.

**Pull request merged**
