### PR TITLE
Revert "Use typeid for hashing (#3010)"

### PR DESCRIPTION
**Pull request by dschwen**
This reverts commit 70520ea2f28d0581befccec5e50441e69057616f.

ABORT ABORT ABORT

### CODE REVIEW

**Comment by jwpeterson** [comment]
You know what, at least it compiled!

**Comment by dschwen** [comment]
I'm glad I'm able to exceed your extremely low expectations!

**Review by lindsayad — APPROVED** [review]

**Comment by jwpeterson** [comment]
I'm guessing the failures are to be expected/not related to this PR, since it's only a revert, so I'm going to go ahead and merge.

**Comment by lindsayad** [comment]
Yes those failures are all expected after the affine map tolerance tightening. Hopefully getting that fixed soon over at https://github.com/idaholab/moose/pull/18705

**Comment by dschwen** [comment]
Sigh, if only I had explained why this failed and why we had to revert this back then...

**Pull request merged**
