### PR TITLE
Fparser JIT Refactor

### LINKED ISSUE #2345: Refactor FParser code generation and just in time compilation
I need this to be more flexible to support JIT with dual numbers and batch compilation. In batch compilation multiple functions will be compiled in a single pass. This should reduce overhead from multiple compiler launches. This functionality will require a global storage (or material object level management of batches) for function objects, which will most likely be implemented on the MOOSE side.

### PR DESCRIPTION
**Pull request by dschwen**
Make the FParser JIT routines more modular and flexible. This will enable the use of MetaPhysicL in parsed functions (as long as they are compiled at least). It also opens up the API to enable batch compilation (multiple functions in one JIT compile run).

Closes #2345

### CODE REVIEW

**Comment by jwpeterson** [comment]
Thanks, this looks like it will also fix the `-Wunused-result` warnings I was getting from this line:
```
../../../contrib/fparser/fparser_ad.cc:1053:9: warning: ignoring return value of ‘int link(const char*, const char*)’, declared with attribute warn_unused_result [-Wunused-result]
     link(object_so.c_str(), libname.c_str());
     ~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by dschwen** [comment]
Yeah. I also reworked a ton of diagnostic pragmas (as clang understands some GCC stuff). For me this resulted in a significant net reduction of compiler warnings but it may not be perfect yet.

**Comment by dschwen** [comment]
Hmm, looks like there is some more debugging to be done. Let me see if I can reproduce the failures.

**Comment by dschwen** [comment]
Looks better, but there still is a failure in Marmot that appears to be unrelated to this PR (the input does not use parsed functions at all). In debug it spits out this:

```
Initial adaptivity step 1 of 1 .Assertion `elem.refinement_flag() == Elem::JUST_COARSENED' failed.
elem.refinement_flag() = 3
Elem::JUST_COARSENED = 4


Stack frames: 23
0: libMesh::print_trace(std::ostream&)
1: libMesh::MacroFunctions::report_error(char const*, int, char const*, char const*)
2: libMesh::OldSolutionBase<libMesh::VectorValue<double>, &(void libMesh::FEMContext::point_gradient<libMesh::VectorValue<double> >(unsigned int, libMesh::Point const&, libMesh::VectorValue<double>&, double) const)>::check_old_context(libMesh::FEMContext const&, libMesh::Point const&)
3: libMesh::OldSolutionValue<libMesh::VectorValue<double>, &(void libMesh::FEMContext::point_gradient<libMesh::VectorValue<double> >(unsigned int, libMesh::Point const&, libMesh::VectorValue<double>&, double) const)>::eval_at_point(libMesh::FEMContext const&, unsigned int, libMesh::Point const&, double)
4: libMesh::GenericProjector<libMesh::OldSolutionValue<double, &(void libMesh::FEMContext::point_value<double>(unsigned int, libMesh::Point const&, double&, double) const)>, libMesh::OldSolutionValue<libMesh::VectorValue<double>, &(void libMesh::FEMContext::point_gradient<libMesh::VectorValue<double> >(unsigned int, libMesh::Point const&, double&, double) const)>, double, libMesh::VectorSetAction<double> >::ProjectVertices::operator()(libMesh::StoredRange<__gnu_debug::_Safe_iterator<__gnu_cxx::__normal_iterator<std::pair<libMesh::Node const*, std::tuple<libMesh::Elem const*, unsigned short, std::__debug::set<unsigned int, std::less<unsigned int>, std::allocator<unsigned int> > > > const*, std::__cxx1998::vector<std::pair<libMesh::Node const*, std::tuple<libMesh::Elem const*, unsigned short, std::__debug::set<unsigned int, std::less<unsigned int>, std::allocator<unsigned int> > > >, std::allocator<std::pair<libMesh::Node const*, std::tuple<libMesh::Elem const*, unsigned short, std::__debug::set<unsigned int, std::less<unsigned int>, std::allocator<unsigned int> > > > > > >, std::__debug::vector<std::pair<libMesh::Node const*, std::tuple<libMesh::Elem const*, unsigned short, std::__debug::set<unsigned int, std::less<unsigned int>, std::allocator<unsigned int> > > >, std::allocator<std::pair<libMesh::Node const*, std::tuple<libMesh::Elem const*, unsigned short, std::__debug::set<unsigned int, std::less<unsigned int>, std::allocator<unsigned int> > > > > >, std::random_access_iterator_tag>, std::pair<libMesh::Node const*, std::tuple<libMesh::Elem const*, unsigned short, std::__debug::set<unsigned int, std::less<unsigned int>, std::allocator<unsigned int> > > > > const&)
5: void libMesh::Threads::parallel_reduce<libMesh::StoredRange<__gnu_debug::_Safe_iterator<__gnu_cxx::__normal_iterator<std::pair<libMesh::Node const*, std::tuple<libMesh::Elem const*, unsigned short, std::__debug::set<unsigned int, std::less<unsigned int>, std::allocator<unsigned int> > > > const*, std::__cxx1998::vector<std::pair<libMesh::Node const*, std::tuple<libMesh::Elem const*, unsigned short, std::__debug::set<unsigned int, std::less<unsigned int>, std::allocator<unsigned int> > > >, std::allocator<std::pair<libMesh::Node const*, std::tuple<libMesh::Elem const*, unsigned short, std::__debug::set<unsigned int, std::less<unsigned int>, std::allocator<unsigned int> > > > > > >, std::__debug::vector<std::pair<libMesh::Node const*, std::tuple<libMesh::Elem const*, unsigned short, std::__debug::set<unsigned int, std::less<unsigned int>, std::allocator<unsigned int> > > >, std::allocator<std::pair<libMesh::Node const*, std::tuple<libMesh::Elem const*, unsigned short, std::__debug::set<unsigned int, std::less<unsigned int>, std::allocator<unsigned int> > > > > >, std::random_access_iterator_tag>, std::pair<libMesh::Node const*, std::tuple<libMesh::Elem const*, unsigned short, std::__debug::set<unsigned int, std::less<unsigned int>, std::allocator<unsigned int> > > > >, libMesh::GenericProjector<libMesh::OldSolutionValue<double, &(void libMesh::FEMContext::point_value<double>(unsigned int, libMesh::Point const&, double&, double) const)>, libMesh::OldSolutionValue<libMesh::VectorValue<double>, &(void libMesh::FEMContext::point_gradient<libMesh::VectorValue<double> >(unsigned int, libMesh::Point const&, double&, double) const)>, double, libMesh::VectorSetAction<double> >::ProjectVertices>(libMesh::StoredRange<__gnu_debug::_Safe_iterator<__gnu_cxx::__normal_iterator<std::pair<libMesh::Node const*, std::tuple<libMesh::Elem const*, unsigned short, std::__debug::set<unsigned int, std::less<unsigned int>, std::allocator<unsigned int> > > > const*, std::__cxx1998::vector<std::pair<libMesh::Node const*, std::tuple<libMesh::Elem const*, unsigned short, std::__debug::set<unsigned int, std::less<unsigned int>, std::allocator<unsigned int> > > >, std::allocator<std::pair<libMesh::Node const*, std::tuple<libMesh::Elem const*, unsigned short, std::__debug::set<unsigned int, std::less<unsigned int>, std::allocator<unsigned int> > > > > > >, std::__debug::vector<std::pair<libMesh::Node const*, std::tuple<libMesh::Elem const*, unsigned short, std::__debug::set<unsigned int, std::less<unsigned int>, std::allocator<unsigned int> > > >, std::allocator<std::pair<libMesh::Node const*, std::tuple<libMesh::Elem const*, unsigned short, std::__debug::set<unsigned int, std::less<unsigned int>, std::allocator<unsigned int> > > > > >, std::random_access_iterator_tag>, std::pair<libMesh::Node const*, std::tuple<libMesh::Elem const*, unsigned short, std::__debug::set<unsigned int, std::less<unsigned int>, std::allocator<unsigned int> > > > > const&, libMesh::GenericProjector<libMesh::OldSolutionValue<double, &(void libMesh::FEMContext::point_value<double>(unsigned int, libMesh::Point const&, double&, double) const)>, libMesh::OldSolutionValue<libMesh::VectorValue<double>, &(void libMesh::FEMContext::point_gradient<libMesh::VectorValue<double> >(unsigned int, libMesh::Point const&, double&, double) const)>, double, libMesh::VectorSetAction<double> >::ProjectVertices&)
6: libMesh::GenericProjector<libMesh::OldSolutionValue<double, &(void libMesh::FEMContext::point_value<double>(unsigned int, libMesh::Point const&, double&, double) const)>, libMesh::OldSolutionValue<libMesh::VectorValue<double>, &(void libMesh::FEMContext::point_gradient<libMesh::VectorValue<double> >(unsigned int, libMesh::Point const&, double&, double) const)>, double, libMesh::VectorSetAction<double> >::project(libMesh::StoredRange<libMesh::MeshBase::const_element_iterator, libMesh::Elem const*> const&)
7: libMesh::System::project_vector(libMesh::NumericVector<double> const&, libMesh::NumericVector<double>&, int) const
8: libMesh::System::project_vector(libMesh::NumericVector<double>&, int) const
9: libMesh::System::restrict_vectors()
10: libMesh::System::prolong_vectors()
11: libMesh::EquationSystems::reinit_solutions()
12: libMesh::EquationSystems::reinit()
13: FEProblemBase::meshChangedHelper(bool)
14: FEProblemBase::meshChanged()
15: FEProblemBase::initialAdaptMesh()
16: FEProblemBase::initialSetup()
17: Transient::init()
18: MooseApp::executeExecutioner()
19: MooseApp::run()
20: ../../marmot-dbg(+0x20fe1) [0x56551393cfe1]
21: __libc_start_main
22: ../../marmot-dbg(+0x20e4e) [0x56551393ce4e]
```

What could trigger this?

**Comment by roystgnr** [comment]
What the heck?  I assume you can replicate that with libMesh master?  Even if there was an fparser use sneaking into that test somewhere I can't see how it would have led to that failure.

Going through that stack trace bottom to top:
We're in a mesh-to-mesh projection
We're interpolating at vertices
We're asking for VectorValue data (this is doing Cahn-Hilliard on HERMITE elements, right?)
We're directly calling eval_at_point, so we know we're not at an old node; we're either at a newly refined node or we're doing finite differencing for the HERMITE cross derivative DoF(s)
We're first using check_old_context to see if we can reuse the FEMContext's previous pre_fe_reinit data.
In check_old_context, we're still in the same elem we used last, and we have an old_context elem ready that might match it, but the old elem doesn't contain the point we're searching for, and we're screaming because it's *not* because the old elem just got coarsened away and we should search one of its siblings instead.

Whew, that was fun.

I have a suspicion about what could be happening, but I can't see why my guess would only happen as some corner case, rather than with practically *every* HERMITE projection.

**Comment by roystgnr** [comment]
Could just be that something about element sizes in Marmot is interacting with the out_of_elem_tol in that projection in ways my own HERMITE runs don't.

Let me try a possible fix.

**Comment by dschwen** [comment]
I can share a redacted MOOSE input (won't run without specific Marmot Kernels, but should give you an idea of the setup)

```
[Mesh]
  type = GeneratedMesh
  dim = 2
  nx = 4
  ny = 4
  xmax = 25
  ymax = 25
  elem_type = QUAD4
  uniform_refine = 1
[]

[Variables]
  [./cv]
    order = THIRD
    family = HERMITE
    [./InitialCondition]
      type = SmoothCircleIC
      x1 = 12.5
      y1 = 12.5
      radius = 6.0
      invalue = 1.0
      outvalue = 0.1
      int_width = 4.0
    [../]
  [../]
[]

[Kernels]
  [./ie_c]
    type = TimeDerivative
    variable = cv
  [../]
  [./CHSolid]
    type = CHPhys
    variable = cv
    mob_name = Ms_v
  [../]
  [./CHInterface]
    type = CHInterface
    variable = cv
    mob_name = M_v
    kappa_name = kappa_v
  [../]
[]

[BCs]
  [./Periodic]
    [./all]
      auto_direction = 'x y'
    [../]
  [../]
[]

[Materials]
  [./GenIrrad]
    type = CTempIrrad
    # redacted parameters 
  [../]
[]

[Executioner]
  type = Transient
  scheme = bdf2
  solve_type = 'PJFNK'

  petsc_options_iname = '-pc_type -pc_hypre_type -ksp_gmres_restart'
  petsc_options_value = 'hypre boomeramg 101'
  l_max_its = 15
  l_tol = 1.0e-4
  nl_max_its = 40
  nl_rel_tol = 1e-10
  start_time = 0.0
  num_steps = 2
  dt = 1.0

  [./Adaptivity]
    initial_adaptivity = 1
    error_estimator = LaplacianErrorEstimator
    refine_fraction = 0.8
    coarsen_fraction = 0.05
    max_h_level = 2
  [../]
[]

[Outputs]
  exodus = true
[]
```

**Comment by dschwen** [comment]
An I now have confirmed the error occurs with current libmesh master as well

**Comment by roystgnr** [comment]
Damn.  My first idea for the fix won't work on domain boundaries, only on interior vertices.  Let me try one more idea.

**Comment by roystgnr** [comment]
Mind if I push proposals to this branch?

**Comment by dschwen** [comment]
sure, go ahead

**Comment by roystgnr** [comment]
I finally came up with something that should work in all cases and shouldn't cause any serious slowdowns (might speed up HERMITE interpolation a touch even).  Whether it actually *works*, we'll find out.

**Comment by dschwen** [comment]
Hm, this seems to fix the issue with that test!

**Comment by roystgnr** [comment]
Nice!  We could merge that commit via a separate PR if anyone wants to be a stickler about proper organization, but IMHO we ought to just hit the button on this one as soon as we're sure I didn't regress any *other* tests.

**Comment by jwpeterson** [comment]
> I can't see why my guess would only happen as some corner case, rather than with practically every HERMITE projection.

Did you figure out this out to your satisfaction?

**Comment by dschwen** [comment]
Cool, now two new tests are segfaulting...

**Comment by roystgnr** [comment]
Really wish we got line numbers out of print_trace().

> Did you figure out this out to your satisfaction?

I have a plausible hypothesis regarding my own codes - our HERMITE adaptivity CI is only running on 1D elements, so it doesn't the affected cases, and the bug may be recent enough that it post dates my own adaptive HERMITE runs.  I'm not sure why nobody's seen it in Marmot before now, though; if I'm understanding this bug right (which is still questionable too) it's a couple years old.

**Comment by dschwen** [comment]
Roy, let me see if I can furnish a MOOSE only test...

**Comment by roystgnr** [comment]
Thanks!  I'm trying to replicate it with libMesh only but so far I'm having no luck.

**Comment by dschwen** [comment]
This triggers the bug for me:

```
[Mesh]
  type = GeneratedMesh
  dim = 2
  nx = 1
  ny = 1
  uniform_refine = 3
[]

[Variables]
  [./c]
    order = THIRD
    family = HERMITE
    [./InitialCondition]
      type = SmoothCircleIC
      x1 = 0.5
      y1 = 0.5
      radius = 0.1
      invalue = 1.0
      outvalue = 0.05
      int_width = 0.2
    [../]
  [../]
[]

[Kernels]
  [./diff]
    type = Diffusion
    variable = c
  [../]
[]

[BCs]
  [./Periodic]
    [./all]
      auto_direction = 'x y'
      variable = c
    [../]
  [../]
[]

[Executioner]
  type = Steady

  [./Adaptivity]
    initial_adaptivity = 2
    error_estimator = LaplacianErrorEstimator
    refine_fraction = 0.8
    coarsen_fraction = 0.05
    max_h_level = 3
  [../]
[]
```

with `uniform_refine = 2` it runs...

**Comment by roystgnr** [comment]
Okay, I think I finally understand why the patch is failing here.  I'd assumed we could always skip the context check at perturbed points because we've just used the context to evaluate the gradient at the center point, but that's not true if the center point was also a node on the old mesh and so we were able to just straight-up copy gradient data there.

Ideally we'd just straight-up copy the mixed derivative data there too ... that doesn't work with the existing APIs but it'd be easy enough to add a new (and backwards-compatible) API to fix it.  I'll try that.  That'd make HERMITE projections faster and give them less roundoff error too ... just hope we don't have any gold standard solutions depending on the roundoff error.

**Comment by roystgnr** [comment]
Abusing CI right now; I'm running late and haven't properly tested this myself yet...

**Comment by roystgnr** [comment]
Passing my tests too.  I think these two together are the right fix.  Going to hold off on hitting the button in case anyone else wants more time to look it over, though.

**Comment by jwpeterson** [comment]
> in case anyone else wants more time to look it over, though.

This seems like it could be cleaned up a bit, no? Daniel's first fixup commit should be squashed into the originals, and your fixes-that-didnt-quite-work could be squashed and merged first, independently of Daniel's PR. I can take the lead on this unless you really want to merge this as-is.

**Comment by dschwen** [comment]
Let me squash my stuff...

**Comment by jwpeterson** [comment]
> Let me squash my stuff...

Thanks for that. I figured this would trigger a rerun of CI, but it appears not to... in this case that's actually desired but OTOH I'm thinking it means something must have gone wrong with moosebuild.

**Comment by roystgnr** [comment]
Huh, that is weird.  My squash didn't trigger CI either.

**Comment by roystgnr** [comment]
I didn't actually change or even reorder anything, though, so I'm still happy if you want to hit the button rather than wait for redundant CI.

**Comment by jwpeterson** [comment]
failed

Last three moosebuild payloads failed to be delivered. Could be an issue on the GitHub side but seems more likely to be on the moosebuild side. Anyway, I'm going to merge as-is.

**Comment by permcody** [comment]
We are experiencing a significant power issue at the lab today. One of our
data centers is offline and possibly other important routers/switches in
another building. We've been without access to the HPC since around noon.
It may be awhile until power is restored.

**Pull request merged**
