### PR TITLE
Get revision information when libmesh is a submodule

### LINKED ISSUE #1476: Git revision info not available when libmesh is a submodule
As discussed in idaholab/moose#10163, git revision information is not available during configure  when libmesh is being used as a submodule because $srcdir/.git is a file and not a directory.

### PR DESCRIPTION
**Pull request by jessecarterMOOSE**
Changed the test to allow `$srcdir/.git` to be a file or a directory to allow for the case when libmesh is being used as a submodule.

Closes #1476

### CODE REVIEW

**Comment by jessecarterMOOSE** [comment]
P.S. This is my first libmesh PR so if please let me know if I didn't adhere to your guidelines.

**Comment by jwpeterson** [comment]
@jessecarterMOOSE I invited you to join the list of developers who get their libmesh PRs tested automatically.

**Comment by jessecarterMOOSE** [comment]
Joined. Thanks!

**Comment by roystgnr** [comment]
Looks good.  The only annoying libMesh-specific guidelines applicable here are "don't forget to bootstrap" and "keep the bootstrap in a separate commit".

**Pull request merged**
