### PR TITLE
Weaken copy_node_and_elements partition assertion

### PR DESCRIPTION
**Pull request by roystgnr**
This will hopefully be sufficient to fix current #1512 problems.

### CODE REVIEW

**Comment by permcody** [comment]
@gardnerru  - Can you pull this patch and see if it fixes the debug runs of the CASL problem with BISON?

**Comment by gardnerru** [comment]
yea, looking now

**Comment by gardnerru** [comment]
Looks like a winner. I ran the input that I received when this was first presented in serial, 4 procs and 8 procs and they all ran. Thanks

**Comment by jwpeterson** [comment]
Thanks @gardnerru for testing it.

**Pull request merged**
