### PR TITLE
Set extra integer on boundary_mesh elems corresponding to parent side index

### PR DESCRIPTION
**Pull request by jwpeterson**
Refs #2457

### CODE REVIEW

**Comment by jwpeterson** [comment]
This is not yet optional as we discussed in #2457, I want to see if there are any major issues with the idea before updating the relevant `BoundaryInfo` APIs.

**Comment by roystgnr** [comment]
Looks good to me once you add the optionality.

**Comment by jwpeterson** [comment]
@roystgnr please review again when you have the time, the setting of parent side ids is now optional.

**Comment by roystgnr** [comment]
Looks good enough to me.  We might go back and add the flag to sync() too if anyone complains in the future.

**Comment by jwpeterson** [comment]
Thanks!

**Pull request merged**
