### PR TITLE
Mixed dimension refinement fixes/more testing

### PR DESCRIPTION
**Pull request by pbauman**
All @cahaynes work in #691 and @roystgnr fix cherry-picked.

@cahaynes, comments from #691 still apply, namely fixing the commit logs on b1a376d and f81f4dd (both authorship and actual log entry), and checking for another place that needed a fix similar to cad4add (I thought there were two cases, but I don't remember offhand where the other was, check you email.)

You can `git remote add pbauman git@github.com:pbauman/libmesh` to add me as a remote, `git fetch pbauman`, and `git checkout pbauman cahaynes-mixed-dim-refinement`. After that, you can `git branch your-new-branch` and work on that new branch to revise history and add new commits, if needed. We can go over this more tomorrow as well.

Otherwise, let's see if Civet is happier with this one.

### CODE REVIEW

**Comment by pbauman** [comment]
Also, @roystgnr, we can park your fix at the beginning of the list of the commits, or take it out entirely if you'd rather commit as a separate PR.

**Comment by roystgnr** [comment]
I'd move it to the beginning; thanks.

**Comment by pbauman** [comment]
Arg, still getting a `fem_system_ex4` failure:

<pre>
Adaptive step 0: 
Assertion `!elem->has_dofs(sys_num) || elem->p_refinement_flag() == Elem::JUST_REFINED || elem->old_dof_object' failed.

Stack frames: 13
0: libMesh::print_trace(std::ostream&)
1: libMesh::MacroFunctions::report_error(char const*, int, char const*, char const*)
2: libMesh::DofMap::old_dof_indices(libMesh::Elem const*, std::__debug::vector<unsigned int, std::allocator<unsigned int> >&, unsigned int) const
3: libMesh::BuildProjectionList::operator()(libMesh::StoredRange<libMesh::MeshBase::const_element_iterator, libMesh::Elem const*> const&)
4: void libMesh::Threads::parallel_reduce<libMesh::StoredRange<libMesh::MeshBase::const_element_iterator, libMesh::Elem const*>, libMesh::BuildProjectionList>(libMesh::StoredRange<libMesh::MeshBase::const_element_iterator, libMesh::Elem const*> const&, libMesh::BuildProjectionList&)
5: libMesh::System::project_vector(libMesh::NumericVector<double> const&, libMesh::NumericVector<double>&, int) const
6: libMesh::System::project_vector(libMesh::NumericVector<double>&, int) const
7: libMesh::System::restrict_vectors()
8: libMesh::System::prolong_vectors()
9: libMesh::EquationSystems::reinit()
</pre>

**Comment by roystgnr** [comment]
I can replicate that (and on one processor this time!) but I don't understand it.  One of the QUAD9s on the EDGE3 boundary seems to be getting refined twice within a single AMR step.  The consequence of this is a straightforward failure: one of the newly created elements looks to its parent for an old_dof_object with old solution indices, and this doesn't exist except on the grandparent.  The *cause*, on the other hand, I don't see.

**Comment by jwpeterson** [comment]
Closing this as I believe it was superseded by #694.

**Pull request closed without merging**
