### PR TITLE
Rereoptimize projections

### PR DESCRIPTION
**Pull request by roystgnr**
Hopefully this will fix the last of the performance regressions well enough; it adds special cases for the rest of the LAGRANGE dofs, which ought to be a decent help in 3D.

This needs to get more testing before merge.

### CODE REVIEW

**Comment by roystgnr** [comment]
This is working with libMesh, MOOSE, and GRINS now, at least.

**Comment by jwpeterson** [comment]
Let me try a libmesh update PR over in MOOSE, let this run through the various apps?

**Comment by roystgnr** [comment]
Very good; I won't merge until we see the results of that.

**Comment by jwpeterson** [comment]
Testing now at idaholab/moose#6236.

**Comment by roystgnr** [comment]
For reference, this extends the changes in #696 to try to re-optimize the refactoring from #680.

**Comment by roystgnr** [comment]
There's a nasty failure in idaholab/moose#6236, but I can replicate it with libMesh versions predating this patch, so I think we're clear here.

**Comment by roystgnr** [comment]
Note for the future: I've thought of one more way to speed up the LAGRANGE code path, but that can go on the back burner indefinitely.  I don't expect it to be a significant improvement, but I do expect to eventually be intolerably tempted to create a "Rerereoptimize projections" PR.

**Pull request merged**
