### PR TITLE
CheckpointIO support for extra DofObject integers

### LINKED ISSUE #2095: Add two integers to Elem
We have a need for two `unsigned int`s to get added to `Elem`.  I propose: `user_id1` and `user_id2`.  This will be controlled with `--enable-extra-elem-ids` at configure time (and configured to `false` by default).  These IDs will be user settable - but otherwise will act just like `subdomain_id` and `unique_id`.

This is something that we've had to engineer around for a long time in one of our applications (Rattlesnake) and there's just no reason for it.

Eventually maybe https://github.com/libMesh/libmesh/issues/1439 will obviate the need for this (maybe)... but there's no reason to wait for that.

### PR DESCRIPTION
**Pull request by roystgnr**
If this works, it should *actually* close #2095 

My brain is pretty frazzled right now, so it probably doesn't work yet and shouldn't be merged until it gets some test coverage; I just want to let CI and @YaqiWang get an early look before I get started on unit tests.

### CODE REVIEW

**Comment by YaqiWang** [comment]
Extra integers are supposed to be set during mesh generation, which should be skipped during recovering. So extra integers need to be written to and load from the checkpoint file. I do not care much how it is done just needs to be transparent to users as the other parts of the mesh. The interface changes in getting the index, writing the integers, etc. are good. Thanks Roy for putting all these in.

**Comment by roystgnr** [comment]
> Extra integers are supposed to be set during mesh generation, which should be skipped during recovering. So extra integers need to be written to and load from the checkpoint file.

That's what we're doing here.  The only limitation is that the recovery should be done into either an empty Mesh or into a mesh that has had the exact same extra integers added in the same order, otherwise we scream and die at runtime.

Which I'm not proud of but honestly reading into a non-empty Mesh probably breaks in all kinds of ways with various MeshInput subclasses, since in user code we generally create a new Mesh object whenever we want to read in a new file.
...
Or we clear an old Mesh.  Damn.  I just realized that MeshBase::clear() isn't clearing the extra_integers metadata.  I'll fix that.

**Comment by roystgnr** [comment]
> Damn. I just realized that MeshBase::clear() isn't clearing the extra_integers metadata. I'll fix that.

Or... maybe I won't.  Our MeshGeneration methods call clear() before creating new elements, so we certainly can't remove add_elem_integer results there!

I don't like the idea of clear() not meaning "restore to a pristine state" but I don't see a way around this other than to document the unintuitive behavior.

**Comment by YaqiWang** [comment]
@roystgnr since you are working on recover here. I have a quick question: can I just read one entry in a recover file, for example, read one variable, assuming mesh, target variable space have been setup properly?

**Comment by roystgnr** [comment]
Hmm... in 2011 I added support for "upconverting" EquationSystems xdr/xda saves: e.g. you could save a reaction problem based on a model with a few chemical species, then read that file into a more complicated chemistry system that had additional species too, and the matching variables would be read from file while the non-matching variables would remain at zero (or IIRC remain at their old values if they'd already been set in some other fashion).

But that only works if the variable(s) you want to read are the only ones in the save file.  I don't think we have any means to extract only some variables' data from a save file that has more, or to save data from only a subset of variables to a file.

**Comment by pbauman** [comment]
> I don't think we have any means to extract only some variables' data from a save file that has more, or to save data from only a subset of variables to a file.

Don't we have a libMesh app that does something along these lines though?

**Comment by roystgnr** [comment]
> Don't we have a libMesh app that does something along these lines though?

Ha!  solution_components, yeah.

My brain's stopped working.  Today in my dad's neurology room I was asking the staff if they had any two-for-the-price-of-one deals...

**Pull request merged**
