### PR TITLE
projection_matrix() unit tests

### PR DESCRIPTION
**Pull request by roystgnr**
Swiping commits from @bboutkov.  He did all the work and deserves all the credit, but this way if there are any more conflicts with --enable-complex, --enable-parmesh, --enable-mesopotamian-mode, etc. then I can add fixes quickly.

### CODE REVIEW

**Comment by pbauman** [comment]
@bboutkov can chime in here. He and I were chatting earlier and he said he was hitting snags with the node number in the DistributedMesh, at which point I suggested he do exactly what @roystgnr did: open a PR for discussion.

**Comment by bboutkov** [comment]
Yeah sorry, communications a bit outta sync but as discussed - the DistributedMesh case fails because node numbering on DistributedMesh wont match the SerialMesh case upon refinement despite the coarse node numbering generated by MeshGeneration matching. As far as I understand we need to do the node->dof mapping even more manually by referencing the physical node coordinates.

**Comment by roystgnr** [comment]
Is this even running on ReplicatedMesh in parallel?  The node numbering may match the serial case, but the dof numbering won't...

**Comment by roystgnr** [comment]
Ah, never mind, I see the node2dof translations you're using.  And this is passing on ReplicatedMesh in parallel for me, so forcing ReplicatedMesh ought to be sufficient for now.

**Pull request merged**
