### PR TITLE
Add in-place L2 norm difference method

### PR DESCRIPTION
**Pull request by loganharbour**

### CODE REVIEW

**Comment by loganharbour** [comment]
@roystgnr please

**Comment by loganharbour** [comment]
@jwpeterson - Roy is looking for your opinions for naming `readable()` and `comparable()` in https://github.com/libMesh/libmesh/pull/3603/commits/9acd8d3ce15307c75966c8bd9a22928c5ee552fb; mind taking a look?

**Comment by jwpeterson** [comment]
OK, so the question is just if those are good names for the functions? Seems OK to me, might change `comparable` -> `compatible` since the word "comparable" is commonly used in the context of STL strict weak orderings.

**Comment by loganharbour** [comment]
> OK, so the question is just if those are good names for the functions? S

Yep - that's it. We hit some stupid mistakes not understanding a result when we forgot to close, so decided to clean that up here.

> might change `comparable` -> `compatible` since the word "comparable" is commonly used in the context of STL strict weak orderings.

Works for me.

**Comment by loganharbour** [comment]
@roystgnr good to go.

**Review by roystgnr — APPROVED** [review]

**Pull request merged**
