### PR TITLE
Add nonblocking packed range push

### PR DESCRIPTION
**Pull request by roystgnr**
My attempt to rebase and fix compatibility issues with #2264 

@loganharbour - give it a look over?

We really ought to get some CI coverage on this, but I know it's hard to get nonblocking stuff properly covered in small unit tests, so we can merge without.

### CODE REVIEW

**Comment by loganharbour** [comment]
At the very least, let me try this in @friedmud's code that used it first and see if those tests pass.

**Comment by loganharbour** [comment]
Added a mac test to this because I'm having issues compiling timpi locally

**Comment by loganharbour** [comment]
Had some Xcode issues that were unrelated locally. This works with the implementation I have and also with Derek's code.

**Comment by roystgnr** [comment]
Glad to hear!  Now the question is what's working on your Mac that isn't working in CI...  That error doesn't look related at all, so I'll just kick it first and see if there was some MPI fluke.

**Comment by loganharbour** [comment]
Just FYI... we came across some issues with Xcode headers and some changes that were introduced in TIMPI. We found a fix for it and are trying to replicate/document it.

**Comment by roystgnr** [comment]
Thanks!  I assume the fix is on the Xcode side?  If you can replicate the problem then I'd love to hunt for workarounds too, just to make things as easy as possible on other users.

Okay, so I restarted the Test Mac build because of one unrelated-looking failure in a MOOSE test, and now I'm seeing a segfault in the libMesh unit tests that wasn't there before?  What on Earth?

**Comment by loganharbour** [comment]
Here's an example of the compile error:
```
In file included from /Users/icenct/projects/moose/scripts/../libmesh/contrib/timpi/src/parallel/src/message_tag.C:22:
In file included from /Users/icenct/projects/moose/scripts/../libmesh/contrib/timpi/src/parallel/include/timpi/communicator.h:38:
In file included from /opt/moose/llvm-9.0.0/bin/../include/c++/v1/complex:245:
/opt/moose/llvm-9.0.0/bin/../include/c++/v1/cmath:313:9: error: no member named 'signbit' in the global namespace
using ::signbit;
      ~~^
/opt/moose/llvm-9.0.0/bin/../include/c++/v1/cmath:314:9: error: no member named 'fpclassify' in the global namespace
using ::fpclassify;
      ~~^
/opt/moose/llvm-9.0.0/bin/../include/c++/v1/cmath:315:9: error: no member named 'isfinite' in the global namespace; did you mean 'finite'?
using ::isfinite;
      ~~^
/usr/include/math.h:749:12: note: 'finite' declared here
extern int finite(double)
           ^
In file included from /Users/icenct/projects/moose/scripts/../libmesh/contrib/timpi/src/parallel/src/message_tag.C:22:
In file included from /Users/icenct/projects/moose/scripts/../libmesh/contrib/timpi/src/parallel/include/timpi/communicator.h:38:
In file included from /opt/moose/llvm-9.0.0/bin/../include/c++/v1/complex:245:
/opt/moose/llvm-9.0.0/bin/../include/c++/v1/cmath:316:9: error: no member named 'isinf' in the global namespace
using ::isinf;
      ~~^
/opt/moose/llvm-9.0.0/bin/../include/c++/v1/cmath:317:9: error: no member named 'isnan' in the global namespace
using ::isnan;
      ~~^
/opt/moose/llvm-9.0.0/bin/../include/c++/v1/cmath:318:9: error: no member named 'isnormal' in the global namespace
using ::isnormal;
      ~~^
/opt/moose/llvm-9.0.0/bin/../include/c++/v1/cmath:319:7: error: no member named 'isgreater' in the global namespace; did you mean '::std::greater'?
using ::isgreater;
      ^~
/opt/moose/llvm-9.0.0/bin/../include/c++/v1/functional:731:57: note: '::std::greater' declared here
struct __attribute__ ((__type_visibility__("default"))) greater : binary_function<_Tp, _Tp, bool>
                                                        ^
```

It stems from issues with Xcode headers. @milljm knows more about the shifts that happened with Xcode 11... but the gist is that there's a weird install/upgrade order that leads to something along the lines of this. We fixed this issue by explicitly removing Xcode 11: Storage Management -> Applications -> Remove Xcode, removing the command line tools: `sudo rm -rf /Library//Library/Developer/CommandLineTools` (yes, this removal method is officially approved by Apple!, and re-installing the command line tools: `xcode-select --install`.

I can also replicate the test failure. Debugging now.

**Comment by roystgnr** [comment]
Okay, so that sort of compile error is *definitely* not our fault.  If there's something we can do (include a not-supposed-to-be-necessary header before the header we actually need?) to work around the problem that would be great, but documenting "here's how you fix Apple's mistakes" sounds adequate to me.

> I can also replicate the test failure. Debugging now.

Thank you!  It'd be quite a hassle for me to get my hands on a Mac at the moment.  I think I'm most confused by the intermittency - how did it pass (at least up until that one MOOSE test) the first time?

**Comment by permcody** [comment]
On Thu, Nov 14, 2019 at 3:15 PM roystgnr <notifications@github.com> wrote:

> Okay, so that sort of compile error is *definitely* not our fault. If
> there's something we can do (include a not-supposed-to-be-necessary header
> before the header we actually need?) to work around the problem that would
> be great, but documenting "here's how you fix Apple's mistakes" sounds
> adequate to me.
>
> I can also replicate the test failure. Debugging now.
>
> Thank you! It'd be quite a hassle for me to get my hands on a Mac at the
> moment. I think I'm most confused by the intermittency - how did it pass
> (at least up until that one MOOSE test) the first time?—
>

This is the most bizarre part of this. Our last hash of libMesh is fine on
the same box as are all the derived MOOSE-based applications. We only
encountered this error when we pulled the latest version of libMesh for
testing today (3 of us have replicated the error). I'm curious, but also
not very motivated to try to pull the thread since ultimately it's not your
fault. Still, very bizarre.

**Comment by loganharbour** [comment]
DIsregard, I actually can't replicate that problem in Check (the segfault). I can replicate the MOOSE test failure. Looking into that as well...

I've compiled in opt on OS X 10.14 locally, and passed Check. The first time it passed Check on the test boxes, it was running on a machine with OS X 10.15. The most recent failure was on 10.12 (which we shouldn't even be supporting anymore...). We're trying again on the best boxes on OS X 10.15 to make sure its not reproducible there.

**Comment by loganharbour** [comment]
Alright @roystgnr, we're good. Summary:

- Original failure in Check was on OS X 10.12 and we're not going to worry about it as there are no issues on 10.14 and 10.15.
- MOOSE failure is unrelated.
- The tests that @friedmud has in his code that use `push_parallel_packed_range` pass in addition to my own.

**Pull request merged**
