### PR TITLE
Fix value return in JIT function

### LINKED ISSUE #2595: Fix JIT compile error
As noted in
https://hpcgitlab.hpc.inl.gov/idaholab/bison/-/merge_requests/2048#note_277895
the use of the `if` conditional in parsed ADReal functions will lead to a JIT compile error. The generated code contains a return statement with the wrong type (ADReal instead of void). I must have missed that when converting the JIT functions from returning values to taking a writable reference for the computed value. This was necessary to permit returning non-intrinsic types.

### PR DESCRIPTION
**Pull request by dschwen**
Closes #2595

### CODE REVIEW

**Comment by jwpeterson** [comment]
More JITTY code

**Comment by dschwen** [comment]
Are you JITTING you pants over it?

**Comment by jwpeterson** [comment]
I've run out of JITs to give.

**Comment by dschwen** [comment]
If this doesn't fix it I'm getting JITFACED!

**Comment by dschwen** [comment]
A ... baJITlion... ?

...

... I'll see myself out.

**Comment by jwpeterson** [comment]
> How many libmesh updates can we do in a month?

A JITload

**Pull request merged**
