### PR TITLE
Added OrderWrapper shim class to enable higher FEType order

### PR DESCRIPTION
**Pull request by dknez**
As per the discussion with @roystgnr and @jwpeterson on the libmesh-devel list.

### CODE REVIEW

**Comment by dknez** [comment]
hmm, this builds for me. Might be because I'm using a C++11-compatible compiler.

**Comment by dknez** [comment]
Oh, the reason it compiled for me before is that I configure with infinite elements on, and I forgot to modify the infinite elements code path...

**Comment by roystgnr** [comment]
Get rid of the first default argument in the old FEType constructor

**Comment by dknez** [comment]
Yep, doing that now.

**Comment by dknez** [comment]
hmm, any suggestions on what to do about errors like this:
`ambiguous overload for ‘operator==’ (operand types are ‘libMesh::OrderWrapper’ and ‘libMesh::Order’`

I tried adding an operator== for OrderWrapper and Order, but that gave ambiguous overloads related to Order and int.

**Comment by dknez** [comment]
This doesn't seem to be as straightforward as I'd hoped. We can just drop this PR if you like. Let me know what you think?

**Comment by roystgnr** [comment]
Go ahead and leave it; I won't have time to play with it for a while but I think we're almost there.

**Comment by roystgnr** [comment]
Superceded by #866

**Pull request closed without merging**
