### PR TITLE
System::projection_matrix implementation

### PR DESCRIPTION
**Pull request by roystgnr**
This is part of the geometric multigrid support that @pbauman and @bboutkov are working on.

Reasons why this isn't quite ready for prime-time:
1. projection_matrix() currently does *not* include a sweep over constraint equations.  The testing @bboutkov has done suggests that this makes it currently unsuitable for problems with periodic BCs, and I would presume the same is true for meshes with hanging nodes.
2. There's a mess of PETSc setup that's necessary to plug this into a GMG solve, and there's some god-awful 160-commit-fork of GRINS where that's being tested, so it may not be ready in libMesh as soon as I'd hoped.
3. No unit test yet.  @bboutkov promised me he'll have one Real Soon Now.

Reasons why I want to merge this immediately anyway:
1. Half this work dates back to March, rebasing on libmesh/master from a thousand commits later in November was a nightmare of conflicts to sort out, and I don't want to do that again.
2. I have optimization work pending on GenericProjector, and if I try to do that in one branch while keeping the projection matrix use case in a different branch then the merge conflicts will become even worse.

### CODE REVIEW

**Comment by fdkong** [comment]
@roystgnr, Do you know which branch is actually main work of GMG? I am just curious to take a look.

**Comment by roystgnr** [comment]
@fdkong, I believe the testing is going on in GRINS in https://github.com/bboutkov/grins/tree/mg_parallel - I'll let you know when they start getting things cleaned up and ported upstream to libMesh.

**Comment by fdkong** [comment]
Thanks @roystgnr.

**Comment by roystgnr** [comment]
@jwpeterson, @pbauman, help?  I'm utterly baffled by the build failure.  I don't believe I'm doing anything different between contrib/metaphysicl/0.2.0 and any of our other nested autotools projects, and on my machines the sub-make in metaphysicl/0.2.0 doesn't provoke any sort of re-bootstrap, but for some reason Civet thinks that subdir is unbuildable without aclocal-1.15!

Is it possible that, when Civet does the git checkout, it happens to create that particular aclocal.m4 or configure too early, and then it sees a later timestamp for configure.ac or an m4/ macro, and that causes make to falsely believe that aclocal needs to be re-run?  Now that I think about it, I'm not sure why that exact failure doesn't happen on at least 50% of our subprojects just by dumb luck...

**Comment by roystgnr** [comment]
Perhaps what I did differently with MetaPhysicL was committing both autotools-input and autotools-output files in the same commit?  If every other subproject did that in two steps and if git was hitting the filesystem commit-by-commit when making a checkout, then it would write the former files before the latter and the dependencies would look fine to make...  That seems like two huge "if"s, though.

**Comment by roystgnr** [comment]
So, that wasn't the fix.  What's weird too is that, when the GRINS test client is just finishing up (after a successful build because aclocal exists on that machine), it screams because a couple Makefile.in files were actually *changed* by the aclocal run.  I swear I'm using our own aclocal out of contrib/autotools/ so I'm not sure what @pbauman's machine might be doing differently.

**Comment by jwpeterson** [comment]
When I have seen this error:
```
WARNING: 'aclocal-1.15' is missing on your system.
         You should only need it if you modified 'acinclude.m4' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'aclocal' program is part of the GNU Automake package:
         <http://www.gnu.org/software/automake>
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         <http://www.gnu.org/software/autoconf>
         <http://www.gnu.org/software/m4/>
         <http://www.perl.org/>
```
it was always associated with `--enable-maintainer-mode`. Do you have `AM_MAINTAINER_MODE
[enable]` in metaphysicl's configure.ac file? From what I understand, this requires a user to then run `./bootstrap` which MOOSE does not require and CIVET is not set up to do.

**Comment by pbauman** [comment]
Trying on my local machine, it looks like aclocal is getting triggered during make for MetaPhysicL. I have the libMesh autotools loaded in my environment and there are white space changes that hit the Makefile.in's in the source tree, which is why GRINS fails (it's trying to git checkout master and git errors saying there's stuff that will be removed. Note also there's a netcdf file that's getting changed to, which should be orthogonal to this). Need to drill down to see why aclocal is getting triggered.

As an aside, MetaPhysicL is header-only, correct? If so, perhaps we strip out the build system entirely in the MetaPhysicL part and just update libMesh build system to put the headers in the right place during install, etc.? That would remove a lot of the potential for this kind of stuff. Just a thought.

**Comment by pbauman** [comment]
Oops, I was wrong about white space changes. `--gnu` is becoming `--foreign` below

<pre>
[11:29:46][pbauman@fry:/fry1/data/users/pbauman/research/libmesh/pbauman][(65594e7...)] $ git diff contrib/metaphysicl
diff --git a/contrib/metaphysicl/0.2.0/src/Makefile.in b/contrib/metaphysicl/0.2.0/src/Makefile.in
index f863ca0..88f203a 100644
--- a/contrib/metaphysicl/0.2.0/src/Makefile.in
+++ b/contrib/metaphysicl/0.2.0/src/Makefile.in
@@ -545,9 +545,9 @@ $(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
              exit 1;; \
          esac; \
        done; \
-   echo ' cd $(top_srcdir) && $(AUTOMAKE) --gnu src/Makefile'; \
+ echo ' cd $(top_srcdir) && $(AUTOMAKE) --foreign src/Makefile'; \
        $(am__cd) $(top_srcdir) && \
-     $(AUTOMAKE) --gnu src/Makefile
+   $(AUTOMAKE) --foreign src/Makefile
 Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
        @case '$?' in \
          *config.status*) \
diff --git a/contrib/metaphysicl/0.2.0/test/Makefile.in b/contrib/metaphysicl/0.2.0/test/Makefile.in
index 1830742..ce62e00 100644
--- a/contrib/metaphysicl/0.2.0/test/Makefile.in
+++ b/contrib/metaphysicl/0.2.0/test/Makefile.in
@@ -896,9 +896,9 @@ $(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
              exit 1;; \
          esac; \
        done; \
-   echo ' cd $(top_srcdir) && $(AUTOMAKE) --gnu test/Makefile'; \
+ echo ' cd $(top_srcdir) && $(AUTOMAKE) --foreign test/Makefile'; \
        $(am__cd) $(top_srcdir) && \
-     $(AUTOMAKE) --gnu test/Makefile
+   $(AUTOMAKE) --foreign test/Makefile
 Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
        @case '$?' in \
          *config.status*) \
</pre>

**Comment by pbauman** [comment]
https://github.com/libMesh/libmesh/pull/1506/commits/fd5e18320de82bc1f1ba864e74d6380eeae83694#diff-0d67ff161f815077a53f1ace4c18af53R4

That line is causing the diff. 

Link discussing the strictness of packaging: https://www.gnu.org/software/automake/manual/automake.html#Strictness

We're using `gnu` in libMesh. The `foreign` that's there is probably a holdover from PECOS days.

**Comment by pbauman** [comment]
I'll also note that it looks like @jwpeterson was also correct that the MetaPhysicL build system is not using `AM_MAINTAINER_MODE`. I haven't tested whether or not that will change the outcome here yet.

However, dropping the line mentioned above actually causes `bootstrap` to error:

<pre>
Makefile.am: installing './INSTALL'
Makefile.am: error: required file './NEWS' not found
Makefile.am: error: required file './README' not found
Makefile.am: error: required file './ChangeLog' not found
src/Makefile.am: installing 'build-aux/depcomp'
autoreconf: automake failed with exit status: 1
</pre>

That is, with `gnu` packaging strictness, it errors when you dont' have these files, whereas `foreign` doesn't.

**Comment by pbauman** [comment]
> As an aside, MetaPhysicL is header-only, correct? If so, perhaps we strip out the build system entirely in the MetaPhysicL part and just update libMesh build system to put the headers in the right place during install, etc.? That would remove a lot of the potential for this kind of stuff. Just a thought.

Just to add to this thought: all the configure checks in MetaPhysicL are essentially to allow it to be used with VexCL, right? Everything in there is other C++, no dependencies?

**Comment by pbauman** [comment]
Looks like adding `AM_MAINTAINER_MODE` in MetaPhysicL configure.ac will do the trick. The rerun of aclocal was skipped during `make` once I added it. That would also fix the error on the INL systems, I believe.

<pre>
diff --git a/contrib/metaphysicl/0.2.0/configure.ac b/contrib/metaphysicl/0.2.0/configure.ac
index 531c2fb..29c1492 100644
--- a/contrib/metaphysicl/0.2.0/configure.ac
+++ b/contrib/metaphysicl/0.2.0/configure.ac
@@ -14,6 +14,8 @@ AC_CANONICAL_TARGET()
 AM_INIT_AUTOMAKE([dist-bzip2 tar-ustar 1.11 no-define color-tests parallel-tests subdir-objects])
 AM_SILENT_RULES(yes)  # use silent rules where available - automake 1.11
 
+AM_MAINTAINER_MODE
+
 LT_INIT
</pre>

**Comment by roystgnr** [comment]
Well, at least it's a real problem this time, and one that I can understand and replicate!

It only just occurs to me that, although MetaPhysicL is supposed to be very datatype independent, the first and last time it was ever tested with std::complex was that last Civet run...

**Comment by roystgnr** [comment]
Okay, this should be ready to merge once that last test is done.

@bboutkov finished up some unit tests, and those can go in a separate PR after I've played with them a bit myself.

**Pull request merged**
