### PR TITLE
Assert valid boundary IDs

### PR DESCRIPTION
**Pull request by roystgnr**
This should be a more reliable way to catch some of the inconsistency bugs that I fixed in the examples in #943

### CODE REVIEW

**Comment by roystgnr** [comment]
IMHO we don't need to bother backporting this; it's not a fix in our code but rather a new feature to help users fix their codes.

**Comment by jwpeterson** [comment]
Looks like it may have uncovered a bug in MOOSE?
```
materials/stateful_prop.test_older_mpi_threads:
Assertion `mesh.comm().semiverify (elem ? &bcids : nullptr)' failed.
[0] ../src/mesh/mesh_tools.C, line 1314, compiled May 23 2016 at 15:12:46
```
Let me know if there's a more or less "obvious" fix, otherwise we can dig down into it further...

**Comment by roystgnr** [comment]
I can replicate this, at least.

**Comment by friedmud** [comment]
I suspect that the fact that it's a "stateful_prop" test has nothing to do
with it... I bet a bunch of tests would have failed if it would have made
it to the `parallel` set of tests...

**Pull request merged**
