### PR TITLE
Optimize FEMap

### PR DESCRIPTION
**Pull request by roystgnr**
My first crack at addressing some of the issues discussed in https://github.com/libMesh/libmesh/issues/890

On my system it cuts the init_reference_to_physical_map() runtime in half for point evaluations.  Nice, but that's for the most extreme case; I was hoping for more.

This needs serious testing.

### CODE REVIEW

**Comment by friedmud** [comment]
Holy crap!  Thanks so much Roy!  I'm going to try it out RIGHT NOW!

**Comment by permcody** [comment]
Nice - I'll try to pull this branch as well and see if I can benchmark it against some of our heavier tests once the tests pass. Thanks!

**Comment by friedmud** [comment]
@permcody I don't expect it to help MOOSE much... yet

We currently request _most_ things from the FE object... so most stuff will get recomputed even with this patch.  We may need to break up our FE objects... have some for "special occasions"... especially one that ONLY computes shape functions for point value evaluation (when we need nothing else).  There are many cases in MOOSE when that is true.

That said - this may still help _some_

**Comment by friedmud** [comment]
I'm seeing some good speedup with this in the test application:

```
> ./simple-opt --n-elem 500 --n-sweeps 50 --fe-reinit-qrule --fe-reinit-custom

Reinit with qrule...
Total Time: 2.50062
ns/element: 200.049
Levelized ns/element: 200.049

Reinit with custom point...
Total Time: 5.14279
ns/element: 411.423
Levelized ns/element: 411.423
```

Nearly 2x... which is awesome!  Definitely a good first step!

I'll see if I can get MOOSE going with it...

**Comment by roystgnr** [comment]
FINALLY!

**Comment by roystgnr** [comment]
So this definitely introduces the possibility of userspace breakage:

1.  Before, the physical point locations were calculated even if you didn't prerequest get_xyz().  After, if you try to use get_xyz() after reinit() you'll get an assertion failure in debug/devel modes or an OOB or segfault in opt/prof modes.

2.  Before, if you prerequested only get_xyz(), it would basically count as no prerequest at all, which would put us on the backwards compatibility "just compute everything" code path, which would let you then use everything later.  After, if you prerequest only get_xyz() from an FE, requesting anything else after reinit will be another assert/OOB failure.

3.  For side and edge reinit, we need to do FEMap prerequests from within the library itself, which probably breaks anyone who was trying to use our "just compute everything" code path with those.

I'll add a unit test to verify my suspicions on (3), then fix if necessary.  I'll also add a libmesh_deprecated() warning to that code path; anybody still not using prerequests at this point should be informed that their code should be better.  For (1) and (2) I don't think there's a fix which won't hurt efficiency, and technically affected user code is wrong, so I'll leave it to users to fix.

But anyway, even before I fix (3), this should now be in shape for people to play with and test with.

**Comment by friedmud** [comment]
Awesome @roystgnr !  I'm crazy busy today - but I'll try this out tonight for sure!

Thanks!

**Comment by jwpeterson** [comment]
Interesting that we had this inconsistency with `get_xyz()` vs. the other getters all along, I never knew that.

**Comment by jwpeterson** [comment]
For whenever you get around to cleaning up the branch before merge:

```
$ git diff --check a59cce1..775439d
src/fe/fe_map.C:196: tab in indent.
+                     (mapping_elem_type, mapping_order, i, qp[0]);
```

**Comment by friedmud** [comment]
Wait - what happened here?  This is what I see from the simple timing application now:

```
./simple-opt --n-elem 500 --n-sweeps 50 --fe-reinit-qrule --fe-reinit-custom

Reinit with qrule...
Total Time: 26.0809
ns/element: 2086.47
Levelized ns/element: 2086.47

Reinit with custom point...
Total Time: 30.9024
ns/element: 2472.19
Levelized ns/element: 2472.19
```

It got 10x slower!

**Comment by friedmud** [comment]
This is what I see in a profiling run now:

slow

**Comment by friedmud** [comment]
After a bit of manual bisecting (should have used _actual_ bisecting but I was lazy :-) it appears as if fa46135 is the culprit.  10x slowdown from that commit on.

I haven't looked into why yet...

**Comment by friedmud** [comment]
I've double checked it - it REALLY is that commit - but I can't see why...

**Comment by friedmud** [comment]
Yep: If I take this branch exactly as it is... and all I do is revert fa46135 it fixes it!  The only thing I can see in that commit is that it added some extra `this->_fe_trans->init_map_phi(*this);` to `determin_calculations()`.

I'm not sure if that's what's causing the slowdown... but it does feel like a bit of a design problem anyway.  `determine_calculations()` shouldn't really be "initializing" data-structures like that... (that's just IMO...)

**Comment by roystgnr** [comment]
Take a look at what init_map_phi() actually does - it initializes necessary prerequests, it doesn't initialize any data structures.

**Comment by roystgnr** [comment]
What's strange is that point queries should have *sped up* after that commit - before, get_xyz() got called even if you didn't need it; after, it didn't.

**Comment by roystgnr** [comment]
Thanks for catching this; there's definitely a regression hiding there.  I'm on it.

**Comment by roystgnr** [comment]
Oh, hell, I think I get it!  Now that we no longer calculate xyz without a prerequest, calculating phi alone asks *nothing* from the map object.  And what do we get when we prerequest nothing?  We fall back on the "backwards compatibility" code path and calculate *everything*.

That should be easy to fix.  We don't actually need a backwards compatibility code path in FEMap since nobody uses that directly, so when the map is asked for nothing it should actually just compute nothing.

**Comment by friedmud** [comment]
Hmmm... it's better, but still slower than it was...

```
./simple-opt --n-elem 500 --n-sweeps 50 --fe-reinit-qrule --fe-reinit-custom

Reinit with qrule...
Total Time: 3.65856
ns/element: 292.685
Levelized ns/element: 292.685

Reinit with custom point...
Total Time: 8.37675
ns/element: 670.14
Levelized ns/element: 670.14
```

**Comment by roystgnr** [comment]
I'm actually seeing ~5% faster (than the original optimization, not just than before the regression).  But that's clearly trumped by ~50% slower.  I'll keep looking into it.

**Comment by roystgnr** [comment]
Hmm...  there may be some compiler issues getting in my way, too?  I'm testing on an E5-2620, a chip that should be 50% as fast as the top of the line per-core, but I'm getting 25% of your speed.  Should I be rebuilding with icpc, -O3, or anything else fancy?

**Comment by friedmud** [comment]
Can you post your numbers?  I'm having a hard time parsing what you're
seeing :-)

**Comment by roystgnr** [comment]
```
$ ./simple-opt --n-elem 500 --n-sweeps 50 --fe-reinit-qrule --fe-reinit-custom 2>&1 | tee derek-after3.txt  
Reinit with qrule...  
Total Time: 15.2313  
ns/element: 1218.5  
Levelized ns/element: 1218.5  
  
Reinit with custom point...  
Total Time: 33.1688  
ns/element: 2653.51  
Levelized ns/element: 2653.51  
```

**Comment by roystgnr** [comment]
Hell, even our newest machine (E5-2670v3) is giving me less than half the single-core speed of yours.

**Comment by friedmud** [comment]
Interesting - this is just on my laptop.  I'm not doing anything interesting.  My compiler is `clang 3.7.0`...

**Comment by roystgnr** [comment]
I can try clang.  What's your CPU?

**Comment by friedmud** [comment]
According to what I can find it's: `22 nm "Haswell/Crystalwell" 2.6 GHz Intel "Core i7" processor (4960HQ)`

All of these numbers are for my 2013 Macbook Pro.

**Comment by pbauman** [comment]
Yeah, I haven't been able to find memory bandwidth numbers, etc. for the Macbook's. My experience (on my late 2013/early 2014 model) is that it is a fair bit slower per core than my Ivy Bridge workstation (E5-2650v2), based on just coarse timings of benchmark problems in GRINS where the software stack is identical between the two machines (starting at the compiler level). So, I'd expect @roystgnr to be able to match your performance. But performance portability is a PITA.

**Comment by friedmud** [comment]
We're talking a 4-6x change in performance here though.  Something is definitely up with that!

**Comment by friedmud** [comment]
Oh - I _do_ have C++11 turned on too... but other than that it's a pretty typical libMesh build.

**Comment by pbauman** [comment]
@friedmud are you using libstdc++ or libc++ (libcxx... whatever LLVM's std library replacement is)? I've never clocked the timing difference, but I wonder if that could be part of this?

**Comment by friedmud** [comment]
I have no idea.  Maybe @milljm can answer that.

You can actually perfectly replicate my environment: http://mooseframework.org/getting-started/

Just download the OS X package and install it.  It all installs in /opt/moose and won't mess with your machine in any way.  There is just one line you put in your bash_profile to pull in the MOOSE environment... leaving it out gets you back to your normal environment.

**Comment by milljm** [comment]
@pbauman Well I do not know much about it myself... Just enough to answer your question (I think).

-stdlib=libc++

I grabbed that info from an old set of instructions on how to build openMP (when LLVM-Clang did not support it) Here is the example so as to proved a bit more than just taking my word for it :)

```bash
cmake -DCMAKE_CXX_COMPILER=$PACKAGES_DIR/clang_3.5.1/bin/clang++ \
-DCMAKE_C_COMPILER=$PACKAGES_DIR/clang_3.5.1/bin/clang \
-DLLVM_ENABLE_LIBCXX=on \
-DCMAKE_BUILD_TYPE=Release \
-DCMAKE_INSTALL_PREFIX=$PACKAGES_DIR/clang_3.5.1  \
-DLLVM_CONFIG=$PACKAGES_DIR/clang_3.5.1/bin/llvm-config \
-Wno-dev -DCMAKE_CXX_FLAGS=-stdlib=libc++ \
-DCMAKE_C_FLAGS=-stdlib=libc++ \
-DCMAKE_EXE_LINKER_FLAGS=-stdlib=libc++ ..
````

**Comment by roystgnr** [comment]
It's definitely not clang - I get slower results there than with gcc.

So I can't replicate the regression any further.  I'm also not sure I could repair it if I did.  The switch from direct _fe_map manipulation to _fe_trans calls was necessary to fix Nedelec elements.  IIRC the refactoring in compute_shape_functions was necessary to fix a regression triggered by MOOSE.

**Comment by roystgnr** [comment]
Going to merge this soon unless there's objections.  It works fine with MOOSE and GRINS.

**Comment by roystgnr** [comment]
Wait, almost forgot John's request for cleanup.  I'll do that first.

**Comment by dknez** [comment]
Can you confirm the implications for applications? I haven't been following this thread closely, but I gather that applications that did not pre-request data properly will now hit an assertion failure in dbg mode, or segfault in opt mode? Might be worth sending an email to libmesh-users about that, after you merge.

**Comment by roystgnr** [comment]
That's close to correct, and will-do.  Technically, "if you prerequest improperly you'll get an assert or a segfault" has been libMesh behavior for years, but the definition of "improperly" gets stricter here.

**Comment by roystgnr** [comment]
That still leaves us with two commits in the history which I'd expect to fail.  I think I can get it down to 0, but after so much rebasing I figured I might as well push and make sure I haven't screwed anything up with the final product in the process.

**Comment by roystgnr** [comment]
In theory that should leave every commit passing CI, as well as eliminate the "we need this method in this class, no its abstract base class, no just its superclass" reversions.  In practice I'm not going to test any of the intermediate commits, and I'll merge if/when this last commit passes.

**Comment by jwpeterson** [comment]
:+1:

**Comment by friedmud** [comment]
@roystgnr sorry I was incommunicado.  I was traveling... and the place I was at doesn't allow cell-phones or laptops :-)

Thanks for putting this in!

I'm still puzzled as to why my laptop is SO much faster than what you guys are seeing.  I'll try to do some digging on that soon by running on a few different machines.

I've ended up coming up with a workaround where I don't use the libMesh FE infrastructure for my current problem anymore.  That said: I really DO want to in the future for this problem so I do want to get this fixed.  It's just not quite as urgent any more.

In addition, after all of the digging I've done on this problem I really think there can be some pretty huge gains in performance by removing a lot of the temporaries from the FE computations.

I'll come back around to that... but right now I'm focused on this talk which is about 2.5 weeks away (and still no results!)

Thanks again for taking the time to work on this right now.  I think these changes are really valuable and will speed up a lot of libMesh based applications!

**Pull request merged**
