### PR TITLE
Short circuit pthread/openmp execution for serial runs

### PR DESCRIPTION
**Pull request by friedmud**
Why are you always preparing - just go!

### CODE REVIEW

**Comment by roystgnr** [comment]
Could we keep the BoolAcquire(in_threads) for this code path, at least in dbg/devel modes?  I like it when I get caught trying to run non-within-thread-safe code within a threaded section, even when (as is typical) I'm not currently using threads.

Otherwise :+1: once we figure out what the heck is going wrong (failure from the naming update that didn't get caught there somehow??) with all those MOOSE CheckpointIO failures.

**Comment by friedmud** [comment]
Does that `BoolAcquire` take any time?

I circumvented it because this was an optimization anyway - so I was trying to do the most optimal thing.

Yeah - the CheckpointIO stuff is because it's an incompatible change with MOOSE.  MOOSE has to be patched for it... but that can't happen until the libMesh submodule is updated in MOOSE.  We hope to do all of that today.

**Comment by roystgnr** [comment]
The constructor sets a bool to true and stores its address, the destructor sets the bool to false.  Pretty trivial, but it definitely doesn't get completely optimized away, and that's a global bool so it might even be a cache miss if you're hitting threaded sections infrequently.  Even O(100ns) per parallel_for call wouldn't sound too bad to me, *except* that if you're already finding yourself optimizing this then I guess it shows up in profiling somewhere.

We currently only use Threads::in_threads within libMesh and MOOSE in internal assertions... and it doesn't look like FIN-S or GRINS use it at all... I'd be willing to bet that we could make that variable's very existence conditional on ```#ifndef NDEBUG``` without really inconveniencing anybody, if you want.

**Comment by friedmud** [comment]
That sounds light enough to me: I'll change it

**Comment by friedmud** [comment]
I think this is ready...

**Pull request merged**
