### PR TITLE
-Winconsistent-missing-override was added in clang 3.6

### PR DESCRIPTION
**Pull request by brianmoose**
This replaces #1601 which can probably be closed.

### CODE REVIEW

**Comment by brianmoose** [comment]
I added the "Minimum clang version" recipe (which uses clang 3.5.1) which had a ton of warnings due to this...

**Comment by brianmoose** [comment]
Oh, nevermind, it doesn't test moose :(

**Comment by brianmoose** [comment]
Well the warnings didn't show up when building libmesh, which they [normally did](https://www.moosebuild.org/job/161450/)

**Comment by jwpeterson** [comment]
> Well the warnings didn't show up when building libmesh, which they normally did

You mean the warnings about not having a warning? Sounds like it's working to me :-)

**Pull request merged**
