### PR TITLE
We should copy over node boundary data when we do BoundaryInfo::sync

### PR DESCRIPTION
**Pull request by dknez**

### CODE REVIEW

**Comment by jwpeterson** [comment]
Seems reasonable.  Please squash these two commits together though.

**Comment by dknez** [comment]
I squashed them.

**Comment by roystgnr** [comment]
If we add this behavior we should document it in the comments.

Should we also hunt for edge boundary data to copy over?  Should edge data in 3D turn into side data in the 2D boundary?

**Comment by dknez** [comment]
I'll add extra comments.

Your questions are certainly valid... I'm not sure what the best answer is, what do you think?

I needed the nodeset data on a BoundaryMesh for an application code I'm working on, which is what motivated this change.  Personally I don't need edge data on the BoundaryMesh right now, so I'd be happy to proceed with the current PR and add the edge data later if/when someone needs it.

**Comment by roystgnr** [comment]
My whim would be "yes" and "yes", but if you want to leave that unimplemented (and documented as such) until someone needs it, that's fine.

**Comment by dknez** [comment]
Comments added. But I think I will leave the edges unimplemented for now. I indicated this in the updated comments.

**Comment by dknez** [comment]
Did this really fail??

**Comment by permcody** [comment]
I highly doubt that's you. I'll look at it in the morning.

**Comment by permcody** [comment]
Yeah, we occasionally see one or two of our threaded tests fail that way (Error 139) and we've never been able to repeat during debugging... I invalidated that target, it should pass just fine.

**Pull request merged**
