### PR TITLE
Fixed valgrind issue with VecSetDM

### PR DESCRIPTION
**Pull request by fdkong**
We should not compose object twice

### CODE REVIEW

**Comment by jwpeterson** [comment]
@fdkong You'll have to rebase this on my revert, it has conflicts.

**Comment by fdkong** [comment]
Do not merge it. We need a way to test against both PETSc-3.12 and PETSc-3.13.

I believe this is caused by increasing reference count twice. Then DMDestroy won't delete anything.

**Comment by fdkong** [comment]
@jwpeterson Could you give me some permission? So I can label PR as "do not merge"

**Comment by lindsayad** [comment]
This appears to fix the MOOSE test valgrind failures with PETSc 3.12.5

**Comment by jwpeterson** [comment]
@fdkong that's too much power, I added a label for you :-)

**Comment by fdkong** [comment]
@jwpeterson Do not worry about me, I am fine

**Comment by fdkong** [comment]
OK. I am going to check if it is Valgrind clean using this change against both` PETSc-3.13 and PETSc-3.12`

https://github.com/idaholab/moose/pull/15202

**Comment by lindsayad** [comment]
This also fixes the MOOSE contact module valgrind failure as well, which also used the standard differencing version of FDP. I guess those were the only tests that did. Additionally based on the vi ssls failures that must also use this DMSetUp business.

**Comment by fdkong** [comment]
One single line of code broke the whole world. It is NOT beautiful.

**Comment by fdkong** [comment]
We are testing the whole world here https://github.com/idaholab/moose/pull/15182

**Comment by fdkong** [comment]
It looks like good for me  according to https://civet.inl.gov/job/517103/
and https://civet.inl.gov/job/517145/

This will obviously work for PETSc-3.12 or older since we did not anything for ancient PETSc (`PETSC_RELEASE_LESS_THAN(3,13,0)`).

**Comment by jwpeterson** [comment]
@fdkong you are saying to merge this PR now, is that correct?

**Comment by fdkong** [comment]
> @fdkong you are saying to merge this PR now, is that correct?

Yes, Thanks @jwpeterson.

**Pull request merged**
