### PR TITLE
Avoid dangling reference in SparsityPattern::Build

### LINKED ISSUE #2199: Warning: binding reference member to stack allocated parameter
In the constructor 
```
Build::Build (const MeshBase & mesh_in,
              const DofMap & dof_map_in,
              const CouplingMatrix * dof_coupling_in,
              std::set<GhostingFunctor *> coupling_functors_in,
              const bool implicit_neighbor_dofs_in,
              const bool need_full_sparsity_pattern_in);
```
the set `coupling_functors_in` is passed in by copy, but is then bound to a reference:
```
const std::set<GhostingFunctor *> & coupling_functors;
```
That seems very wrong (as the reference points to the stack allocated (temporary) copy. Hence the warning:

```
../src/base/sparsity_pattern.C:48:21: warning: binding reference member 'coupling_functors' to stack allocated parameter 'coupling_functors_in' [-Wdangling-field]
  coupling_functors(coupling_functors_in),
                    ^~~~~~~~~~~~~~~~~~~~
./include/libmesh/sparsity_pattern.h:86:39: note: reference member declared here
  const std::set<GhostingFunctor *> & coupling_functors;
```

### PR DESCRIPTION
**Pull request by roystgnr**
This should fix #2199

### CODE REVIEW

**Comment by dschwen** [comment]
I'll go ahead and click merge on this...

**Comment by jwpeterson** [comment]
I forgot @dschwen could merge stuff... :open_mouth:

**Comment by dschwen** [comment]
Muhahaha

**Comment by jwpeterson** [comment]
I heard the laugh in my mind. Terrifying.

**Comment by permcody** [comment]
Even worse in person...

**Pull request merged**
