### PR TITLE
Partitioner unit tests

### LINKED ISSUE #1905: Partitioning a 0 element mesh throws an assert
Currently, if someone calls `prepare_for_use()` on an empty (zero element) mesh, the number of partitions gets set to 0 by this line:

https://github.com/libMesh/libmesh/blob/5e3620b01bc1ab478de8ae8c6786714095f2148a/src/partitioning/partitioner.C#L69-L71

Then we end up calling `_do_partition` with `n_parts==0`,

https://github.com/libMesh/libmesh/blob/5e3620b01bc1ab478de8ae8c6786714095f2148a/src/partitioning/partitioner.C#L86

and this eventually triggers an assert in `MetisPartitioner`:

https://github.com/libMesh/libmesh/blob/5e3620b01bc1ab478de8ae8c6786714095f2148a/src/partitioning/metis_partitioner.C#L61

It seems to me, however, that this doesn't need to be an error, but simply an early return. @leorachapuis ran into this while working on some mesh generation stuff...

### PR DESCRIPTION
**Pull request by roystgnr**
IIRC we have an open ticket for "METIS sucks", but I didn't realize how bad it was until I was futzing around to fix #1905.  What kind of partitioners can't figure out how to put 27 elements into even 14 nonempty groups?  Is there something wrong with our shims??

Anyway, this PR fixes a couple easier minor bugs, and adds unit tests for at least the level of capability that we *can* expect.

### CODE REVIEW

**Comment by roystgnr** [comment]
I *thought* this was going to be dead-simple, but it took me enough iterations that I don't think I want to merge until it gets another set of eyes, even if CI is finally happy.

**Comment by roystgnr** [comment]
> This might be OK, though as it looks like you are not diffing against "gold" files or asserting that a particular element ends up with a particular processor ID?

Oh, definitely not.  My *goal* with tests is to always have them pass regardless of processor count or partitioner choice or phase of the moon.

> I'm guessing you developed the new unit tests on Linux and then CIVET ran them on a Linux box... any chance you've tested them on a Mac? I might be able to give it a shot later today.

Yes, yes, and no, respectively.  That's a very good idea; it'd be embarrassing if METIS performed even worse on Mac and that tripped the tests and that didn't show up until after we'd merged.  Is the Test Mac  CI option enough?  If not then we'll want to wait for you to try it by hand.

**Comment by jwpeterson** [comment]
> Is the Test Mac CI option enough?

That will test with a pretty new clang compiler on Mac and should be sufficient, yeah. Thanks for remembering we had that optional recipe.

**Comment by roystgnr** [comment]
Hmm.. as my finger was clicking on the merge button, my brain was clicking on a possible problem: that Test Mac run surely only hits one processor count.  If you could do something like
```
for num in $(seq 1 24); do LIBMESH_RUN="mpiexec -n $num" make -C tests/ check || break; done
```
on Mac some time I'd feel much relieved to hear that it still passes.

**Comment by jwpeterson** [comment]
OK, I can try that out.

**Comment by jwpeterson** [comment]
That command worked for me so I'd say we're good.

**Pull request merged**
