### PR TITLE
Read/write numeric vector projection/type info

### PR DESCRIPTION
**Pull request by lindsayad**
I ran into an issue where I was reading at a ghost dof location with a
vector that should be ghosted, but when reading `System` information
from xdr before this PR we add vectors as default `ParallelType PARALLEL` if the
vectors are not already present in the `System` object; the result was a
failed read and a triggered assertion in debugging modes/a segmentation
fault in optimized modes. So here I add the writing of both vector
projection and type so that users are safe to use ghosted vectors
without considering whether their vector has been created at the time we
read xdr `System` information. I know I'll need to add versioning
information because of this change.

Refs idaholab/moose#17399

### CODE REVIEW

**Comment by lindsayad** [comment]
Silly MOOSE showing the need for versioning the IO :laughing:

**Comment by roystgnr** [comment]
Ha!  I was actually kind of surprised you put this up before adding versioning, but I didn't want to say anything because I really wanted to make sure our CI failed.  It's a pretty damning indictment of the libMesh "make check" that that phase passed.

**Comment by jwpeterson** [comment]
Sounds like `make check` is pretty "robust" :wink:

**Comment by lindsayad** [comment]
No matter what you throw at it, it passes! Yea sounds like a feature to me :smile:

**Review by roystgnr — APPROVED** [review]

**Review by jwpeterson — APPROVED** [review]
Looks good to me. I guess at some point we should stop using `sprintf` with a fixed `buf` size of 80 in this function :laughing:

**Pull request merged**
