### PR TITLE
adding example for SHELL8 + small fixes

### PR DESCRIPTION
**Pull request by svallaghe**

### CODE REVIEW

**Comment by pbauman** [comment]
The GRINS failure here is almost certainly unrelated to the PR. (One of the tests barfed on parsing the xda file generated by that case...) I'll try and reproduce locally this afternoon with master.

**Comment by roystgnr** [comment]
This certainly looks good to me, but I'd like to wait on the merge until Paul looks into the GRINS red herring and until the Civet build servers are up and running again, just to be safe.

**Comment by pbauman** [comment]
OK, I pulled libMesh master and GRINS (dbg,devel) both passed, `-np 4` parallel testing. Going to pull this branch now and see if I can recreate.

**Comment by pbauman** [comment]
OK, that single test passed, I'm running the same mode that `femputer` does now (takes about 45 mins or so to finish), but I'm going to invalidate that test now and see if it occurs again. I'm perplexed at the moment.

**Comment by pbauman** [comment]
OK, I have no explanation for what happened on `femputer` for the previous failure, but this is good to go from me.

**Pull request merged**
