### PR TITLE
Add Eigen-based optimization for DenseVector<T>::dot().

### PR DESCRIPTION
**Pull request by jwpeterson**
Also, improve and shorten the l1_norm(), l2_norm(), and linfty_norm()
Eigen-based optimizations done previously.  We are now not restricted
to using the Eigen optimizations for double: they should work with any
underlying type which Eigen itself supports.

C++ bonus meme: we get to employ the obscure forms of the 'typename'
and 'template' keywords in a single line of code.

Refs #1046.

### CODE REVIEW

**Comment by jwpeterson** [comment]
Haven't seen this particular one before.
```
---- Basis dimension: 0 ----
Performing RB solves on training set
/opt/moose/gcc-6.2.0/include/c++/6.2.0/debug/vector:422:
Error: attempt to subscript container with out-of-bounds index 0, but 
container only holds 0 elements.

Objects involved in the operation:
    sequence "this" @ 0x0x7fff9dfec238 {
      type = std::__debug::vector<double, std::allocator<double> >;
    }
```

**Comment by jwpeterson** [comment]
> Error makes no sense, this patch does not touch the RB code...

Actually it did make sense, needed to check for zero length vectors before accessing `&v[0]`.

**Comment by friedmud** [comment]
Did you do any timing studies on this?  I'm interested because my current application REALLY relies on `DenseVector::dot()`... like REALLY relies on it.

**Comment by jwpeterson** [comment]
Yes, it is 3-5x faster for large vectors (like, very large, 1M+ elements).  For smaller vectors I couldn't really tell any difference with PerfLog timings... you might have more luck with Instruments or some other profiler...

**Comment by friedmud** [comment]
Ok - well... I have really detailed timings on my code (everything is
measured in nanoseconds) so I'll let you know if anything changes.

Derek

**Pull request merged**
