### PR TITLE
Additional PETSc+METIS compatibility options

### PR DESCRIPTION
**Pull request by roystgnr**
These were written to let me build with the Ubuntu 19.10 system PETSc and METIS, but the PETSc configuration fixes might improve compatibility with other installs too, and the option to use a third-party METIS is just generally the right thing to offer users.

### CODE REVIEW

**Comment by roystgnr** [comment]
Yay CI.  This is clearly my bug, but I don't understand why it's only in the 64-bit environment that Parmetis configuration would now be failing.

**Comment by roystgnr** [comment]
Never mind, now the other PETSc METIS configs are failing too, and I think I see why.

**Comment by roystgnr** [comment]
Can anyone reproduce that fem_system_ex5 failure?  I cajoled @pbauman into trying on his Mac, but there it ran and completed fine.

**Comment by pbauman** [comment]
I didn't realize that was related to this PR. Note that I used `--with-metis=PETSc` in my build. Is there another configuration I should try? (My entire configure line was `--enable-everything --with-metis=PETSc`)

**Comment by roystgnr** [comment]
Oh, it (almost certainly) wasn't related to this PR.  This PR is just the first time I turned on the optional CI "MOOSE Mac Test" recipe since merging the new example.

Configuration there is
```
../configure --with-methods=opt --prefix=/opt/civet/build_0/libmesh/installed --enable-silent-rules --enable-unique-id --disable-warnings --enable-openmp --disable-maintainer-mode --with-metis=PETSc
```

But I don't see anything there that raises my eyebrows.

**Comment by roystgnr** [comment]
I think I've found the bug, which is indeed a heinous bug anywhere but which dumb luck didn't let us trigger anywhere except Mac.  If this works then I'll move the fix to a new PR.  If *that* works then I'll rebase this post-bugfix-merge, get rid of the debugging commits, and merge this once CI is happy again.

**Pull request merged**
