### PR TITLE
Revert "Use MPI_Pack/MPI_Unpack for vec-of-vec..."

### PR DESCRIPTION
**Pull request by roystgnr**
This reverts commit 2d9377d37c149cab814d626b78d697b024b6295b, with
conflicts manually fixed.

With some good luck, this patch will fix the breakage @dknez ran into in #1697.  I'm submitting this PR before doing any testing myself so that he can get on that ASAP, since I still can't reproduce the problems he encountered.

With the luck I've been having, this patch won't even compile, this PR will trigger a Github server bug and set their datacenter on fire, and this very joke will cause some reader to have a fatal brain aneurysm.

### CODE REVIEW

**Comment by dknez** [comment]
introduction_ex4 now works in parallel for me with this PR, great!

I will run our test suite on this. That will take a couple of hours, though.

**Comment by roystgnr** [comment]
@pbauman, is femputer down?  It's not showing up in the CI box here and I can't seem to connect to the webserver.

**Comment by pbauman** [comment]
Crap. The web page is not pulling up for me, but the machine is up and the server is running. Let me try rebooting.

**Comment by roystgnr** [comment]
I tried digging into git history for the send_receive_vec_of_vec method I broke, and it turns out that the tricky code I was trying and failing to refactor was written in 2bf2691 - by Ben, in 2008.  Any other MPI_Pack/MPI_Unpack experts in the crowd?

Unless I ever manage to figure out how to reproduce the error in #1697, I think I'll probably just leave this hackish alternative in place indefinitely.  Its disadvantages (it won't work on heterogenous architectures that nobody ever uses) are greatly outweighed by its advantages (it probably won't pass CI but then break horribly for other users).

**Comment by roystgnr** [comment]
> Unless I ever manage to figure out how to reproduce the error in #1697

It turns out to be as simple as "use OpenMPI".  I still think we should merge this PR as soon as GRINS-dbg and David's test suite are both happy, though; just because I can trigger the error doesn't mean I'll be able to fix it quickly.

**Comment by dknez** [comment]
This PR fixes the failures I was seeing before, so it's ready to merge as far as I'm concerned.

**Comment by roystgnr** [comment]
Actually, it looks like the real fix may be nearly trivial.  Would you mind testing that too in a minute?

**Comment by dknez** [comment]
Sure

**Comment by roystgnr** [comment]
I'm still running tests on it, but it looks like #1699 will be a much safer fix.

**Pull request closed without merging**
