### PR TITLE
Get exio helper

### PR DESCRIPTION
**Pull request by dknez**
In order to have full flexibility with ExodusII input/output, it can be useful to have access to the ExodusII_IO_helper object. This PR provides a "getter" for that object.

We also had to remove exodusII_io_helper.h from the noinst_blacklist so that it is accessible from app codes.

### CODE REVIEW

**Comment by dknez** [comment]
@jwpeterson, is this OK with you to merge?

**Comment by dknez** [comment]
I could add a comment to get_exio_helper in the header to explain that this gives access to a non-public API and may change in the future. Does that sound OK?

**Comment by jwpeterson** [comment]
I think the "likely to see future API changes" clause of the `libmesh_experimental` macro is applicable here.

**Comment by dknez** [comment]
So do you suggest a comment in the header, or a print statement, or calling a macro? I can update it with whatever you prefer.

**Comment by roystgnr** [comment]
If John thinks it's not overkill and if you don't mind the stdout clutter, then let's go with libmesh_experimental().  It was exactly the intent of that macro to warn people about APIs in flux; my only qualm is that I hadn't pictured it being used on APIs which we expect to be in that state for such a *long* time.

**Comment by jwpeterson** [comment]
`libmesh_experimental()` in the getter is fine, it's wrapped in `libmesh_do_once()` so you'll only see it once in the output.

**Comment by dknez** [comment]
OK, done now. Sorry for the extra commits, we can squash if you like?

**Comment by jwpeterson** [comment]
> squash if you like?

Just the last two commits, yeah. And we don't need to wait for testing.

**Pull request merged**
