### PR TITLE
Allow Nemesis Appending During MOOSE Recover

### PR DESCRIPTION
**Pull request by frombs**
Ref #2564

### CODE REVIEW

**Comment by jwpeterson** [comment]
@frombs I sent you an invite to join the group which gets their PRs tested automatically. I'll start these ones by hand now.

**Comment by roystgnr** [comment]
After this is in, can you get a test case covering the previously-broken behavior into MOOSE CI?  I fear this would be an easy regression to make otherwise.

**Comment by frombs** [comment]
@jwpeterson, thanks for adding me to the group.

**Comment by frombs** [comment]
> After this is in, can you get a test case covering the previously-broken behavior into MOOSE CI? I fear this would be an easy regression to make otherwise.

@roystgnr, this case should be covered by [idaholab#13415](https://github.com/idaholab/moose/pull/13415). I will contact @permcody and see how he wants to proceed.

**Pull request merged**
