### PR TITLE
WIP: Add support for Bezier elements in VTK output.

### LINKED ISSUE #3152: VTK support for IsoGeometric Analysis visualization
Pinging @aeslaughter to get the Coreform guys in here.

Right now, our best option for IGA visualization is "output to Exodus, and wince as our ExodusII_IO output inappropriately turns RATIONAL_BERNSTEIN control points into LAGRANGE mid-edge/face/cell points"  This works fine as long as our mesh is so fine that there's little difference between the two ... which means that the more advantageous an IGA solve is, the worse our IGA visualization is going to be.

Our best option for quickly fixing that is probably to output the proper element data via VTKIO, using the relatively recent extensions to VTK that support those element types.

Right now, src/mesh/vtk_io.C has an element map from libMesh element types to VTK element types, and that won't be enough - in libMesh the same e.g. HEX27 may be a Lagrange element if it has one mapping_type() or a Rational Bernstein element if it has another mapping_type().  At the very least we'll need to be testing Elem::mapping_type() before deciding which VTK element type to output.  Hopefully this will be the only major complication (in particular, I don't *see* anything in get_local_node_values or node_values_to_vtk that I'd expect to change), but I'm unfamiliar with the VTK rational basis support so I can't swear to it.

Our best bet for testing this out would be to just add VTK output to at least one of the IGA unit tests in tests/mesh/mesh_input.C - possibly testExodusFileMappingsPlateWithHole?  I'm not sure how best to get such a test in CI (as opposed to "just look at it manually in Paraview"), though, not without VTK input as well as output support.

### PR DESCRIPTION
**Pull request by brianmoose**
VTK 9 added support for VTK_BEZIER_* elements.
This writes out those elements in the VTK output when available.

Start with a WIP to make sure this is how the libmesh folks want this done.

For verification, I just look at the result in paraview  with a tesselation. As @roystgnr said in #3152 , not sure how else to check it.

[PlateWithHole_Patch8_0.vtu.gz](https://github.com/libMesh/libmesh/files/8050965/PlateWithHole_Patch8_0.vtu.gz)

closes #3152

### CODE REVIEW

**Comment by lindsayad** [comment]
@brianmoose what's up?!

**Review by jwpeterson — APPROVED** [review]
Do we know what version of Paraview supports (or will support) these types of elements?

**Comment by brianmoose** [comment]
Hey @lindsayad  ! Just started at Coreform about a month ago and now trying to bring @brianmoose back to life!

@jwpeterson Based off the VTK submodule in Paraview, looks like 5.8.0 was the first version that used a VTK that had the VTK_BEZIER_* stuff in it.

**Comment by jwpeterson** [comment]
> looks like 5.8.0 was the first version

OK, thanks I will check that out. I guess this PR imples you didn't run into issues with compiling libmesh against VTK 9, so that's good.

**Comment by lindsayad** [comment]
@jwpeterson not scared of WIP and absence of CI

**Comment by jwpeterson** [comment]
Hah, I clicked the wrong button didn't I.

**Comment by lindsayad** [comment]
> Hey @lindsayad ! Just started at Coreform about a month ago and now trying to bring @brianmoose back to life!

It's fun seeing you back in the community!

**Comment by brianmoose** [comment]
No problems with compiling against VTK 9, that seems to be the default with MOOSE anyway.
I can't believe CIVET is still up and running, @jwpeterson don't deprive me of the full experience :smile:

**Comment by brianmoose** [comment]
Haha, looks like I will get the full experience, I forgot to put a VTK guard in the unit tests...

**Comment by jwpeterson** [comment]
Hah, sorry about that. I guess you an always open a second PR to fix the one I accidentally merged.

**Pull request merged**
