### PR TITLE
bug fix for exodus write_timestep with single precision

### PR DESCRIPTION
**Pull request by svallaghe**
Enabling single precision when writing exodus time series was giving a wrong visualization under paraview.
This can be easily checked on the example transient_ex1 for instance, by adding the flag "true" when creating ExodusII_IO objects:
"ExodusII_IO exio(mesh,true)"

### CODE REVIEW

**Comment by roystgnr** [comment]
The second half of the patch looks good.

I'm afraid I don't understand the first half... Ah!  We can request a single-precision write from the constructor even if we're configured for higher precision, and we were doing the wrong thing in that case?

:+1: - I'll merge this afternoon unless someone objects.

**Comment by svallaghe** [comment]
Yes, there's this option to write in floats to save memory/disk space, even if the computations was done using doubles.
This feature was added a few years back but without treating the time dependent case.
This fix is just for that.

**Comment by jwpeterson** [comment]
Thanks for the fix, just fixed a small formatting issue before merging.

**Comment by jwpeterson** [comment]
FYI this bugfix was also cherry-picked onto the v1.2.0 branch. See also #1286.

**Pull request merged**
