### PR TITLE
Take out of libmesh_assert for an API integration

### PR DESCRIPTION
**Pull request by fdkong**
https://github.com/idaholab/moose/pull/15727

### CODE REVIEW

**Comment by fdkong** [comment]
When something was wrong, it has to be wrong for a while before we can it right.

**Comment by lindsayad** [comment]
Are you channeling some inner Yoda?

**Comment by mangerij** [comment]
ask not what the code does, but what the code was intended to do
________________________________

**Comment by fdkong** [comment]
@roystgnr Could you click the button to get my evil in?

**Pull request merged**
