### PR TITLE
reduced_basis_ex7 fixes

### PR DESCRIPTION
**Pull request by roystgnr**
Before, complex-valued PETSc-enabled libMesh builds would die on reduced_basis_ex7 unless you manually set LIBMESH_OPTIONS to a direct solver.

Now, complex-valued PETSc-enabled libMesh builds will die on reduced_basis_ex7 unless you configured PETSc with MUMPS.

This should be enough to get my BuildBot libMesh --enable-complex stage working, which is what I care about, but suggestions for further improvement would be welcome.

### CODE REVIEW

**Comment by jwpeterson** [comment]
I take it this does it not work with just straight `-pc_type lu`?  Otherwise I don't see the need to introduce a MUMPS dependency in addition to the PETSc dependency?

**Comment by jwpeterson** [comment]
Also I am ready to backport this to 1.0.0 if you think that's a good idea.

**Comment by jwpeterson** [comment]
> I take it this does it not work with just straight -pc_type lu?

Ah, I see now that you were more worried about it working in parallel... 

Maybe a `run_example_serial()` function in run_common.sh?  This would ignore the user's $LIBMESH_RUN settings but otherwise be the same as the existing `run_example()`.

**Comment by roystgnr** [comment]
The trouble with ignoring LIBMESH_RUN is that we don't just use that for MPI.  It'd be annoying to be debugging and go through the "LIBMESH_RUN='libtool --mode=execute gdb --args'" rigamarole only to have the example outright ignore you.  You can use LIBMESH_RUN to do a fair "make check" on systems where the admins don't like you running jobs on the head/compile nodes, too.

Oh, and there used to be some MPI implementations that would crash on you if you didn't use "mpirun -np 1" for serial jobs.  I don't think that's ever the case anymore, but who knows.

**Comment by roystgnr** [comment]
I wouldn't bother backporting this one.  There was already a crummy-but-tolerable workaround (do "make check" in serial with LIBMESH_OPTIONS specifying LU, or with LIBMESH_OPTIONS specifying MUMPS LU), and it's only a flaw in the example setup, not in library code.

**Pull request merged**
