### PR TITLE
New unit test for add_system() with extra ints

### PR DESCRIPTION
**Pull request by roystgnr**
This turned out not to be the explanation for the failures in
https://github.com/idaholab/moose/pull/13706 but now that the test is
already written we should use it to avoid future regressions.

### CODE REVIEW

**Comment by roystgnr** [comment]
... this new test isn't actually running.  We disabled node_test.C when we disabled the Node copy constructor, and elem_test.C isn't pulling in dof_object_test.h, so the only extra integers tests being run are the ones in tests/mesh/

I'll fix that and then I'll bet this new test fails.

**Comment by roystgnr** [comment]
This seems to fix https://github.com/idaholab/moose/pull/13706 for me too; I'll merge if it passes CI.  @YaqiWang, want to try it out too?

**Comment by YaqiWang** [comment]
Trying it out, will let you know shortly.

**Comment by YaqiWang** [comment]
Yes, it does fix the test and produce the expected results! Thanks @roystgnr .

**Pull request merged**
