### PR TITLE
Rename protected FEMContext members

### PR DESCRIPTION
**Pull request by pbauman**
This falls squarely in OCD minutiae, but this was annoying enough when reading the code that I went ahead and changed it (actually separated this from a forthcoming PR). Doesn't touch the interface or public members. Compiles and fem_system examples run. Unless I offend @roystgnr or @jwpeterson sensibilities, I'll merge later today. (I did them separately, but I can squash these into 1 if y'all would rather.)

### CODE REVIEW

**Comment by roystgnr** [comment]
As long as we're going OCD on this code, should we have the internals use the accessors too?  That'll mean fewer changes down the road if we ever need to make the accessors more than shims.  I think member-variables-with-accessors are probably better off private than protected, too.

If the intermediate commits compile and run then I wouldn't squash them.

**Comment by pbauman** [comment]
Good idea. I'll make a pass and push to this branch.

**Comment by pbauman** [comment]
OK, I'm done. FEMSystem examples and GRINS `make check` are both happy. @dknez you might want to take a quick look at the (small) changes in DGFEMContext since I don't have any tests for it (did I miss a libMesh example that has it?). Otherwise, I'd like to merge this today.

**Comment by dknez** [comment]
The changes to dg_fem_context.C look fine to me. (There is no libMesh example that uses DGFEMContext, unfortunately. I added it for making a Reduced Basis version of misc_ex9, but I never made that Reduced Basis version into an example.)

**Pull request merged**
