### PR TITLE
Mixed dimension refinement fixes/more testing

### PR DESCRIPTION
**Pull request by roystgnr**
My attempt at fixing the remaining bugs in #691 and #693.  This finally passes with fem_system_ex4 for me now, and it doesn't seem to break the tests @cahaynes added either.

### CODE REVIEW

**Comment by pbauman** [comment]
@roystgnr Thanks for both taking a look at the #693 failures and coming up with fixes.

**Comment by pbauman** [comment]
Well, we made it past libMesh tests:

<pre>
/home/moosetest/civet/client_root_0/moose/framework/src/mesh/MooseMesh.C: In member function 'void MooseMesh::init()':
/home/moosetest/civet/client_root_0/moose/framework/src/mesh/MooseMesh.C:1708:9: error: no match for 'operator!' (operand type is 'libMesh::AutoPtr<libMesh::Partitioner>')
     if (!_custom_partitioner)
         ^
/home/moosetest/civet/client_root_0/moose/framework/src/mesh/MooseMesh.C:1708:9: note: candidate is:
/home/moosetest/civet/client_root_0/moose/framework/src/mesh/MooseMesh.C:1708:9: note: operator!(bool) <built-in>
/home/moosetest/civet/client_root_0/moose/framework/src/mesh/MooseMesh.C:1708:9: note:   no known conversion for argument 1 from 'libMesh::AutoPtr<libMesh::Partitioner>' to 'bool'
MOOSE Compiling C++ (in dbg mode) /home/moosetest/civet/client_root_0/moose/framework/src/postprocessors/ElementH1SemiError.C...
MOOSE Compiling C++ (in dbg mode) /home/moosetest/civet/client_root_0/moose/framework/src/postprocessors/ElementVariablePostprocessor.C...
In file included from /home/moosetest/civet/client_root_0/moose/framework/include/utils/InputParameters.h:28:0,
                 from /home/moosetest/civet/client_root_0/moose/framework/include/mesh/MooseMesh.h:18,
                 from /home/moosetest/civet/client_root_0/moose/framework/src/mesh/MooseMesh.C:15:
/home/moosetest/civet/client_root_0/moose/framework/include/utils/MooseTypes.h: At global scope:
/home/moosetest/civet/client_root_0/moose/framework/include/utils/MooseTypes.h:84:19: warning: 'Moose::ANY_BLOCK_ID' defined but not used [-Wunused-variable]
 const SubdomainID ANY_BLOCK_ID = libMesh::Elem::invalid_subdomain_id - 1;
                   ^
make: *** [/home/moosetest/civet/client_root_0/moose/framework/src/mesh/MooseMesh.x86_64-unknown-linux-gnu.dbg.lo] Error 1
make: *** Waiting for unfinished jobs....
ERROR: Cleaning up
</pre>

I don't understand the thing that I am seeing...

**Comment by jwpeterson** [comment]
This is definitely weird.  I'll take a closer look, but for some reason libmesh on the build box got built with the old AutoPtr as the UniquePtr type...

**Comment by jwpeterson** [comment]
I think I understand the problem. Turns out we configure libmesh differently in the libmesh PR tests vs. the MOOSE PR tests. In the libmesh PR tests, we *don't* configure with `--enable-unique-ptr`, so even though C++11 `std::unique_ptr` is found, we don't use it.  This explains the error message's reference to libMesh::AutoPtr.  And since there is no `operator bool` defined for AutoPtr, that explains why one can't do `if (!foo)` with it.

I'd like to try and fix this by adding `operator bool` to libmesh's `AutoPtr` and continue testing both configurations (unique ptr both enabled and disabled) with the CI system.

**Comment by pbauman** [comment]
Anything we need to do to get Civet to run the tests again since #695 was merged?

**Comment by jwpeterson** [comment]
Yeah, we can just invalidate the failed ones.

**Comment by jwpeterson** [comment]
I'm going to ignore the debug one for the moment -- they are failing due to timeouts from the performance regression right now anyway.

**Comment by jwpeterson** [comment]
Cool, looks like it passed!

**Pull request merged**
