### PR TITLE
Print more information when we hit an element with a negative Jacobian.

### PR DESCRIPTION
**Pull request by jwpeterson**
Because why not?

### CODE REVIEW

**Comment by roystgnr** [comment]
:+1:, and thanks!

**Comment by dknez** [comment]
I'd like to merge this so I can use it in my testing. I assume that's OK with everyone?

**Comment by roystgnr** [comment]
Yup.  Although "git checkout origin/better_error" wouldn't have been much of a hassle.

**Comment by roystgnr** [comment]
It's slightly more tricky to test with a PR when it's coming from some_fork/some_branch and you haven't yet added a remote for some_fork.

**Comment by permcody** [comment]
If there's a PR, there's one more shortcut that works for the "don't have a
remote for that fork" case:
git fetch origin pull/ID/head: BRANCHNAME

I personally like this approach quite a bit as I don't have to manage a
bunch of remotes to peoples forks.

Cody

**Comment by jwpeterson** [comment]
On Tue, May 5, 2015 at 11:25 AM, Cody Permann <notifications@github.com>
wrote:

> If there's a PR, there's one more shortcut that works for the "don't have a
> remote for that fork" case:
> git fetch origin pull/ID/head: BRANCHNAME
>
> I personally like this approach quite a bit as I don't have to manage a
> bunch of remotes to peoples forks.
>

IMO it isn't that bad having a bunch of remotes, it's basically
add-and-forget.

Just remember *not* to "git fetch bob", since then you will get all of
bob's branches.

Instead,

git fetch bob branch_name
... do work...
git branch -d -r bob/branch_name

AFAIK the "git fetch origin pull/ID/head: BRANCHNAME" method is
github-specific.

-- 
John

**Pull request merged**
