### PR TITLE
Update BOOST m4 file to include proper flag

### PR DESCRIPTION
**Pull request by aeslaughter**
Thanks @jwpeterson

### CODE REVIEW

**Comment by jwpeterson** [comment]
:+1:

**Comment by roystgnr** [comment]
Has this been submitted upstream?  I don't think having to use ```#ifdef``` is so awful that it's worth forking boost.m4.

**Comment by jwpeterson** [comment]
Well, we've already forked it (13ef034177d5618d9b340770a7fc01e170e9cbb4, 0d8ea46682b082a0bb8f638af31f23273e0515e0) and those changes are not in upstream either...

**Comment by jwpeterson** [comment]
Not to say that two wrongs make a right, but I don't think diverging from upstream autoconf-archive in order to support libmesh-specific changes is all that big of a deal...

**Pull request merged**
