### PR TITLE
Delete dangerous implicit conversions for should_p_refine

### PR DESCRIPTION
**Pull request by lindsayad**
I immediately shot myself in the foot with my own code per https://github.com/idaholab/moose/pull/25108#discussion_r1294127650. Let's not let myself nor anyone else do that in the future

### CODE REVIEW

**Review by roystgnr — APPROVED** [review]
Should we just turn things like FEFamily into scoped enums?  I suspect if C++11 had been out when we defined all our enums only Order would have been allowed to implicitly convert.

**Comment by roystgnr** [comment]
I'm not seeing CI kicking on here?

**Comment by lindsayad** [comment]
> Should we just turn things like FEFamily into scoped enums? I suspect if C++11 had been out when we defined all our enums only Order would have been allowed to implicitly convert.

That would probably be a good idea

> I'm not seeing CI kicking on here?

Yea GitHub is having problems with webhooks again

**Comment by lindsayad** [comment]
failure unrelated

**Pull request merged**
