### PR TITLE
Try changing max order for L2 families

### PR DESCRIPTION
**Pull request by lindsayad**
Let's see what breaks!

### CODE REVIEW

**Review by jwpeterson — APPROVED** [review]

**Comment by roystgnr** [comment]
Have you tried a p-refined problem yet to make sure this actually works?  We almost certainly don't have anything in CI that's doing adaptive p-refinement of these families, and we definitely don't have anything in CI that's doing uniform p refinement or starting with high-p on them.

**Comment by lindsayad** [comment]
There's the errors!
```
(moose-petsc) lindad@inl610212:~/libmesh/installed/examples/miscellaneous/ex5(max-order)$ ./example-devel refinement_type=p fe_family="L2_LAGRANGE"
  Beginning Solve 0
Number of elements: 219
 assembling elliptic dg system... done
System has: 1536 degrees of freedom.
Linear solver converged at step: 14, final residual: 1.62233e-11
L2-Error is: 0.126732
ERROR: Bad ElemType = HEX8 for SECOND order approximation!
Stack frames: 10
0: 0   libmesh_devel.0.dylib               0x000000010ef14815 libMesh::print_trace(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) + 1141
1: 1   libmesh_devel.0.dylib               0x000000010ef0f58d libMesh::MacroFunctions::report_error(char const*, int, char const*, char const*) + 269
2: 2   libmesh_devel.0.dylib               0x000000010f2441c7 libMesh::(anonymous namespace)::l2_lagrange_n_dofs(libMesh::ElemType, libMesh::Order) + 2775
3: 3   libmesh_devel.0.dylib               0x000000010ee4164c libMesh::DofMap::reinit(libMesh::MeshBase&) + 6188
4: 4   libmesh_devel.0.dylib               0x000000010ee5f315 libMesh::DofMap::distribute_dofs(libMesh::MeshBase&) + 261
5: 5   libmesh_devel.0.dylib               0x000000010fa7cd5e libMesh::EquationSystems::reinit_solutions() + 1614
6: 6   libmesh_devel.0.dylib               0x000000010fa839ce libMesh::EquationSystems::reinit() + 14
7: 7   example-devel                       0x000000010eded8a8 main + 4232
8: 8   libdyld.dylib                       0x00007fff6e99e3d5 start + 1
9: 9   ???                                 0x0000000000000003 0x0 + 3
[0] ../src/fe/fe_l2_lagrange.C, line 394, compiled Jun 22 2021 at 10:28:43
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
[unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=1
:
system msg for write_line failure : Bad file descriptor
```

**Comment by lindsayad** [comment]
And for `L2_HIERARCHIC`:
```
Assertion `totalorder < 2' failed.
totalorder = 2
2 = 2


Stack frames: 19
0: 0   libmesh_devel.0.dylib               0x000000010b800815 libMesh::print_trace(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) + 1141
1: 1   libmesh_devel.0.dylib               0x000000010b7fb58d libMesh::MacroFunctions::report_error(char const*, int, char const*, char const*) + 269
2: 2   libmesh_devel.0.dylib               0x000000010baa9a7a (anonymous namespace)::fe_hierarchic_3D_shape(libMesh::Elem const*, libMesh::Order, unsigned int, libMesh::Point const&, bool) + 714
3: 3   libmesh_devel.0.dylib               0x000000010b9872b2 libMesh::FE<3u, (libMesh::FEFamily)6>::default_shapes(libMesh::Elem const*, libMesh::Order, unsigned int, std::__1::vector<libMesh::Point, std::__1::allocator<libMesh::Point> > const&, std::__1::vector<double, std::__1::allocator<double> >&, bool) + 146
4: 4   libmesh_devel.0.dylib               0x000000010bc04634 libMesh::H1FETransformation<double>::map_phi(unsigned int, libMesh::Elem const*, std::__1::vector<libMesh::Point, std::__1::allocator<libMesh::Point> > const&, libMesh::FEGenericBase<double> const&, std::__1::vector<std::__1::vector<double, std::__1::allocator<double> >, std::__1::allocator<std::__1::vector<double, std::__1::allocator<double> > > >&) const + 196
5: 5   libmesh_devel.0.dylib               0x000000010b9b0a9c libMesh::FEGenericBase<double>::compute_shape_functions(libMesh::Elem const*, std::__1::vector<libMesh::Point, std::__1::allocator<libMesh::Point> > const&) + 60
6: 6   libmesh_devel.0.dylib               0x000000010b8fbfc3 libMesh::FE<3u, (libMesh::FEFamily)6>::reinit(libMesh::Elem const*, std::__1::vector<libMesh::Point, std::__1::allocator<libMesh::Point> > const*, std::__1::vector<double, std::__1::allocator<double> > const*) + 995
7: 7   libmesh_devel.0.dylib               0x000000010c38cea4 libMesh::FEMContext::elem_fe_reinit(std::__1::vector<libMesh::Point, std::__1::allocator<libMesh::Point> > const*) + 148
8: 8   libmesh_devel.0.dylib               0x000000010c454686 libMesh::GenericProjector<libMesh::OldSolutionValue<double, &(void libMesh::FEMContext::point_value<double>(unsigned int, libMesh::Point const&, double&, double) const)>, libMesh::OldSolutionValue<libMesh::VectorValue<double>, &(void libMesh::FEMContext::point_gradient<libMesh::VectorValue<double> >(unsigned int, libMesh::Point const&, double&, double) const)>, double, libMesh::VectorSetAction<double> >::ProjectInteriors::operator()(libMesh::StoredRange<std::__1::__wrap_iter<libMesh::Elem const* const*>, libMesh::Elem const*> const&) + 1238
9: 9   libmesh_devel.0.dylib               0x000000010c43fdbf void libMesh::Threads::parallel_reduce<libMesh::StoredRange<std::__1::__wrap_iter<libMesh::Elem const* const*>, libMesh::Elem const*>, libMesh::GenericProjector<libMesh::OldSolutionValue<double, &(void libMesh::FEMContext::point_value<double>(unsigned int, libMesh::Point const&, double&, double) const)>, libMesh::OldSolutionValue<libMesh::VectorValue<double>, &(void libMesh::FEMContext::point_gradient<libMesh::VectorValue<double> >(unsigned int, libMesh::Point const&, double&, double) const)>, double, libMesh::VectorSetAction<double> >::ProjectInteriors>(double const&, libMesh::GenericProjector<libMesh::OldSolutionValue<double, &(void libMesh::FEMContext::point_value<double>(unsigned int, libMesh::Point const&, double&, double) const)>, libMesh::OldSolutionValue<libMesh::VectorValue<double>, &(void libMesh::FEMContext::point_gradient<libMesh::VectorValue<double> >(unsigned int, libMesh::Point const&, double&, double) const)>, double, libMesh::VectorSetAction<double> >::ProjectInteriors&) + 79
10: 10  libmesh_devel.0.dylib               0x000000010c40d6e2 libMesh::GenericProjector<libMesh::OldSolutionValue<double, &(void libMesh::FEMContext::point_value<double>(unsigned int, libMesh::Point const&, double&, double) const)>, libMesh::OldSolutionValue<libMesh::VectorValue<double>, &(void libMesh::FEMContext::point_gradient<libMesh::VectorValue<double> >(unsigned int, libMesh::Point const&, double&, double) const)>, double, libMesh::VectorSetAction<double> >::project(libMesh::StoredRange<libMesh::MeshBase::const_element_iterator, libMesh::Elem const*> const&) + 2002
11: 11  libmesh_devel.0.dylib               0x000000010c40ba83 libMesh::System::project_vector(libMesh::NumericVector<double> const&, libMesh::NumericVector<double>&, int) const + 2867
12: 12  libmesh_devel.0.dylib               0x000000010c412680 libMesh::System::project_vector(libMesh::NumericVector<double>&, int) const + 64
13: 13  libmesh_devel.0.dylib               0x000000010c3b8ff4 libMesh::System::restrict_vectors() + 500
14: 14  libmesh_devel.0.dylib               0x000000010c368d73 libMesh::EquationSystems::reinit_solutions() + 1635
15: 15  libmesh_devel.0.dylib               0x000000010c36f9ce libMesh::EquationSystems::reinit() + 14
16: 16  example-devel                       0x000000010b6d88a8 main + 4232
17: 17  libdyld.dylib                       0x00007fff6e99e3d5 start + 1
18: 18  ???                                 0x0000000000000003 0x0 + 3
[0] ../src/fe/fe_hierarchic_shape_3D.C, line 1562, compiled Jun 22 2021 at 10:28:27
```

**Comment by lindsayad** [comment]
We could expand `L2_LAGRANGE` but there is some ambiguity about what to do for say QUAD4/HEX8 with order > 1. I would think we'd want to do the tensor products, e.g. order = 2 on a QUAD4 should appear like QUAD9 as opposed to QUAD8. What do you all think about that.

Conceptually there shouldn't be ambiguity with expanding `L2_HIERARCHIC` support

**Comment by roystgnr** [comment]
> I would think we'd want to do the tensor products, e.g. order = 2 on a QUAD4 should appear like QUAD9 as opposed to QUAD8. What do you all think about that?

Strongly agreed.

> Conceptually there shouldn't be ambiguity with expanding L2_HIERARCHIC support

Yeah, I'm wondering if this isn't just an overzealous assertion that we can rewrite to only apply to regular `HIERARCHIC`

**Comment by lindsayad** [comment]
> Yeah, I'm wondering if this isn't just an overzealous assertion that we can rewrite to only apply to regular `HIERARCHIC`

Exactly what it was. See if you agree with what I did https://github.com/libMesh/libmesh/pull/2952/commits/75ddfd4f50a3d1e3d84deb84bf412b2b55189a5f to circumvent it

**Review by roystgnr — APPROVED** [review]
That looks like the optimal fix to me.

**Comment by jbadger95** [comment]
One simple construction for L2_LAGRANGE is to just use LAGRANGE shape functions but without enforcing continuity but I wonder if this is the best approach. For example, thinking about 1D HIERARCHIC shape functions, the lowest order shape functions are just the linears: x and (1-x). The L2_HIERARCHIC shape functions essentially correspond to derivatives of these, the lowest order is just composed of the constant, then first order L2_HIERARCHIC are composed of a constant and a linear (which was the derivative of a quadratic guy). So essentially the point I'm trying to make is that L2_HIERARCHIC isn't just HIERARCHIC without continuity (although the spaces spanned are the same) and I'm wondering if it makes sense to do something similar with L2_LAGRANGE. Just a thought, in the end it probably doesn't matter much since the spaces spanned will be the same but it can be useful for example to have the constant shape function for things like quick access to averages. 

Also I wanted to point out that the naming convention of the L2 shape functions is a bit awkward with the exact sequence (but it probably doesn't make much sense to change it). It comes down to whether ORDER represents polynomial order (which is what's adhered to by MOOSE) or approximation order. For example, if you look at the exact sequence of order p in 3D, H^1 has polynomials of order p, H(curl) and H(div) have sort of mixed polynomial order, and L^2 has polynomials of order p-1, but all these (in an ideal FE) scheme should produce order p approximations. But as I said, probably makes sense to keep ORDER as polynomial order since users who know about this should be able to navigate it without too much trouble

**Comment by lindsayad** [comment]
@roystgnr you may want to look at https://github.com/libMesh/libmesh/pull/2952/commits/3f3a62e22e7e955fe4cc95d37a096bcffe0dbcbd which is a commit for second order `L2_LAGRANGE` on first order elements and see if you still approve.

**Comment by lindsayad** [comment]
> So essentially the point I'm trying to make is that L2_HIERARCHIC isn't just HIERARCHIC without continuity

For us it *is* though because of your later point that `Order` represents polynomial order for us and not approximation order. So the way we treat the pairings LAGRANGE-L2_LAGRANGE and HIERARCHIC-L2_HIERARCHIC is identical: we call the same `fe_lagrange_*D_shape` helper function for LAGRANGE and L2_LAGRANGE and we call the same `fe_hierarchic_*D_shape` helper function for HIERARCHIC and L2_HIERARCHIC and get the same shape function evaluations for a given `Order`.

**Comment by jbadger95** [comment]
I’m not at my computer right now but isn’t CONSTANT implemented for L2_hierarchic? Would it make sense to swap out on of the linears for constant in the higher order ones? I know for example in my advisors code we use the constant shape function for a few things including evaluating the DPG error indicator (it makes it so we only have to assemble a single column of the stiffness matrix for uncondensing, technically you could do the same thing using linears but for example on a Hex you have to use 8 DoFs to represent a constant). Could also be useful in coupling FV or something. Sorry not trying to push it, just wondering if it might make sense.

**Comment by lindsayad** [comment]
> I’m not at my computer right now but isn’t CONSTANT implemented for L2_hierarchic?

No it isn't. `CONSTANT` is implemented for `MONOMIAL`

**Comment by roystgnr** [comment]
> I definitely think we should support CONSTANT L2_HIERARCHIC especially if we think about supporting your energy sequences.

I don't.  In our code the key thing about the HIERARCHIC bases is that they're literally hierarchic: the basis for order n-1 is just the first N terms of the basis for any higher order, and the key thing about the L2_FOO bases is that their projection onto FOO on the same element, in the element bases, is an identity matrix.  We have code depending on the first characteristic and I'm sure others have code depending on the second.

We also have code depending on the idea that basis numbering doesn't change: our restart files.  If it turns out that we screwed up a basis in some way, the way to fix that is to add a new basis name and eventually deprecate the old one, not redefine the old basis and corrupt any old files that used it.

**Comment by roystgnr** [comment]
The implementation in 3f3a62e looks good to me.  I assume the examples/ change covers it, and triggered failures before the corresponding src/ changes went in?

**Comment by lindsayad** [comment]
Correct. Produced one of the backtraces shown earlier in the PR

**Comment by roystgnr** [comment]
Something wonky with moosebuild?  That "Test debug" target looks complete when I click on "Details" but is still "Pending (9/9)" in the summary for me.

**Comment by lindsayad** [comment]
Something seems off with the reporting to github. It's also registered as complete here https://civet.inl.gov/pr/13854/

**Comment by roystgnr** [comment]
Good enough for me.  Though I still see the little yellow dot in https://github.com/libMesh/libmesh/pulls?q=is%3Apr+is%3Aclosed - taunting me.

**Pull request merged**
