### PR TITLE
Fix --disable-amr build.

### PR DESCRIPTION
**Pull request by jwpeterson**
Refs #850.

### CODE REVIEW

**Comment by jwpeterson** [comment]
Also attached the optional "Test No AMR" recipe...

**Comment by jwpeterson** [comment]
Looks like a unit test is also failing with AMR disabled. I'll have to take a closer look, but it may be that this test should not be run in this configuration...
```
[0] ../src/base/dof_map_constraints.C, line 3389, compiled Nov 26 2018 at 08:17:07
[0]PETSC ERROR: ------------------------------------------------------------------------
[0]PETSC ERROR: Caught signal number 11 SEGV: Segmentation Violation, probably memory access out of range
```

**Comment by roystgnr** [comment]
Serial unit tests pass for me now but I'm still getting a failure in parallel.

**Comment by roystgnr** [comment]
And none of our CI is running the libMesh tests in parallel.  @pbauman, @jwpeterson, could we change the GRINS-devel and "Test debug" recipes to use, say, LIBMESH_RUN='mpiexec -n 8'?  The speedup on bigger examples will probably outweigh the extra overhead on tiny cases.

**Comment by roystgnr** [comment]
Or maybe we use a different processor count on each; 8 on one and 16 on another?  I know John just added the sweep recipes but I don't want to use those often and it'd be good to get a *little* less redundancy in the different tests.

**Comment by jwpeterson** [comment]
> could we change the GRINS-devel and "Test debug" recipes to use, say, LIBMESH_RUN='mpiexec -n 8'?

You talking specifically about unit tests now, or all of the tests that get run by "make check"?

**Comment by roystgnr** [comment]
All the "make check" tests.  The unit tests are all tiny enough that I'm sure running in parallel is just going to make them slower, and they don't give as much corner case coverage as the whole swath of adaptivity and adjoints examples do.

**Comment by jwpeterson** [comment]
OK, so a single parallel (-n 8) "make check" step added to the "Test debug" recipe? Should be easy enough...

**Comment by roystgnr** [comment]
I'd just replace the existing step.  It's much rarer for a bug to affect serial but not parallel runs than for it to break the other way around.

**Comment by jwpeterson** [comment]
:+1: I can't formally approve this PR since I opened it. Thanks for finding the remaining issues @roystgnr!

**Comment by jwpeterson** [comment]
I just looked at the Test_debug recipe and it already does this.
```
[Check]
script = scripts/build.sh
abort_on_failure = True
allowed_to_fail = False
APP_SUBDIR = build
MAKE_ARGS = check
LIBMESH_RUN = mpiexec -np 4
```
Looks like the change was made in idaholab/civet_recipes@09aeaab37bd070d77dbcaecb18ba46d7140e53b3 (Oct 2017).

**Comment by jwpeterson** [comment]
If you drill down into the CIVET output for the Test_debug recipe, you should see e.g.:
```
***************************************************************
* Done Running Example introduction_ex1:
*  mpiexec -np 4 ./example-dbg -d 3 output.xdr 
***************************************************************
```

**Comment by jwpeterson** [comment]
Anyway, I think this can be merged whenever you are ready.

**Comment by roystgnr** [comment]
Aha!  We're passing Test debug not because it's running in serial, but because it doesn't have any unit tests being run!  No good way to fix that unless you happen to have a mixing-glibcxx_debug-settings-compatible cppunit install on your build boxes, and that would be pretty fragile.  Or unless we turn off the glibcxx debugging, but I think that would lose more coverage than it added.

**Comment by roystgnr** [comment]
Anyway, the parallel fix worked for me.  Thanks for getting this started!

**Pull request merged**
