### PR TITLE
Temporary workaround for MOOSE apps (mis)using LibmeshPetscCall

### PR DESCRIPTION
**Pull request by nmnobre**

### CODE REVIEW

**Comment by roystgnr** [comment]
Copied to https://github.com/libMesh/libmesh/tree/farscape_workaround_test so we can test this in the MOOSE PRs.  Please remind me to delete that when we're done with it.

**Review by lindsayad — COMMENTED** [review]
Is this what just passed in idaholab/moose#28969?

**Comment by nmnobre** [comment]
> Is this what just passed in [idaholab/moose#28969](https://github.com/idaholab/moose/pull/28969)?

Affirm.

- [ ] 1) Delete https://github.com/libMesh/libmesh/tree/farscape_workaround_test
- [ ] 2) Merge this PR
- [ ] 3) Update MOOSE's libMesh submodule
- [ ] 4) Rebase and merge idaholab/moose#28929
- [ ] 5) Revert this PR and fb0abb5
- [ ] 6) Kindly ask app devs to update their apps
- [ ] 7) Reuse idaholab/moose#28969 to periodically police app devs :P
- [ ] 8) Update MOOSE's libMesh submodule

**Comment by lindsayad** [comment]
Such a simple process 😆

**Review by lindsayad — APPROVED** [review]

**Comment by jwpeterson** [comment]
@nmnobre I think this PR caused a failure in the "Test No Exceptions" testing that we do for the devel -> master merge, see e.g. [here](https://civet.inl.gov/job/2552291/). There are many error error messages from the compiler, but some representative ones are:
```
In file included from ./include/libmesh/petsc_shell_matrix.h:33,
                 from ./include/libmesh/petsc_matrix_shell_matrix.h:26,
                 from ./include/libmesh/static_condensation.h:26,
                 from ../src/base/dof_map.C:42:
./include/libmesh/petsc_vector.h: In constructor 'libMesh::PetscVector<T>::PetscVector(Vec, const libMesh::Parallel::Communicator&)':
./include/libmesh/petsc_vector.h:598:3: error: there are no arguments to 'LibmeshPetscCall' that depend on a template parameter, so a declaration of 'LibmeshPetscCall' must be available [-fpermissive]
   LibmeshPetscCall(VecGetLocalSize(_vec, &petsc_local_size));
   ^~~~~~~~~~~~~~~~
./include/libmesh/petsc_vector.h:598:3: note: (if you use '-fpermissive', G++ will accept your code, but allowing the use of an undeclared name is deprecated)
```
And many others along the same lines:
```
./include/libmesh/petsc_vector.h:602:3: error: there are no arguments to 'LibmeshPetscCall' that depend on a template parameter, so a declaration of 'LibmeshPetscCall' must be available [-fpermissive]
   LibmeshPetscCall(VecGetType(_vec, &ptype));
   ^~~~~~~~~~~~~~~~
./include/libmesh/petsc_vector.h:637:7: error: there are no arguments to 'LibmeshPetscCall' that depend on a template parameter, so a declaration of 'LibmeshPetscCall' must be available [-fpermissive]
       LibmeshPetscCall(VecGetLocalToGlobalMapping(_vec, &mapping));
       ^~~~~~~~~~~~~~~~
```
I see from your previous comment that reverting this PR is part of the 8 step plan so I guess the issue will eventually be resolved, but we won't have any devel -> master merges in the meantime.

**Comment by nmnobre** [comment]
The errors make sense, the temporary definition is only on the with-exceptions code path. I'm at SC24, I'll try to push a patch this afternoon (or feel free to go ahead with a patch).

**Pull request merged**
