### PR TITLE
libmesh_not_implemented() in all unimplemented TypeNTensor functions

### PR DESCRIPTION
**Pull request by jwpeterson**
The constructors for this class are (sort of) implemented, but almost none of the actual API is... to prevent the possibility of any of the unimplemented functions being called and silently returning invalid results, they should all have `libmesh_not_implemented()` calls in them.

### CODE REVIEW

**Comment by roystgnr** [comment]
Looks like vector_fe_ex2 is unintentionally trying to calculate second derivative info, and second derivatives for a vector are a rank-3 tensor so it's screaming and dying when it gets there?

**Comment by roystgnr** [comment]
What I don't see is *how*.  I can't find any deliberate attempts to `get_d2phi()` in the example code, and I thought that our old "if user requests nothing, calculate everything" code path had been deprecated (and so would have been caught out in one of my many --disable-deprecated builds, if not in CI) long ago.

**Comment by jwpeterson** [comment]
This PR has been marked "do not merge" since we are no longer accepting PRs into the `master` branch. All new PRs should be made on the `devel` branch instead. Once this PR's target branch has been updated to `devel`, the "do not merge" label will be removed.

**Comment by roystgnr** [comment]
Turned out it was `ExactSolution` trying to calculate H2 seminorms whether we were ever going to used them or not.  I made that calculation type-dependent in #3180 so hopefully this should pass now.  I'll redirect to devel to kick off a new CI run.

**Comment by roystgnr** [comment]
We've got 7 "failing" checks because they're recipes that were changed so extensively that they no longer exist.  As long as the other 15 recipes pass I'll be happy to merge.

**Comment by jwpeterson** [comment]
Nice, thanks for remembering this PR existed!

**Comment by jwpeterson** [comment]
It looks like vector_fe_ex_2 failed on the latest [complex+ifem build](https://civet.inl.gov/job/974527/) in a call to `libMesh::ExactSolution::compute_error()`. I can't tell if it's still hitting a `libmesh_not_implemented()` but presumably that's the issue.
```
Stack frames: 8
0: libMesh::print_trace(std::ostream&)
1: libMesh::MacroFunctions::report_error(char const*, int, char const*, char const*)
2: libMesh::TypeNTensor<3u, libMesh::CompareTypes<std::complex<double>, std::complex<double> >::supertype> libMesh::TypeNTensor<3u, std::complex<double> >::operator-<std::complex<double> >(libMesh::TypeNTensor<3u, std::complex<double> > const&) const
3: void libMesh::ExactSolution::_compute_error<libMesh::VectorValue<double> >(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<double, std::allocator<double> >&)
4: libMesh::ExactSolution::compute_error(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
5: /opt/civet/build_1/libmesh/build/examples/vector_fe/vector_fe_ex2/.libs/lt-example-opt() [0x4187bc]
6: __libc_start_main
7: /opt/civet/build_1/libmesh/build/examples/vector_fe/vector_fe_ex2/.libs/lt-example-opt() [0x41915e]
[0] ./include/libmesh/type_n_tensor.h, line 132, compiled Mar  3 2022 at 07:32:02
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
[unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=1
```

**Comment by jwpeterson** [comment]
After wading through all the template output, it looks like the offending call is `TypeNTensor::operator-`.

**Comment by jwpeterson** [comment]
Oh, and vector_fe_ex2 has nothing to do with ifems or complex so it should be easy to reproduce...

**Comment by jwpeterson** [comment]
The error is triggered by the `grad2_u_h - exact_hess` line here:

```
#ifdef LIBMESH_ENABLE_SECOND_DERIVATIVES
          // Compute the value of the error in the hessian at this
          // quadrature point
          typename FEGenericBase<OutputShape>::OutputNumberTensor exact_hess;
          RawAccessor<typename FEGenericBase<OutputShape>::OutputNumberTensor> exact_hess_accessor( exact_hess, dim );
          if (_exact_hessians.size() > sys_num && _exact_hessians[sys_num])
            {
              //FIXME: This needs to be implemented to support rank 3 tensors
              //       which can't happen until type_n_tensor is fully implemented
              //       and a RawAccessor<TypeNTensor> is fully implemented
              if (FEInterface::field_type(fe_type) == TYPE_VECTOR)
                libmesh_not_implemented();

              for (unsigned int c = 0; c < n_vec_dim; c++)
                for (unsigned int d = 0; d < dim; d++)
                  for (unsigned int e =0; e < dim; e++)
                    exact_hess_accessor(d + e*dim + c*dim*dim) =
                      _exact_hessians[sys_num]->
                      component(var_component+c, q_point[qp], time)(d,e);
            }
          else if (_equation_systems_fine)
            {
              // FIXME: Needs to be updated for vector-valued elements
              std::vector<Tensor> output(1);
              coarse_values->hessian(q_point[qp],time,output,&subdomain_id);
              exact_hess = output[0];
            }

          const typename FEGenericBase<OutputShape>::OutputNumberTensor grad2_error = grad2_u_h - exact_hess;

          // FIXME: PB: Is this what we want for rank 3 tensors?
          error_vals[2] += JxW[qp]*grad2_error.norm_sq();
#endif
```

**Comment by jwpeterson** [comment]
It looks like we don't hit the `if` or the `else if` branches here, so we make it to the subtraction having never set a value for `exact_hess`.

**Comment by jwpeterson** [comment]
I'm testing a fix now and I'll push it to this old branch if it works for me locally...

**Pull request merged**
