### PR TITLE
 ASPECT_RATIO and STRETCH quality metrics for face_quad elements

### LINKED ISSUE #1532: Implement quality metrics (ASPECT_RATIO and STRETCH) for face_quad elements

### PR DESCRIPTION
**Pull request by hchen139**
close #1532

### CODE REVIEW

**Comment by hchen139** [comment]
@jwpeterson Please help to have a look at this PR. Thx.

**Comment by Kitein** [comment]
谌海龙？

⁣Gesendet mit BlueMail ​

**Comment by jwpeterson** [comment]
Looks reasonable to me. I will merge after a bit of refactoring to use `std::sort()` and making some formatting changes.

**Comment by jwpeterson** [comment]
@hchen139 I sent you an invite to join the libMesh collaborators team so that your PRs will be tested automatically in the future.

**Comment by roystgnr** [comment]
:+1:, thanks to both of you!

**Comment by jwpeterson** [comment]
@roystgnr did you want to manually activate those GRINS jobs? I don't think this PR can cause anything in GRINS to fail so it's up to you guys.

**Comment by hchen139** [comment]
Many thanks. @jwpeterson

**Comment by roystgnr** [comment]
Nah; I don't believe GRINS even touches the quality() method, and even if it did you're just adding new cases, not futzing with the existing ones.  This should be good to merge when MOOSE is happy.

**Pull request merged**
