### PR TITLE
Fixes for configure with CXXFLAGS=-Werror

### PR DESCRIPTION
**Pull request by roystgnr**
@lindsayad never mentioned any names, but I strongly approve of whatever crazy freak has `$CXXFLAGS` set to `-Werror` in their environment, and I apologize for the false negatives it was giving for some of our configure tests, and I hope this fixes the lot of them.

### CODE REVIEW

**Comment by jwpeterson** [comment]
meme

**Comment by lindsayad** [comment]
why did we get not testing triggered :-/

**Review by lindsayad — APPROVED** [review]

**Comment by roystgnr** [comment]
I was just wondering that myself, reworded a commit to force push and try again.

**Comment by roystgnr** [comment]
But I'm still seeing nothing.

**Comment by lindsayad** [comment]
looks good now!

**Pull request merged**
