### PR TITLE
Boundaryinfo equals fix

### PR DESCRIPTION
**Pull request by roystgnr**
A new unit test, intended to replicate the failure noted in #2630, in a commit after a bugfix for that failure.

@YaqiWang, could you try this and see if it works for your case too?

I'll merge this when CI is done either way; even if this turns out not to fix *that* bug, it at least fixes **a** bug.

### CODE REVIEW

**Comment by jwpeterson** [comment]
I have a comment about the documentation for this copy assignment operator:
```
  /**
   * Actual copying operation.
   *
   * \note The copy will have a reference to the same Mesh as the original.
   */
  BoundaryInfo & operator=(const BoundaryInfo & other_boundary_info);
```

I think it should instead say something like: "the mesh reference held by this BoundaryInfo will remain unchanged by assignment" or something along those lines. That's really the only thing that differentiates it from the default copy assignment operator in this case.

Also, while you're at it, it appears that `_ss_id_to_name` and friends are also not properly cleared in `BoundaryInfo::clear()`.

**Comment by roystgnr** [comment]
Damn, good catches.  I'll fix those.

**Comment by jwpeterson** [comment]
```
FAIL meshgenerators/mesh_extruder_generator.extruder/preserve_sideset_names FAILED (ERRMSG)
```
Huh, I guess there was a test actually relying on the behavior of not clearing sideset names in `clear()`. I would not have guessed this was the case. I guess if you want to comment that out to get this passing for now, and maybe we can add it back in later, that would be simplest?

**Comment by roystgnr** [comment]
Nah, I think I finally figured it out.  The bug you noticed while I was fixing the other bug was covering up a third bug.  Looks like the third bug is in libMesh too, so I'll fix that and tack on the fix here.

**Comment by YaqiWang** [comment]
Do not know why I did not notice this. Sorry. Just a quick question, do we need to fix MOOSE for this? It will give me some headache to find the case and rerun it.

**Comment by roystgnr** [comment]
We don't *need* to fix MOOSE; the failure case you noticed should have been completely fixed by this PR.

There's now some MooseMesh copy constructor code that's become redundant, so we should eventually delete a few lines there and just rely on this assignment operator working correctly under the hood, but the old code is just redundant, not incorrect or noticeably slow, so there's no rush.

**Pull request merged**
