### PR TITLE
Drop long-deprecated Elem APIs.

### PR DESCRIPTION
**Pull request by jwpeterson**
Seems like a good time to do this since 1.4.0 was released. I don't
think these will ever be truly gone from application codes until we
just remove them, so let's remove them.

### CODE REVIEW

**Comment by pbauman** [comment]
>  I don't think these will ever be truly gone from application codes until we
just remove them, so let's remove them.

Ha, busted.

**Comment by jwpeterson** [comment]
@pbauman I can probably make you a GRINS PR to fix these, unless it's convenient for you to do so.

**Comment by pbauman** [comment]
I appreciate the offer. I'll get it taken care of this afternoon. Don't let us hold up merging.

**Comment by pbauman** [comment]
Job [GRINS-devel](https://femputer.eng.buffalo.edu:8000/job/3209/) on 1aacd95 : invalidated by @pbauman

Removed these deprecated APIs from GRINS.

**Pull request merged**
