### PR TITLE
Fix all -Wconversion warnings with default id sizes

### PR DESCRIPTION
**Pull request by roystgnr**
This is a massive PR, and both @jwpeterson and I are going to be on vacation shortly, and @bboutkov has a more urgent PR that he wants to get wrapped up that may have conflicts, so there's no need to merge this any time in the next few weeks, but I definitely would like to see what our CI tests (especially the --enable-werror --enable-paranoid-warnings on femputer) think of it.

### CODE REVIEW

**Comment by pbauman** [comment]
That looks like a helluva rabbit hole you went down...

**Comment by pbauman** [comment]
In case you can't see femputer (I'm looking into a proper web certificate next week) libMesh build passed, but examples didn't:

<pre>
aking check in introduction/introduction_ex3
make[2]: Entering directory `/femputer/pbauman/civet_build_testing_root/libmesh-devel/examples/introduction/introduction_ex3'
make   example-devel    run.sh
make[3]: Entering directory `/femputer/pbauman/civet_build_testing_root/libmesh-devel/examples/introduction/introduction_ex3'
make[3]: Nothing to be done for `/femputer/pbauman/civet_build_testing_root/libMesh/examples/introduction/introduction_ex3/run.sh'.
  CXX      example_devel-introduction_ex3.o
  CXX      example_devel-exact_solution.o
/femputer/pbauman/civet_build_testing_root/libMesh/examples/introduction/introduction_ex3/introduction_ex3.C: In function ‘void assemble_poisson(libMesh::EquationSystems&, const string&)’:
/femputer/pbauman/civet_build_testing_root/libMesh/examples/introduction/introduction_ex3/introduction_ex3.C:300:34: error: conversion to ‘unsigned int’ from ‘std::vector<unsigned int>::size_type {aka long unsigned int}’ may alter its value [-Werror=conversion]
       Ke.resize (dof_indices.size(),
                  ~~~~~~~~~~~~~~~~^~
/femputer/pbauman/civet_build_testing_root/libMesh/examples/introduction/introduction_ex3/introduction_ex3.C:301:34: error: conversion to ‘unsigned int’ from ‘std::vector<unsigned int>::size_type {aka long unsigned int}’ may alter its value [-Werror=conversion]
                  dof_indices.size());
                  ~~~~~~~~~~~~~~~~^~
/femputer/pbauman/civet_build_testing_root/libMesh/examples/introduction/introduction_ex3/introduction_ex3.C:303:34: error: conversion to ‘unsigned int’ from ‘std::vector<unsigned int>::size_type {aka long unsigned int}’ may alter its value [-Werror=conversion]
       Fe.resize (dof_indices.size());
                  ~~~~~~~~~~~~~~~~^~
/femputer/pbauman/civet_build_testing_root/libMesh/examples/introduction/introduction_ex3/introduction_ex3.C:316:23: error: conversion to ‘unsigned int’ from ‘std::size_t {aka long unsigned int}’ may alter its value [-Werror=conversion]
                 Ke(i,j) += JxW[qp]*(dphi[i][qp]*dphi[j][qp]);
                       ^
/femputer/pbauman/civet_build_testing_root/libMesh/examples/introduction/introduction_ex3/introduction_ex3.C:316:23: error: conversion to ‘unsigned int’ from ‘std::size_t {aka long unsigned int}’ may alter its value [-Werror=conversion]
/femputer/pbauman/civet_build_testing_root/libMesh/examples/introduction/introduction_ex3/introduction_ex3.C:350:19: error: conversion to ‘unsigned int’ from ‘std::size_t {aka long unsigned int}’ may alter its value [-Werror=conversion]
               Fe(i) += JxW[qp]*fxy*phi[i][qp];
                   ^
/femputer/pbauman/civet_build_testing_root/libMesh/examples/introduction/introduction_ex3/introduction_ex3.C:427:29: error: conversion to ‘unsigned int’ from ‘std::size_t {aka long unsigned int}’ may alter its value [-Werror=conversion]
                       Ke(i,j) += JxW_face[qp]*penalty*phi_face[i][qp]*phi_face[j][qp];
                             ^
/femputer/pbauman/civet_build_testing_root/libMesh/examples/introduction/introduction_ex3/introduction_ex3.C:427:29: error: conversion to ‘unsigned int’ from ‘std::size_t {aka long unsigned int}’ may alter its value [-Werror=conversion]
/femputer/pbauman/civet_build_testing_root/libMesh/examples/introduction/introduction_ex3/introduction_ex3.C:432:25: error: conversion to ‘unsigned int’ from ‘std::size_t {aka long unsigned int}’ may alter its value [-Werror=conversion]
                     Fe(i) += JxW_face[qp]*penalty*value*phi_face[i][qp];
</pre>

**Comment by roystgnr** [comment]
Oh, of course.  The examples don't build on "make", only on "make check".  I was smart enough to do a ```LIBMESH_RUN=echo make check -C examples``` when working on #1812 but forgot to do it this time.

**Comment by roystgnr** [comment]
Hmm... and the MOOSE failure is actually an API change that I mistakenly *thought* wouldn't affect anyone.  It's easy to fix on the user side but in the short term I'm not sure if that's the right way to go.

**Comment by pbauman** [comment]
This is the failure on the `make check` recipe in GRINS-devel (looks like adjoints_ex4):

<pre>
Making check in adjoints/adjoints_ex4
make[2]: Entering directory `/femputer/pbauman/civet_build_testing_root/libmesh-devel/examples/adjoints/adjoints_ex4'
make  check-am
make[3]: Entering directory `/femputer/pbauman/civet_build_testing_root/libmesh-devel/examples/adjoints/adjoints_ex4'
make   example-devel    run.sh
make[4]: Entering directory `/femputer/pbauman/civet_build_testing_root/libmesh-devel/examples/adjoints/adjoints_ex4'
  CXX      example_devel-element_qoi_derivative.o
make[4]: Nothing to be done for `/femputer/pbauman/civet_build_testing_root/libMesh/examples/adjoints/adjoints_ex4/run.sh'.
  CXX      example_devel-L-shaped.o
  CXX      example_devel-side_postprocess.o
  CXX      example_devel-adjoints_ex4.o
  CXX      example_devel-femparameters.o
  CXX      example_devel-side_qoi_derivative.o
  CXX      example_devel-element_postprocess.o
/femputer/pbauman/civet_build_testing_root/libMesh/examples/adjoints/adjoints_ex4/element_qoi_derivative.C: In member function ‘virtual void LaplaceSystem::element_qoi_derivative(libMesh::DiffContext&, const libMesh::QoISet&)’:
/femputer/pbauman/civet_build_testing_root/libMesh/examples/adjoints/adjoints_ex4/element_qoi_derivative.C:37:58: error: conversion to ‘unsigned int’ from ‘std::vector<unsigned int>::size_type {aka long unsigned int}’ may alter its value [-Werror=conversion]
   const unsigned int n_T_dofs = c.get_dof_indices(0).size();
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~^~
/femputer/pbauman/civet_build_testing_root/libMesh/examples/adjoints/adjoints_ex4/side_qoi_derivative.C: In member function ‘virtual void LaplaceSystem::side_qoi_derivative(libMesh::DiffContext&, const libMesh::QoISet&)’:
/femputer/pbauman/civet_build_testing_root/libMesh/examples/adjoints/adjoints_ex4/side_qoi_derivative.C:40:58: error: conversion to ‘unsigned int’ from ‘std::vector<unsigned int>::size_type {aka long unsigned int}’ may alter its value [-Werror=conversion]
   const unsigned int n_T_dofs = c.get_dof_indices(0).size();
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~^~
/femputer/pbauman/civet_build_testing_root/libMesh/examples/adjoints/adjoints_ex4/L-shaped.C: In member function ‘virtual bool LaplaceSystem::element_time_derivative(bool, libMesh::DiffContext&)’:
/femputer/pbauman/civet_build_testing_root/libMesh/examples/adjoints/adjoints_ex4/L-shaped.C:79:58: error: conversion to ‘unsigned int’ from ‘std::vector<unsigned int>::size_type {aka long unsigned int}’ may alter its value [-Werror=conversion]
   const unsigned int n_T_dofs = c.get_dof_indices(0).size();
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~^~
/femputer/pbauman/civet_build_testing_root/libMesh/examples/adjoints/adjoints_ex4/L-shaped.C: In member function ‘virtual bool LaplaceSystem::side_constraint(bool, libMesh::DiffContext&)’:
/femputer/pbauman/civet_build_testing_root/libMesh/examples/adjoints/adjoints_ex4/L-shaped.C:135:58: error: conversion to ‘unsigned int’ from ‘std::vector<unsigned int>::size_type {aka long unsigned int}’ may alter its value [-Werror=conversion]
   const unsigned int n_T_dofs = c.get_dof_indices(0).size();
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~^~
cc1plus: all warnings being treated as errors
cc1plus: all warnings being treated as errors
make[4]: *** [example_devel-element_qoi_derivative.o] Error 1
make[4]: *** Waiting for unfinished jobs....
make[4]: *** [example_devel-side_qoi_derivative.o] Error 1
cc1plus: all warnings being treated as errors
make[4]: *** [example_devel-L-shaped.o] Error 1
make[4]: Leaving directory `/femputer/pbauman/civet_build_testing_root/libmesh-devel/examples/adjoints/adjoints_ex4'
make[3]: *** [check-am] Error 2
make[3]: Leaving directory `/femputer/pbauman/civet_build_testing_root/libmesh-devel/examples/adjoints/adjoints_ex4'
make[2]: *** [check] Error 2
make[2]: Leaving directory `/femputer/pbauman/civet_build_testing_root/libmesh-devel/examples/adjoints/adjoints_ex4'
make[1]: *** [check-recursive] Error 1
make[1]: Leaving directory `/femputer/pbauman/civet_build_testing_root/libmesh-devel/examples'
make: *** [check-recursive] Error 1
cat: test/test-suite.log: No such file or directory
ERROR: exiting with code 1
</pre>

**Comment by roystgnr** [comment]
Thanks, but I can duplicate all these failures; I just didn't have time to actually fix them all before vacation.  Hmmm... I should strip out the compiler flags and the API changes and then at least the rest might be considered for merging.

**Pull request merged**
