### PR TITLE
Added a DenseMatrix function to compute outer product of 2 vectors

### PR DESCRIPTION
**Pull request by joshuahansel**
This adds a method to `DenseMatrix` to compute the outer product of 2 vectors and store it in the matrix object.

### CODE REVIEW

**Comment by jwpeterson** [comment]
One thing that I just read is that the [outer product of complex-valued vectors typically uses the conjugate transpose of the second vector](https://en.wikipedia.org/wiki/Outer_product). This would be pretty easy to implement using the `libmesh_conj()` function which is defined in libmesh_common.h, and then your code would give the expected results for real- and complex-valued builds.

**Comment by roystgnr** [comment]
Great, thanks!

:+1: once Civet is done.

**Comment by joshuahansel** [comment]
@jwpeterson Do you want the complex-value changes on this PR or a subsequent one?

**Comment by jwpeterson** [comment]
> Do you want the complex-value changes on this PR

This PR would be good. It's fine with me if you want to skip adding a complex-valued unit test specifically for the time being...

**Pull request merged**
