### PR TITLE
Systems of equations ex8 (rebased)

### PR DESCRIPTION
**Pull request by jwpeterson**
(Replaces #460.)

This compiles and runs for me, but I have some fairly serious issues with the performance of this example.  It's been running for over 10 minutes (in opt mode) on my system, taking up to 50 NL steps before failing some solves. Since we run the examples with not only every libmesh PR which gets tested but also every MOOSE PR, it's pretty bad to have an example this slow.

```
Performing solve 1, forcing_magnitude: 0.001, contact_penalty: 10
  NL step  0, |residual|_2 = 5.648720e-04
  NL step  1, |residual|_2 = 5.641630e-04
  NL step  2, |residual|_2 = 4.832477e-04
  NL step  3, |residual|_2 = 2.609847e-04
  NL step  4, |residual|_2 = 1.102499e-04
  NL step  5, |residual|_2 = 5.817022e-05
  NL step  6, |residual|_2 = 3.095772e-05
  NL step  7, |residual|_2 = 1.690786e-05
  NL step  8, |residual|_2 = 1.056366e-05
  NL step  9, |residual|_2 = 5.802202e-06
  NL step 10, |residual|_2 = 4.304370e-06
  NL step 11, |residual|_2 = 2.377938e-06
  NL step 12, |residual|_2 = 1.883154e-06
  NL step 13, |residual|_2 = 1.046683e-06
  NL step 14, |residual|_2 = 8.051227e-07
  NL step 15, |residual|_2 = 4.554674e-07
Nonlinear solver convergence/divergence reason: CONVERGED_FNORM_RELATIVE
System solved at nonlinear iteration 15 , final nonlinear residual norm: 4.554674e-07

Solution l2 norm: 4.585181e-01

Computing stresses...
Performing solve 2, forcing_magnitude: 1.500000e-03, contact_penalty: 1.000000e+01
  NL step  0, |residual|_2 = 2.824394e-04
  NL step  1, |residual|_2 = 2.165190e-04
  NL step  2, |residual|_2 = 1.911254e-04
  NL step  3, |residual|_2 = 1.451373e-04
  NL step  4, |residual|_2 = 4.373337e-05
  NL step  5, |residual|_2 = 3.283120e-05
  NL step  6, |residual|_2 = 1.532516e-05
  NL step  7, |residual|_2 = 1.170025e-05
  NL step  8, |residual|_2 = 6.643117e-06
  NL step  9, |residual|_2 = 4.603227e-06
  NL step 10, |residual|_2 = 2.657380e-06
  NL step 11, |residual|_2 = 1.820327e-06
  NL step 12, |residual|_2 = 1.148845e-06
  NL step 13, |residual|_2 = 7.515515e-07
  NL step 14, |residual|_2 = 5.148985e-07
  NL step 15, |residual|_2 = 3.291982e-07
  NL step 16, |residual|_2 = 2.383475e-07
Nonlinear solver convergence/divergence reason: CONVERGED_FNORM_RELATIVE
System solved at nonlinear iteration 16 , final nonlinear residual norm: 2.383475e-07

Solution l2 norm: 6.843984e-01

Computing stresses...
Performing solve 3, forcing_magnitude: 2.000000e-03, contact_penalty: 1.000000e+01
  NL step  0, |residual|_2 = 2.824347e-04
  NL step  1, |residual|_2 = 2.133578e-04
  NL step  2, |residual|_2 = 6.515121e-05
  NL step  3, |residual|_2 = 3.318758e-05
  NL step  4, |residual|_2 = 2.080842e-05
  NL step  5, |residual|_2 = 2.063058e-05
  NL step  6, |residual|_2 = 2.045862e-05
  NL step  7, |residual|_2 = 2.029223e-05
  NL step  8, |residual|_2 = 2.013110e-05
  NL step  9, |residual|_2 = 1.997496e-05
  NL step 10, |residual|_2 = 1.995978e-05
  NL step 11, |residual|_2 = 1.994465e-05
  NL step 12, |residual|_2 = 1.992956e-05
  NL step 13, |residual|_2 = 1.991452e-05
  NL step 14, |residual|_2 = 1.989952e-05
  NL step 15, |residual|_2 = 1.988457e-05
  NL step 16, |residual|_2 = 1.986966e-05
  NL step 17, |residual|_2 = 1.985480e-05
  NL step 18, |residual|_2 = 1.983998e-05
  NL step 19, |residual|_2 = 1.983983e-05
  NL step 20, |residual|_2 = 1.983968e-05
  NL step 21, |residual|_2 = 1.983953e-05
  NL step 22, |residual|_2 = 1.983952e-05
  NL step 23, |residual|_2 = 1.983950e-05
  NL step 24, |residual|_2 = 1.983949e-05
  NL step 25, |residual|_2 = 1.983947e-05
  NL step 26, |residual|_2 = 1.983947e-05
  NL step 27, |residual|_2 = 1.983947e-05
  NL step 28, |residual|_2 = 1.983947e-05
  NL step 29, |residual|_2 = 1.983947e-05
  NL step 30, |residual|_2 = 1.983947e-05
  NL step 31, |residual|_2 = 1.983947e-05
  NL step 32, |residual|_2 = 1.983947e-05
  NL step 33, |residual|_2 = 1.983947e-05
  NL step 34, |residual|_2 = 1.983947e-05
  NL step 35, |residual|_2 = 1.983947e-05
  NL step 36, |residual|_2 = 1.983947e-05
  NL step 37, |residual|_2 = 1.983947e-05
  NL step 38, |residual|_2 = 1.983947e-05
  NL step 39, |residual|_2 = 1.983947e-05
  NL step 40, |residual|_2 = 1.983947e-05
  NL step 41, |residual|_2 = 1.983947e-05
  NL step 42, |residual|_2 = 1.983947e-05
  NL step 43, |residual|_2 = 1.983947e-05
  NL step 44, |residual|_2 = 1.983947e-05
  NL step 45, |residual|_2 = 1.983947e-05
  NL step 46, |residual|_2 = 1.983947e-05
  NL step 47, |residual|_2 = 1.983947e-05
  NL step 48, |residual|_2 = 1.983947e-05
Nonlinear solver convergence/divergence reason: DIVERGED_LINE_SEARCH
System solved at nonlinear iteration 48 , final nonlinear residual norm: 1.983947e-05

Solution l2 norm: 8.879566e-01

Computing stresses...
Performing solve 4, forcing_magnitude: 2.500000e-03, contact_penalty: 1.000000e+01
  NL step  0, |residual|_2 = 2.831279e-04
  NL step  1, |residual|_2 = 1.792215e-04
  NL step  2, |residual|_2 = 8.665665e-05
  NL step  3, |residual|_2 = 4.102393e-05
  NL step  4, |residual|_2 = 2.933715e-05
  NL step  5, |residual|_2 = 1.484880e-05
  NL step  6, |residual|_2 = 1.300654e-05
  NL step  7, |residual|_2 = 8.982019e-06
  NL step  8, |residual|_2 = 8.643977e-06
  NL step  9, |residual|_2 = 7.817356e-06
  NL step 10, |residual|_2 = 7.730295e-06
  NL step 11, |residual|_2 = 7.511412e-06
  NL step 12, |residual|_2 = 7.456324e-06
  NL step 13, |residual|_2 = 7.353843e-06
  NL step 14, |residual|_2 = 7.296880e-06
  NL step 15, |residual|_2 = 7.221177e-06
  NL step 16, |residual|_2 = 7.161152e-06
  NL step 17, |residual|_2 = 7.093941e-06
  NL step 18, |residual|_2 = 7.032867e-06
  NL step 19, |residual|_2 = 6.969288e-06
  NL step 20, |residual|_2 = 6.908409e-06
  NL step 21, |residual|_2 = 6.846857e-06
  NL step 22, |residual|_2 = 6.786698e-06
  NL step 23, |residual|_2 = 6.726586e-06
  NL step 24, |residual|_2 = 6.667351e-06
  NL step 25, |residual|_2 = 6.608430e-06
  NL step 26, |residual|_2 = 6.550185e-06
  NL step 27, |residual|_2 = 6.492352e-06
  NL step 28, |residual|_2 = 6.435111e-06
  NL step 29, |residual|_2 = 6.378316e-06
  NL step 30, |residual|_2 = 6.322073e-06
  NL step 31, |residual|_2 = 6.266284e-06
  NL step 32, |residual|_2 = 6.211025e-06
  NL step 33, |residual|_2 = 6.156220e-06
  NL step 34, |residual|_2 = 6.101931e-06
  NL step 35, |residual|_2 = 6.048089e-06
  NL step 36, |residual|_2 = 5.994753e-06
  NL step 37, |residual|_2 = 5.941858e-06
  NL step 38, |residual|_2 = 5.889458e-06
  NL step 39, |residual|_2 = 5.837493e-06
  NL step 40, |residual|_2 = 5.786013e-06
  NL step 41, |residual|_2 = 5.734961e-06
  NL step 42, |residual|_2 = 5.684385e-06
  NL step 43, |residual|_2 = 5.634230e-06
  NL step 44, |residual|_2 = 5.584542e-06
  NL step 45, |residual|_2 = 5.535268e-06
  NL step 46, |residual|_2 = 5.486453e-06
  NL step 47, |residual|_2 = 5.438044e-06
  NL step 48, |residual|_2 = 5.390087e-06
  NL step 49, |residual|_2 = 5.342528e-06
  NL step 50, |residual|_2 = 5.295413e-06
Nonlinear solver convergence/divergence reason: DIVERGED_MAX_IT
System solved at nonlinear iteration 50 , final nonlinear residual norm: 5.295413e-06

Solution l2 norm: 1.089859e+00

Computing stresses...
Performing solve 5, forcing_magnitude: 3.000000e-03, contact_penalty: 1.000000e+01
  NL step  0, |residual|_2 = 2.824868e-04
  NL step  1, |residual|_2 = 1.706818e-04
  NL step  2, |residual|_2 = 1.010621e-04
  NL step  3, |residual|_2 = 9.242222e-05
  NL step  4, |residual|_2 = 6.451887e-05
  NL step  5, |residual|_2 = 4.691857e-05
  NL step  6, |residual|_2 = 4.027517e-05
  NL step  7, |residual|_2 = 3.966055e-05
  NL step  8, |residual|_2 = 3.910240e-05
  NL step  9, |residual|_2 = 3.856848e-05
  NL step 10, |residual|_2 = 3.805716e-05
  NL step 11, |residual|_2 = 3.756694e-05
  NL step 12, |residual|_2 = 3.709647e-05
  NL step 13, |residual|_2 = 3.664449e-05
  NL step 14, |residual|_2 = 3.620987e-05
  NL step 15, |residual|_2 = 3.616795e-05
  NL step 16, |residual|_2 = 3.612618e-05
  NL step 17, |residual|_2 = 3.608457e-05
  NL step 18, |residual|_2 = 3.608042e-05
  NL step 19, |residual|_2 = 3.607627e-05
  NL step 20, |residual|_2 = 3.607213e-05
  NL step 21, |residual|_2 = 3.606799e-05
  NL step 22, |residual|_2 = 3.606385e-05
  NL step 23, |residual|_2 = 3.606343e-05
  NL step 24, |residual|_2 = 3.606339e-05
  NL step 25, |residual|_2 = 3.606335e-05
  NL step 26, |residual|_2 = 3.606331e-05
  NL step 27, |residual|_2 = 3.606327e-05
  NL step 28, |residual|_2 = 3.606323e-05
  NL step 29, |residual|_2 = 3.606319e-05
  NL step 30, |residual|_2 = 3.606314e-05
  NL step 31, |residual|_2 = 3.606314e-05
  NL step 32, |residual|_2 = 3.606314e-05
  NL step 33, |residual|_2 = 3.606313e-05
  NL step 34, |residual|_2 = 3.606313e-05
  NL step 35, |residual|_2 = 3.606313e-05
  NL step 36, |residual|_2 = 3.606313e-05
  NL step 37, |residual|_2 = 3.606313e-05
  NL step 38, |residual|_2 = 3.606313e-05
  NL step 39, |residual|_2 = 3.606313e-05
  NL step 40, |residual|_2 = 3.606313e-05
  NL step 41, |residual|_2 = 3.606313e-05
  NL step 42, |residual|_2 = 3.606312e-05
  NL step 43, |residual|_2 = 3.606312e-05
  NL step 44, |residual|_2 = 3.606312e-05
  NL step 45, |residual|_2 = 3.606312e-05
  NL step 46, |residual|_2 = 3.606312e-05
  NL step 47, |residual|_2 = 3.606312e-05
  NL step 48, |residual|_2 = 3.606312e-05
  NL step 49, |residual|_2 = 3.606312e-05
  NL step 50, |residual|_2 = 3.606312e-05
Nonlinear solver convergence/divergence reason: DIVERGED_MAX_IT
System solved at nonlinear iteration 50 , final nonlinear residual norm: 3.606312e-05

Solution l2 norm: 1.284275e+00

Computing stresses...
Performing solve 6, forcing_magnitude: 3.500000e-03, contact_penalty: 1.000000e+01
  NL step  0, |residual|_2 = 2.846695e-04
  NL step  1, |residual|_2 = 1.781814e-04
  NL step  2, |residual|_2 = 1.175725e-04
  NL step  3, |residual|_2 = 4.464844e-05
  NL step  4, |residual|_2 = 2.968909e-05
  NL step  5, |residual|_2 = 1.970980e-05
  NL step  6, |residual|_2 = 1.351522e-05
  NL step  7, |residual|_2 = 8.842241e-06
  NL step  8, |residual|_2 = 5.816432e-06
  NL step  9, |residual|_2 = 3.586677e-06
  NL step 10, |residual|_2 = 2.289236e-06
  NL step 11, |residual|_2 = 1.364956e-06
  NL step 12, |residual|_2 = 8.543849e-07
  NL step 13, |residual|_2 = 4.990637e-07
  NL step 14, |residual|_2 = 3.088313e-07
  NL step 15, |residual|_2 = 1.778474e-07
Nonlinear solver convergence/divergence reason: CONVERGED_FNORM_RELATIVE
System solved at nonlinear iteration 15 , final nonlinear residual norm: 1.778474e-07

Solution l2 norm: 1.474246e+00

Computing stresses...
Performing solve 7, forcing_magnitude: 4.000000e-03, contact_penalty: 1.000000e+01
  NL step  0, |residual|_2 = 2.824313e-04
  NL step  1, |residual|_2 = 1.602663e-04
  NL step  2, |residual|_2 = 9.892372e-05
  NL step  3, |residual|_2 = 4.375143e-05
  NL step  4, |residual|_2 = 3.822861e-05
  NL step  5, |residual|_2 = 3.477424e-05
```

### CODE REVIEW

**Comment by dknez** [comment]
Agreed. Can you set "n_solves = 1" in systems_of_equations_ex8.in please? That will mean we only do one "continuation step", so it'll be a lot faster.

As a separate issue, it'd be good to make the nonlinear convergence more robust, but I'm not really sure how to do that (the penalty method for contact is known to give solvers a hard time).

**Comment by jwpeterson** [comment]
> Agreed. Can you set "n_solves = 1" in systems_of_equations_ex8.in please? That will mean we only do one "continuation step", so it'll be a lot faster.

Sure.

> As a separate issue, it'd be good to make the nonlinear convergence more robust, but I'm not really sure how to do that (the penalty method for contact is known to give solvers a hard time).

So right now, what does it mean when
```
Nonlinear solver convergence/divergence reason: DIVERGED_MAX_IT
```
is hit?  Clearly the example doesn't fail... Can we set a much lower number of max nonlinear iterations (have it fail faster) while still getting an interesting solution?

**Comment by dknez** [comment]
If nonlinear_max_its is hit then we haven't reduced the residual as far as we'd like, but in most cases where we hit nonlinear_max_its the results still seem reasonable.

We can lower the iteration limit, just set "nonlinear_max_its" in the systems_of_equations_ex8.in. But I'm not sure that's necessary now if we only do the first continuation step anyway, since the first solve only needs 15 iterations.

**Comment by jwpeterson** [comment]
> We can lower the iteration limit, just set "nonlinear_max_its" in the systems_of_equations_ex8.in. But I'm not sure that's necessary now if we only do the first continuation step anyway, since the first solve only needs 15 iterations.

Ah, yes, that makes sense!

BTW, the failure was due to the damn run.sh not being executable again, not sure why that keeps happening.

**Comment by jwpeterson** [comment]
With 1 solve, opt mode isn't bad (about 22 seconds), dbg mode takes a little over 5 minutes but maybe that's OK...

**Comment by dknez** [comment]
If you want to reduce max_its or increase nonlinear_tolerance to make dbg mode faster, that's fine with me...

**Comment by jwpeterson** [comment]
> If you want to reduce max_its or increase nonlinear_tolerance to make dbg mode faster, that's fine with me...

These options are definitely possible, but the tolerance already seems pretty loose and reducing the number of iterations signals a convergence failure in PETSc, although it doesn't cause the code itself to fail.

How do you feel about reducing the penalty parameter as in 7adf00e6c13 just for the purposes of speeding up the test?  I get about 5 seconds and 77 seconds in opt and debug modes, respectively, with this change.  Obviously the solution is less physically-meaningful but I tired to put a note in the input file to that effect.

Perhaps continuation in the penalty parameter is possible?  Longer term, it might be worth setting up a simpler geometry with fewer elements for this example and using tighter tolerances and more realistic penalty values, but that doesn't need to hold up this PR.

**Comment by dknez** [comment]
Your proposed changes are fine with me. I agree that it's important to have default values that run fast, for testing purposes. It's easy for users to play with the various problem parameters in an installed version of the library, so that's fine with me.

**Pull request merged**
