### PR TITLE
Fixed petsc_linear_solver for PETSc-master

### PR DESCRIPTION
**Pull request by fdkong**

### CODE REVIEW

**Comment by jwpeterson** [comment]
Looks good to me...  I attached "Test with PETSc master" as well.

**Comment by jwpeterson** [comment]
I think it's been a while since the CIVET recipe for testing PETSc master on libMesh PRs was updated. I'm sure you guys have already run into this before, though so it shouldn't be too hard to fix.
```
*******************************************************************************
         UNABLE to CONFIGURE with GIVEN OPTIONS    (see configure.log for details):
-------------------------------------------------------------------------------
Cannot use SuperLU_DIST without enabling C++11, see --with-cxx-dialect=C++11
*******************************************************************************
```

**Comment by fdkong** [comment]
> I think it's been a while since the CIVET recipe for testing PETSc master on libMesh PRs was updated. I'm sure you guys have already run into this before, though so it shouldn't be too hard to fix.
> 
> ```
> *******************************************************************************
>          UNABLE to CONFIGURE with GIVEN OPTIONS    (see configure.log for details):
> -------------------------------------------------------------------------------
> Cannot use SuperLU_DIST without enabling C++11, see --with-cxx-dialect=C++11
> *******************************************************************************
> ```

Yes we knew this. Just did not updater the script in civet yet.  I am going to do this.

**Comment by fdkong** [comment]
@jwpeterson I think we could merge the PR. The falling test is moose. I have a fix here https://github.com/idaholab/moose/pull/12897

**Comment by jwpeterson** [comment]
This will also go in v1.4.0 (#2029).

**Comment by fdkong** [comment]
Thanks, @jwpeterson

**Pull request merged**
