### PR TITLE
Add support for --drop-cerr command line argument.

### PR DESCRIPTION
**Pull request by jwpeterson**
There was also a libmesh-devel thread discussing this: http://tinyurl.com/hseqsm4

### CODE REVIEW

**Comment by jwpeterson** [comment]
@permcody

**Comment by permcody** [comment]
Hmm, I don't think I like the name. Maybe `--drop-parallel-cerr`, `--drop-other-cerr` `--drop-slave-cerr`, etc

**Comment by permcody** [comment]
`--keep-root-cerr`?

**Comment by jwpeterson** [comment]
It goes along with the existing `--keep-cout` option.  It's like the converse of that.

**Comment by permcody** [comment]
Fine you win...
image

**Comment by permcody** [comment]
We probably really should add something to the the libMesh abort handler (or whatever that is) that says to rerun without --drop-cerr.

**Pull request merged**
