### PR TITLE
Added MeshCommunication::check_for_duplicate_global_indices. 

### PR DESCRIPTION
**Pull request by dknez**
This just calls some of the debugging code that was commented out in MeshCommunication::assign_global_indices.

### CODE REVIEW

**Comment by dknez** [comment]
This provides the Hilbert index clash check in a separate function call, like @jwpeterson suggested.

**Comment by jwpeterson** [comment]
Looks good.  So this isn't automatically called (say in DEBUG mode or something) since it's pretty slow?

**Comment by dknez** [comment]
Yeah, it's too slow to call automatically, since it's O(N^2).

**Comment by roystgnr** [comment]
Doing a sort would get that down from O(N^2) to O(N log N), cheap enough for ```#ifdef DEBUG```

To be really useful we'd want to check more than just local against local indices, though, and IIRC our parallel sorting doesn't work when duplicates exist.

**Pull request merged**
