### PR TITLE
Mark virtual functions as such

### PR DESCRIPTION
**Pull request by jwpeterson**
Note that this should have no effect on the code, it is basically just documentation for humans.

### CODE REVIEW

**Comment by jwpeterson** [comment]
I don't guarantee that I found all of these... it is kind of a hard thing to grep for.

**Review by roystgnr — APPROVED** [review]
Fine by me.  I like to hope that most of our users would be able to figure things out from `override` alone, though.

**Comment by dschwen** [comment]
Isn't virtual completely redundant to override? We've had the discussion on MOOSE PRs and .. let's say opinions still differ.

**Comment by jwpeterson** [comment]
Yeah, this is in response to a specific mailing list question where a user didn't realize that override -> virtual. Also we are like 98% consistent in labeling everything virtual so I'd rather fix the remaining 2% than go the other direction.

**Pull request merged**
