### PR TITLE
Upgrade netcdf version to 4.9.2

### LINKED ISSUE #3390: current netcdf tests in contrib incompatible with hdf5 version 1.12
I discovered this sad fact this week when running `make check`. https://github.com/Unidata/netcdf-c/commit/9f9b125028b28d8e94f2c990c8d92a7df76fde78 appears to have fixed that issue.

In discussion with @roystgnr we may migrate to having a netcdf submodule but which points to a fork of ours which includes bootstrapped material

### PR DESCRIPTION
**Pull request by lindsayad**
Closes #3390 and allows me to run `make check` on my system

### CODE REVIEW

**Comment by lindsayad** [comment]
Hmm got a lot of extra unnecessary files in here (including the tar ball) ...

**Comment by lindsayad** [comment]
Must wait on https://github.com/idaholab/moose/pull/25178 to make it through to the conda channels

**Review by roystgnr — APPROVED** [review]
Looks good to me.

What versions are we ending up with in the CI recipes?  I can't imagine we're getting coverage for both without changing recipes to ensure that?

**Comment by lindsayad** [comment]
In CIVET we are getting the old version, 4.6.2. Once the PETSc update goes through and the PETSc hdf5 is built with zlib, then maybe we can switch some recipes over to 4.9.2 (the submodule)

**Pull request merged**
