### PR TITLE
Poly2TriTriangulator refinement fixes

### PR DESCRIPTION
**Pull request by roystgnr**
This fixes some failure cases where triangulation refinement runs away creating sliver elements ... and it fixes more failure cases where it turns out we can't trust poly2tri to give us a true Delaunay triangulation.

The more careful behavior at boundaries will probably force us to regold tests in MOOSE.  Here's hoping it doesn't force too much of that further downstream.

This fixes https://github.com/idaholab/moose/issues/24474 for me.

### CODE REVIEW

**Comment by roystgnr** [comment]
The compiler warnings are easy to fix, but looks like we have at least three regoldings coming in MOOSE.

**Comment by olinwc** [comment]
I'm pulling this branch to work on some of my test cases, will report the results once I have them

**Comment by olinwc** [comment]
@roystgnr Devel mode reactor compiled with this branch I was able to mesh my gHPMR_2d_core_v33.i without any assertions or errors.

**Comment by olinwc** [comment]
Unfortunately my MHTGR mesh seems to error out, but it does that with the current version of moose/libmesh, so I need to troubleshoot that.

**Comment by olinwc** [comment]
Ok I was able to run my MHTGR mesh with this branch also. Error was being caused by a boundary I defined being renamed during stitching and me trying to use the old name. Works fine now.

**Comment by olinwc** [comment]
@roystgnr Decided to run gHPMR_2d_core_v33.i in parallel and it just hangs or is just taking a lot longer, in serial it runs in 15 seconds, with four processors I've been waiting for several minutes just getting

```
Setting Up....................
```

**Comment by roystgnr** [comment]
In serial even in devel mode it runs in 9 seconds for me, on 4 procs I get segfaults or assertion failures (boy I love parallel race conditions!) after more like 40 seconds.

Looking into it now.

**Comment by roystgnr** [comment]
2 procs is enough to trigger failure too; hooray for small blessings.

**Comment by roystgnr** [comment]
Whoa.  The failure is coming from `LaplaceMeshSmoother`??

**Comment by roystgnr** [comment]
One failure was coming from `LaplaceMeshSmoother`.  If I turn off smoothing in XYDelaunay then I see assertion failures from ... `Partitioner::partition_unpartitioned_elements`?  Weirder and weirder.  There's got to be some underlying failure elsewhere.

**Comment by roystgnr** [comment]
Okay; the underlying failure is in Poly2TriTriangulator.  I've found one obvious bug where it can get out of sync in parallel; still hunting for others.

@lindsayad wrote [an ironic three hours ago](https://github.com/idaholab/moose/pull/24619#issuecomment-1582907802) that "There may be some algorithms that require iterating in sync across processes for which you do have to have a deterministic ordering and I think we have those in the places we need them", but what he forgot is that I'm always writing **new** bugs to replace the old ones!

**Comment by lindsayad** [comment]
Hahaha how timely. We have so many development intersections and cross-references these days. This from @olinwc included:

> Error was being caused by a boundary I defined being renamed during stitching and me trying to use the old name.

**Comment by roystgnr** [comment]
@olinwc - give it a try now?

**Comment by olinwc** [comment]
Since this is my personal Github I don't get notified on my work email... Trying this now!

**Comment by olinwc** [comment]
So good news, `gHPMR_2d_core_v33.i` did run on 4 cores, it was slower, but it's also a small problem so that might just be expected

4 cores:
```
Finished Setting Up                                                                      [ 75.41 s] [  521 MB]
```
Serial:
```
Finished Setting Up                                                                      [ 14.61 s] [  210 MB]
```

Will try MHTGR next

**Comment by olinwc** [comment]
MHTGR

Serial:
```
Finished Setting Up                                    [143.10 s] [ 1814 MB]
```
4 Cores:
```
Finished Setting Up                                    [790.19 s] [ 3770 MB]
```
No more hanging!

**Comment by roystgnr** [comment]
> and performance fixes can wait.

I say, right before I dive into the code to look for fixes.

With a swath of low-hanging microoptimizations, I managed to make things faster by ... a fraction of a second?  So that's not the way to go.

But during the process I couldn't help but notice that gHPMR_2d_core_v33.i is triggering FOUR HUNDRED AND NINETEEN repartitionings, which for a mesh with no extrusions and no refinements is probably approximately four hundred eighteen too many.  We've long had vague plans to make the `is_prepared()`/`prepare_for_use()` system more fine-grained, but this seems to be the perfect motivational and test case; it's triggering an order of magnitude more overkill than I was imagining.

**Comment by lindsayad** [comment]
That is truly brutal

**Comment by olinwc** [comment]
@roystgnr That parallel behavior was all running with `METHOD=devel`

I'm also on a 2013 Mac Pro running locally, so people with more up-to-date local machines, like the new M1 Macs, are a lot faster per core.

**Comment by roystgnr** [comment]
Rebased on `master`, to kick off new CI now that the tests to regold are temporarily disabled.

**Comment by roystgnr** [comment]
That timeout on the `Test MOOSE debug` modules worries me.  Looked like the timing-out test was unrelated, so I just kicked it, but I'm also going to see if I get any weirdness in a local dbg modules `make test`.

**Pull request merged**
