### PR TITLE
Updates to InfFEBase::build_elem()

### PR DESCRIPTION
**Pull request by jwpeterson**
* Preserve const-ness of input in the output
* Don't hand back allocated dumb pointer to the user
* InfFE::base_elem should be treated as const
* Update docs including the need for a const_cast workaround in debug mode.

### CODE REVIEW

**Comment by roystgnr** [comment]
Solid improvement IMHO but let's wait to see what @BalticPinguin thinks before we merge.

**Comment by jwpeterson** [comment]
OK, thanks for reviewing. One thing that I think could be improved is for `Elem::build_side_ptr()` to set a "not invalid" `id()` on the side proxy element that it builds. This would allow us to avoid the `const_cast` that is in this PR. But, after thinking about that idea for a bit, it's not clear exactly what that side id should be. We could set it to the "parent" element's id or 0, but it's possible this duplication of ids would then lead to other issues...

A possibly simpler fix is to make it so that `DofObject::id()` does not throw an exception in debug (or any) mode. This seems safer overall to me, because it avoids the issue where you are already throwing an exception and in the course of trying to print information about the error (as in `inverse_map()`) you go to print the `id()` of the element causing the error, and this *also* throws, leading to an immediate program termination.

**Comment by roystgnr** [comment]
We use id() so often as a key in map (and worse, vector) lookups, and in the past I've really liked the ability to catch invalid_id errors there with an exception rather than a segfault...  but I guess we catch the map case with libmesh_map_find now, and any remaining instances of the vector case (damn ErrorVector) ought to be deprecated for the sake of efficiency in distributed mesh runs ... so yeah, I'd be happy to see that assertion removed.  Sorry I didn't do it *last* time this problem came up, now that I think about it.

**Comment by jwpeterson** [comment]
> so yeah, I'd be happy to see that assertion removed.

OK, great. I'll just tack that change on to this PR and then I can merge it without any `const_cast`.

**Review by BalticPinguin — APPROVED** [review]
This looks all fine to me.

**Pull request merged**
