### PR TITLE
Bugfix in rb_construction_base.C

### PR DESCRIPTION
**Pull request by dknez**
Previously the index of n_training_samples_per_param was going out of bounds.

### CODE REVIEW

**Comment by roystgnr** [comment]
Reminder: whenever we merge this, we ought to change one of the Civet recipes (Test debug?  Minimum gcc version debug?) to use --enable-glibcxx-debugging so we don't have a regression of this type again.

**Comment by jwpeterson** [comment]
> Reminder: whenever we merge this, we ought to change one of the Civet recipes (Test debug? Minimum gcc version debug?)

I'd prefer not to change an existing recipe, since that disables the dbg-mode unit tests from running, which are also useful for catching asserts before code gets merged. Maybe add a new optional "glibcxx" CIVET recipe?

**Comment by roystgnr** [comment]
My hope was that if we changed one debug recipe (to get GLIBCXX_DEBUG coverage on the examples) and left the other unchanged (to get dbg coverage on the unit tests) that'd give us a strict increase in coverage without increasing CI expense.

**Comment by jwpeterson** [comment]
> that'd give us a strict increase in coverage without increasing CI expense.

OK, sounds good. Does Test Debug actually use GCC? If not, then I guess we should go with Min gcc.

**Pull request merged**
