### PR TITLE
Fix mis-branching in CouplingMatrix iterator++

### PR DESCRIPTION
**Pull request by roystgnr**
This was causing a *huge* performance penalty in cases where we had
many variables.

Hopefully https://github.com/idaholab/moose/issues/9480 will be fully
resolved by the fix.  I see orders of magnitude speedup in our test
case.

Assuming this doesn't break a hundred test cases (whether by exposing an underlying bug, or by failing to match a regression standard generated with the broken version, although I don't think either is likely to happen), @dschwen would you mind checking the asymptotic behavior again?  There's still some slight optimizations that might be possible here, but I think I've caught the entire O(N^3) mistake.

### CODE REVIEW

**Comment by roystgnr** [comment]
Breaking unit tests is never a good sign.  Trying to replicate.

**Comment by jwpeterson** [comment]
@roystgnr is this still in "do not merge" condition? Looks like it's passing all the tests now... does it also still fix the original performance regression?

**Comment by roystgnr** [comment]
Nope.  I'm back in debugging mode at the moment, testing out Plan C.

**Comment by roystgnr** [comment]
I'm hoping to have it in working order by this afternoon.  I assume you're chomping at the bit to get this included in the next MOOSE libMesh update?

**Comment by jwpeterson** [comment]
> I assume you're chomping at the bit to get this included in the next MOOSE libMesh update?

It would be nice, but we are also mainly waiting for the CheckpointIO changes to be un-reverted (re-reverted?) so you're not holding anything up.

**Comment by roystgnr** [comment]
Ok, only seeing 1 more OOM speedup with the newest version, but I think I've got it correct now.

**Comment by roystgnr** [comment]
Hmmm... I made the mistake of doing those last timings with more than just this PR; there's also another minor optimization in my local checkout (so 1 OOM might be an overestimate) and there's some thick cerr-debugging (so 1OOM might be an underestimate).  Regardless, I think this PR alone fixes the ridiculously awful asymptotic complexity bug and should be merged ASAP if it passes tests.  If my other optimization makes a constant-factor improvement on top of that then I'll put it in a separate PR.

There's a possibility of false positive test failures, if one of the side effects of the previous iterator behavior (overfilling sparsity patterns) happens to have been masking an application bug (declaring a too-sparse CouplingMatrix and then attempting to set entries outside it), so normally I'd want to turn on all the MOOSE app tests right now, but if there's a general MOOSE libMesh update coming soon then we can just wait for that.

**Comment by roystgnr** [comment]
Yup; most of my timing was stderr output.  :-P  I see about 2.5 OOM speedup now.

**Comment by dschwen** [comment]
Pulling the branch now

**Comment by roystgnr** [comment]
Actually, that looks like it might possibly be N^2 log(N)??  That might actually be the best we can do, if it is.  I'll put up my last optimization, though, which may at least shave log(N) off the scalar case.

**Comment by YaqiWang** [comment]
I am lazy to check, has this been merged into moose libmesh submodule?

**Comment by roystgnr** [comment]
Went in via https://github.com/idaholab/moose/pull/10740, yes.

**Pull request merged**
