### PR TITLE
If starting the nonlinear solve with a really good initial guess, we …

### PR DESCRIPTION
**Pull request by vikramvgarg**
…dont want to set an absurd linear tolerance

### CODE REVIEW

**Comment by vikramvgarg** [comment]
All tests passed on make check.

**Comment by jwpeterson** [comment]
@vikramvgarg I think we are waiting on you to confirm that this indeed works for the specific situation you coded it to address, this line of code is most likely not exercised by any of the existing examples in libMesh...

**Comment by vikramvgarg** [comment]
Yeah, still testing that.

**Comment by jwpeterson** [comment]
OK, thanks.

**Comment by roystgnr** [comment]
It works correctly.  Not quite as *well* as I'd hoped (it requires the user to set a sane absolute_residual_tolerance even if they were previously relying on relative tolerances, and the safety factor is definitely necessary but still leads to some oversolving) but it's better than we had before on Vikram's solved-restart case.

**Pull request merged**
