### PR TITLE
Fixed compiling errors against  with PETSc-3.11.x

### LINKED ISSUE #2146: Compiling errors with PETSc-3.11.x
There is an API change in PETSc-3.11.x.

`DMCreateSubDM_Section_Private` was changed to `DMCreateSectionSubDM`

It is a good change actually since the API is public now.

### PR DESCRIPTION
**Pull request by fdkong**
Closes #2146

### CODE REVIEW

**Comment by fdkong** [comment]
@jwpeterson  Could you take a look at this?

**Comment by jwpeterson** [comment]
BTW, I attached a test with PETSc master but we don't run that often so I'm not sure whether it actually passes.

**Comment by fdkong** [comment]
> BTW, I attached a test with PETSc master but we don't run that often so I'm not sure whether it actually passes.

It is good to check. If it does not work, I will try to fix it.

**Comment by jwpeterson** [comment]
@fdkong, looks like the new code compiles fine but there are some failing MOOSE tests... they seem to be unrelated to your specific change, but they could be caused by a new PETSc... I'd be OK with merging this as-is, unless you want me to hold off for some reason.

**Comment by fdkong** [comment]
> @fdkong, looks like the new code compiles fine but there are some failing MOOSE tests... they seem to be unrelated to your specific change, but they could be caused by a new PETSc... I'd be OK with merging this as-is, unless you want me to hold off for some reason.

It is better to merge it in as-is, and the falling is unrelated to this PR. I will try to fix on the moose side.  I need this PR in before I can do some tests in MOOSE.

**Comment by fdkong** [comment]
Thanks, @jwpeterson

**Pull request merged**
