### PR TITLE
Fixes for assorted odd build configurations

### PR DESCRIPTION
**Pull request by roystgnr**
PECOS finally has BuildBot up and running again!

This means that we can finally resume automatic testing of all the little fiddly configuration options that the main developers don't commonly use.  In particular I'm looking forward to explaining that the answer to "does --enable-complex work" is "yes, at least as of last night", rather than "yes, at least if you use a git hash from shortly after the last time someone complained about --enable-complex not working".

This PR is still a work in progress; I'll take off the "do not merge" tag once everything in our current set of test configurations builds cleanly again.

There are a lot of warnings to be fixed as well; I'll leave those in a separate PR.  My hope is that the fixes for even corner-case errors can get merged down to 1.0, but IMHO that's not worth it for fixes for warnings.

### CODE REVIEW

**Comment by roystgnr** [comment]
That should be it for today.  I'd like to merge this afternoon so BuildBot can take a crack again overnight.

**Comment by jwpeterson** [comment]
Does buildbot have any GitHub integration?  We could have it test PRs like Civet...

**Comment by roystgnr** [comment]
It does, but we don't have any examples of it in our old config files (which may have predated it...) so I'd rather not start testing it on libMesh.  I'll pick one of our other GitHub hosted projects and give it a try.

**Comment by jwpeterson** [comment]
Looks like everything here can go on 1.0.0?  I'll do that now...

**Comment by roystgnr** [comment]
Definitely.  There'll be another swath of fixes to come later, though.

**Pull request merged**
