### PR TITLE
Hopefully fix Metis bug originally introduced with SubdomainPartitioner

### PR DESCRIPTION
**Pull request by jwpeterson**
This fix is very relatively simple, and I have not tested it with all the cases that were segfaulting previously, but it does reliably pass adaptivity_ex2 on 4 processors which was one of the cases @roystgnr had reported not working.

### CODE REVIEW

**Comment by pbauman** [comment]
Oh, cool, I'll try this out late this afternoon. I was getting segfaults on an AMR case I was running before I left for SIAM NC. Hopefully this will fix it.

**Comment by roystgnr** [comment]
Ah!  That looks like it could be it.  That's both reassuring and disappointing.  I was kind of hoping we had exposed some pre-existing METIS API usage bug, so fixing it would also fix the crummy results METIS gives us on occasion.

@pbauman, the bug existed for a little over a week before we reverted, and had a high probability of crashing during AMR repartitioning, so yeah, if you pulled at the wrong time, that could have been it.

**Comment by roystgnr** [comment]
:+1: when you're ready

**Comment by roystgnr** [comment]
Oh, wait

**Comment by roystgnr** [comment]
Could you reorder those last two commits, or merge them?  We might as well not have a gap in between uncommenting the buggy code and fixing it.

**Comment by jwpeterson** [comment]
> Could you reorder those last two commits, or merge them?

I will squash them, I was initially testing with 8b2fd9b to confirm that I could reproduce the bug, but it does not need to be in the final history.

**Comment by jwpeterson** [comment]
This patch also seems to work for Cody's AMR grain growth example:
```
cd $MOOSE_DIR/modules/phase_field/examples/grain_growth/grain_growth_2D_graintracker.i
mpiexec -n 12 ../../phase_field-opt -i grain_growth_2D_graintracker.i
```
that was crashing on previously, so I'm fairly optimistic it's the right fix.

**Comment by jwpeterson** [comment]
By the way @roystgnr, I cherry-picked your initial fix (439f48e) onto the v1.2.0 branch so the release would not have the original bug, but if this new fix works, I'd like to also cherry-pick it onto v1.2.0. On the other hand, I could just leave it alone depending on your preference...

**Comment by roystgnr** [comment]
No, let's definitely cherry-pick this on too.

**Pull request merged**
