### PR TITLE
Update TIMPI and MetaPhysicL submodules

### PR DESCRIPTION
**Pull request by lindsayad**
- Update to new DualNumber template signature
- Update StandardType specializations to use `is_fixed_type` static member API

### CODE REVIEW

**Comment by roystgnr** [comment]
Well that's fun.  Wonder why it didn't scream about the incompatibility on non-Mac MOOSE builds.

**Comment by lindsayad** [comment]
Looks like it happily fails on the Linux boxes as well (as one would hope). Just had to give it time. We knew this was an API breaking change. For this one to go in, we're just going to have to live with the failures (until I get the libMesh update into MOOSE)

**Comment by roystgnr** [comment]
I hate non-overlapping updates, even *aside* from the loss of CI.  The problem here is forward declarations, no?  Could we first update MetaPhysicL to the earliest version with dualnumber_forward.h, then update MOOSE to use that header for forward declarations, then do the final update?

**Comment by lindsayad** [comment]
I should have thought more critically about this at the time...The third template parameter and `dualnumber_forward.h` were introduced in the same commit. We could revert that commit, and then I can split the commit into two.

**Comment by lindsayad** [comment]
Actually, the least painful would be for me to to do a `MetaPhysicL` version check and if `MAJOR_VERSION < 1`, then use the existing forward declaration, else include `metaphysicl/dualnumber_forward.h`

**Comment by lindsayad** [comment]
Well, this shows that my current way of doing `--with-future-timpi-dir` isn't very fail-safe... Going to have to revert https://github.com/idaholab/civet_recipes/pull/1620 while I think about the right thing to do. Is it a crazy idea to create a libtimpi.so which points to the most optimized extension of TIMPI that gets built?

**Comment by lindsayad** [comment]
Looks like this is ready to review/merge

**Comment by roystgnr** [comment]
My "only configures when I pass in --enable-entrails-of-a-chicken" system is now autodetecting things perfectly, thank you!

**Comment by lindsayad** [comment]
That’s cool to hear!

**Pull request merged**
