### PR TITLE
TESTED fix for PeriodicBoundaries where elements have multiple sides on boundary

### PR DESCRIPTION
**Pull request by roystgnr**
I should know better than to submit PRs for new code I don't yet have test coverage for.

This includes the attempted bugfix from #2687, but with the fix fixed, plus a new unit test that revealed the inadequacies of the pre-fixed fix.

Thanks again to @arovinelli, this time for the 2D mesh that made testing here easier.  Hopefully his 3D cases will work as well.

The unit test is factored in such a way that we'll be able to add test coverage for other elements pretty easily, but I'm throwing it up here with just the LAGRANGE case so that he can take a crack at it sooner.

### CODE REVIEW

**Comment by roystgnr** [comment]
Looks like my BUILT_SOURCES tweaks didn't work here?  Let me see if I can reproduce that; if not then I'll just go back to the .linkstamp stuff.

**Comment by roystgnr** [comment]
Okay - this passes CI, and the unit test fails for me (with 0.04 error vs 1e-11 tolerance) if I remove the bugfix commits, so the bugfix is definitely fixing *some* bug, so I'm merging.  I'm hoping this fixes the 3D case @arovinelli hit too; if not then we'll get a fix for that and a unit test to reproduce that in a later PR.

**Comment by arovinelli** [comment]
This PR fixed my issue. Now I have the correct periodic field everywhere.
@roystgnr thanks a lot for taking care of this so quickly.

**Comment by lindsayad** [comment]
7be1c82989d8c2257 broke MOOSE's example 4 trapezoidal test.

Looks like we're hitting a remote elem now. Stack trace:
```
#0  0x00007faa5eae2c6f in wait4 () from /usr/lib/x86_64-linux-gnu/libc.so.6
#1  0x00007faa5ea520e7 in ?? () from /usr/lib/x86_64-linux-gnu/libc.so.6
#2  0x00007faa5f6b7da2 in (anonymous namespace)::gdb_backtrace (out_stream=...) at /usr/include/c++/9/bits/basic_string.h:2300
#3  libMesh::print_trace (out_stream=...) at /home/lindad/projects2/moose/scripts/../libmesh/src/base/print_trace.C:209
#4  0x00007faa5f6b3d5c in libMesh::MacroFunctions::report_error (file=0x7faa60405a48 "./include/libmesh/remote_elem.h", line=120, date=0x7faa603cf007 "nodate", time=0x7faa603cf000 "notime") at /home/lindad/projects2/moose/scripts/../libmesh/src/base/libmesh_common.C:85
#5  0x00007faa5fa06aab in libMesh::RemoteElem::n_nodes (this=<optimized out>) at ./include/libmesh/remote_elem.h:120
#6  0x00007faa5f6412c5 in libMesh::DofMap::dof_indices (this=this@entry=0x563f31bf7f40, elem=elem@entry=0x563f312720e0, di=std::vector of length 0, capacity 0, vn=vn@entry=0, p_level=0, p_level@entry=-12345) at /usr/include/c++/9/bits/stl_tree.h:1018
#7  0x00007faa5f80b579 in libMesh::FEGenericBase<double>::compute_periodic_constraints (constraints=..., dof_map=..., boundaries=..., mesh=..., point_locator=point_locator@entry=0x563f31f05d20, variable_number=0, elem=0x563f31e30840) at /usr/include/c++/9/bits/unique_ptr.h:360
#8  0x00007faa5f8b0d39 in libMesh::FEInterface::compute_periodic_constraints (constraints=..., dof_map=..., boundaries=..., mesh=..., point_locator=point_locator@entry=0x563f31f05d20, variable_number=<optimized out>, elem=0x563f31e30840) at /home/lindad/projects2/moose/scripts/../libmesh/src/fe/fe_interface.C:2166
#9  0x00007faa5f67ac77 in (anonymous namespace)::ComputeConstraints::operator() (range=..., this=0x7ffd0cd74dc0) at /home/lindad/projects2/moose/scripts/../libmesh/src/base/dof_map_constraints.C:115
#10 libMesh::Threads::parallel_for<libMesh::StoredRange<libMesh::MeshBase::const_element_iterator, libMesh::Elem const*>, (anonymous namespace)::ComputeConstraints> (body=..., range=...) at ./include/libmesh/threads_pthread.h:277
#11 libMesh::DofMap::create_dof_constraints (this=0x563f31bf7f40, mesh=..., time=0) at /home/lindad/projects2/moose/scripts/../libmesh/src/base/dof_map_constraints.C:1839
#12 0x00007faa5ff11338 in libMesh::System::reinit_constraints (this=0x563f31e8e0f0) at /usr/include/c++/9/bits/unique_ptr.h:360
#13 0x00007faa5ff1d916 in libMesh::System::init_data (this=0x563f31e8e0f0) at /home/lindad/projects2/moose/scripts/../libmesh/src/systems/system.C:279
#14 0x00007faa5ff1dcc3 in libMesh::System::init (this=0x563f31e8e0f0) at /home/lindad/projects2/moose/scripts/../libmesh/src/systems/system.C:254
#15 0x00007faa5fed628d in libMesh::EquationSystems::init (this=this@entry=0x563f31e71b10) at ./include/libmesh/system.h:2210
#16 0x00007faa610a7f67 in FEProblemBase::init (this=0x563f31e714d0) at /home/lindad/projects2/moose/framework/src/problems/FEProblemBase.C:4874
#17 0x00007faa6188800b in Action::timedAct (this=0x563f31dd73c0) at /home/lindad/projects2/moose/framework/src/actions/Action.C:93
#18 0x00007faa618956d9 in ActionWarehouse::executeActionsWithAction (this=this@entry=0x563f31c5a168, task="init_problem") at /home/lindad/projects2/moose/framework/src/actions/ActionWarehouse.C:378
#19 0x00007faa618976ef in ActionWarehouse::executeAllActions (this=this@entry=0x563f31c5a168) at /home/lindad/projects2/moose/framework/src/actions/ActionWarehouse.C:339
#20 0x00007faa61d1e258 in MooseApp::runInputFile (this=0x563f31c59390) at /home/lindad/projects2/moose/framework/src/base/MooseApp.C:892
#21 0x00007faa61d1b18d in MooseApp::run (this=0x563f31c59390) at /home/lindad/projects2/moose/framework/src/base/MooseApp.C:1057
#22 0x0000563f3079e39b in main (argc=3, argv=0x7ffd0cd757f8) at /usr/include/c++/9/bits/shared_ptr_base.h:1020
[Inferior 1 (process 3016595) detached]
[0] ./include/libmesh/remote_elem.h, line 120, compiled nodate at notime
                                                              [ 12.79 s]


*** ERROR ***
Error: not implemented!
```

**Comment by lindsayad** [comment]
Ok, I figured out why the MOOSE example has stopped working. The reason is simply because the transformed point simply doesn't lie on the paired boundary. It's a little bit off, and that's enough for `contains_point` to return `false`. The x coordinate aligns perfectly, but the y-position is just a bit wrong. However `trapezoid.e` got generated, it seems like it just didn't have its transform functions quite right:
```
(gdb) p neigh_side_proxy->centroid()
.$76 = {<libMesh::TypeVector<double>> = {_coords = {-2.329545454545455, 4.0347727272727276, 0}}, <No data fields>}
(gdb) p p
$77 = {<libMesh::TypeVector<double>> = {_coords = {-2.3295454545454541, 4.0348910858138627, 0}}, <No data fields>}
```
The `Point p` is indeed correctly mapped from the originating boundary point which was at (4.6590909090909, 0, 0).
```
In [13]: r * cos(2*pi/3)                                                                                                                                                                      
Out[13]: -2.329545454545454

In [14]: r * sin(2*pi/3)                                                                                                                                                                      
Out[14]: 4.034891085813863
```

**Comment by lindsayad** [comment]
It is weird that `git bisect` didn't get me to the correct commit :-(

**Comment by roystgnr** [comment]
> So I think I'm probably removing that MOOSE example test.

No way to fix the mesh?  I cringe at the thought of our PBC test coverage *decreasing*...

I'd also kind of like to keep the inaccurate mesh as an error test - ideally we should be dying with a clear error message in this situation, even in opt mode, but obviously "clear error message" isn't on the table, and now I'm worried about whether we're at least screaming *something* and dying in opt mode, rather than doing something horrific like trying to continue but with an incomplete periodic constraint equation set.

**Comment by lindsayad** [comment]
> No way to fix the mesh? I cringe at the thought of our PBC test coverage _decreasing_...

No. Whoever created the test didn't provide a `.jou` input file. I don't feel like trying to regenerate it by hand. I don't even have cubit on my workstation. We do have a very similar test in another directory that has a pi/3 rotation instead of 2pi/3 that apparently  has a clean mesh.

> I'd also kind of like to keep the inaccurate mesh as an error test - ideally we should be dying with a clear error message in this situation, even in opt mode, but obviously "clear error message" isn't on the table, and now I'm worried about whether we're at least screaming _something_ and dying in opt mode, rather than doing something horrific like trying to continue but with an incomplete periodic constraint equation set.

Yea I dunno. It seems like turning that `libmesh_assert_msg` at the end of `PeriodicBoundaries::neighbor` into a `libmesh_error_msg_if` could be pretty expensive?

**Comment by roystgnr** [comment]
> We do have a very similar test in another directory that has a pi/3 rotation instead of 2pi/3 that apparently has a clean mesh.

That ought to do, thanks for the reassurance.

> It seems like turning that libmesh_assert_msg at the end of PeriodicBoundaries::neighbor into a libmesh_error_msg_if could be pretty expensive?

Too expensive, I think, though I'd want to see a call graph to say for sure.

I'd guess we're probably at least safe from corrupted solutions thanks to the ```libmesh_not_implemented()``` RemoteElem virtual functions, though?  Even on a ReplicatedMesh if we skip that assert and plow forward we'll be returning remote_elem and so we'll be hitting an unimplemented virtual if we try to do anything with it.  And I guess that's good enough for me; as long as we don't just quietly return an incorrect solution, I can forgive not making it as easy as it should be for users to diagnose what went wrong.

**Comment by lindsayad** [comment]
> I'd guess we're probably at least safe from corrupted solutions thanks to the `libmesh_not_implemented()` RemoteElem virtual functions, though?

Yes, you're exactly right. That's what the failure was in opt mode for that MOOSE example.

**Pull request merged**
