### PR TITLE
OrderWrapper shim class to enable arbitrary FE orders

### PR DESCRIPTION
**Pull request by roystgnr**
Based 99% on the work @dknez did.

Obsoletes #824

This seems to get everything compiling and running sanely for me.

I'd like to get this merged soon if everyone is happy; I just discovered that we might have a use for specifying *negative* FE order as well; I need to be able to specify temporary p-coarsening via some less hackish code in order to fix a race condition in threaded constraint evaluation on hp-refined meshes.

### CODE REVIEW

**Comment by dknez** [comment]
Nice job getting that disambiguation in good shape, thanks! :)

**Comment by roystgnr** [comment]
I feel like there has to be a better standard way to do that in C++.

If not then I'm not happy with the standard.  In general it would be nice if instead of "Error: two overloads have equal precedence for this function call, so I don't know what to do", the compiler would at most say "Warning: two overloads have equal precedence for this function call, so I assume either will work just fine".  If I write a function to handle ```foo(Bar b, T t)```, and another to handle ```foo(T t, Qux q)```, then I promise, it's okay to call either one to handle ```foo(b,q)```!  If what I'd really written with that first overload was implicitly ```foo(Bar b, TButNotQux nq)```, then I'd have used SFINAE and made the type explicitly TButNotQux.

**Comment by roystgnr** [comment]
Ugh.  Not sure whether I missed that because I tested with a slightly older MOOSE build or because I only built in opt.

**Comment by roystgnr** [comment]
I'll merge this tomorrow unless there's objections.

**Comment by jwpeterson** [comment]
> I'll merge this tomorrow unless there's objections.

:+1:

**Pull request merged**
