### PR TITLE
Getpot::get_subsection_names()

### PR DESCRIPTION
**Pull request by roystgnr**
@pbauman, the ideal method to submit feature requests is via the issue tracker rather than via random comments in source code, but I eventually noticed this anyway:

https://github.com/grinsfem/grins/blob/f4c70889c59cd869d536b022a3c37cfeabea9178/src/common/src/builder_helper.C#L60

And at about the same time I hit a use case for the same feature, so here's my crack at it.

### CODE REVIEW

**Comment by pbauman** [comment]
Yeah, sorry for being lazy. Thanks for implementing it.

**Comment by roystgnr** [comment]
Thank me when I implement it *correctly*.  Still testing.

**Comment by roystgnr** [comment]
Wow; I didn't realize std::string::back() was C++11 only.  Good catch Civet.

**Comment by roystgnr** [comment]
In addition to passing unit tests this works as a drop-in replacement for the GRINS code.

**Pull request merged**
