### PR TITLE
Refinement early return

### PR DESCRIPTION
**Pull request by roystgnr**
Add a test to MeshRefinement::refine_and_coarsen_elements() to make sure we actually have something to refine or coarsen; if not then we can return early without first testing for level mismatches and testing for unrefined islands and so forth.

Also remove the probably-redundant call to make_flags_parallel_compatible(), except as a dbg-mode test; if you need it then you can call it manually, and if you don't then we shouldn't be wasting your time with it.

See https://github.com/idaholab/moose/pull/10025 for discussion.

### CODE REVIEW

**Comment by jessecarterMOOSE** [comment]
This speeds things up quite well. Thanks!

**Comment by jessecarterMOOSE** [comment]
I went ahead and closed idaholab/moose#10025 in favor of this PR. Your way is much cleaner.

**Comment by roystgnr** [comment]
Oh, of course I'm an idiot.

Even if we're not h-refining, we can't exit early unless we know we're not p-refining either.

We also need one sync between processors to handle distributed mesh cases where one processor sees refinement flags but another does not.

**Comment by jessecarterMOOSE** [comment]
Ah, that didn't register because I'm not using p-adaptivity nor distributed mesh for my problem.

**Comment by roystgnr** [comment]
Okay, I've got fixes for every problem I can find (none of which ought to noticeably affect performance), but I'm going to do a bunch of rebasing and force push so that we don't end up with any intermediate broken commits.

**Comment by roystgnr** [comment]
Random side note: I honestly suspect we're going to see a small but noticeable speedup after moving to C++11 ranged-for loops.  There are a ton of places where we put a virtual function call into a loop stopping condition, not because we expect "n_children()" or"n_neighbors()" to change from iteration to iteration, but because that's just the most terse way to write those loops in C++98...

**Comment by jessecarterMOOSE** [comment]
👍 thanks!

**Pull request merged**
