### PR TITLE
Modifying data read in from an exodus file

### PR DESCRIPTION
**Pull request by dknez**
Added a function that copies data to a new ExodusII_IO object and optionally modifies the data, and writes it out to disk.

The motivation for this is that I want to be able to change some specific values in an exodus file and write out the modified data, without having to create an EquationSystems object in order to do the data modification.

### CODE REVIEW

**Comment by dknez** [comment]
Is that MOOSE XFEM failure related to this PR? I can't see how this would be related, since this PR is just an extra function which should not change any existing behavior.

**Comment by jwpeterson** [comment]
> Is that MOOSE XFEM failure related to this PR?

No, the reason for this failure is being discussed over in #1688. 

I don't have time right at this moment to look at this PR, but I would like to before it gets merged. Can you give me a day or two to look at it?

**Comment by dknez** [comment]
Sure, no problem.

**Comment by jwpeterson** [comment]
I have a few questions/concerns about this PR...

1. Is this really generally applicable enough that it should become part of the `ExodusII_IO` API? We were just lamenting [the other day](https://github.com/libMesh/libmesh/pull/1670) about how inconsistent the `ExodusII_IO` API is... this feels like one more tacked on thing.
1. Only the nodal vars are copied, any fundamental reason to omit elemental vars and global data?
1. It's not really clear to me from the documentation how to build up the fairly complicated `std::map<std::pair<int,std::string>, std::map<unsigned int,Real>>` data structure that must be passed in to the function.
1. This adds a capability to `ExodusII_IO` with no corresponding capability on the `Nemesis_IO` side... not strictly necessary for this PR to be merged, but I'd like to maintain more consistency between these two formats going forward.

**Comment by dknez** [comment]
I agree with your points.

An alternative solution would be to give public access to the helper object so that we can move this kind of functionality into app codes. What do you think about that?

**Comment by jwpeterson** [comment]
> An alternative solution would be to give public access to the helper object so that we can move this kind of functionality into app codes.

Yes I think we've been heading this way for quite some time, actually. People have wanted access to members on the helper at various times in the past, and instead of making the entire helper public, in the past we've just added more interfaces at the `ExodusII_IO` level. I think I'd be OK with this as long as we maintain the "Pimpl" idiom that is there currently, which allows us to avoid installing the Exodus library's internal headers.

**Comment by jwpeterson** [comment]
> I was thinking of just adding a "getter" to ExodusII_IO to access the helper object. Would that be OK with you? If so, I'll make a PR for that.

Seems like the right way to get started, yes.

**Comment by dknez** [comment]
@jwpeterson: I tried to add

```ExodusII_IO_Helper & get_exio_helper();```

to ExodusII_IO, but I can't use that from app codes because exodusII_io_helper.h is apparently not installed. Do you have any suggestion on what the best approach is here?

**Comment by jwpeterson** [comment]
> Do you have any suggestion on what the best approach is here?

This is controlled by the `include/rebuild_include_HEADERS.sh` script, where that file is added to a blacklist. If you remove it from there and then follow the instructions for [adding/removing source files](https://github.com/libMesh/libmesh/wiki/Adding-or-removing-source-files), it should get added to the list of headers to install.

**Comment by dknez** [comment]
Closing this, use #1695 instead.

**Pull request closed without merging**
