### PR TITLE
Added support for reading and writing NodeElems in ExodusII

### PR DESCRIPTION
**Pull request by dknez**
We use the ExodusII SPHERE element to represent NodeElems.

### CODE REVIEW

**Comment by dknez** [comment]
This works as I hoped. We can add NodeElems to a mesh and they're preserved on writing to and reading from Exodus files. Also, paraview handles Exodus SPHERE data with no problems, so that's convenient too.

**Comment by roystgnr** [comment]
:+1:, thanks!

Should we add read support too?  Exodus/Nemesis are lousy formats for restarts but it's nice to support what we can.

**Comment by dknez** [comment]
What change do you have in mind regarding read support?

I did the following test:
- I did a solve, and wrote out the mesh and solution data via equation_systems.write("solution_data.exo");
- I then made a new Mesh and EquationSystems by reading in the mesh exo file and solution_data.exo file.

This all worked fine, and it retained the NodeElem in the solution after reading in solution_data.exo. So it seems to me that this already does everything that is necessary, no?

**Comment by dknez** [comment]
Oh, oops, I thought equation_systems.write("solution_data.exo") would write an exodus file, but it writes an Xda file.

I'm not sure what code to change to make exodus restarts work?

**Comment by roystgnr** [comment]
I don't think anything should need to be changed to make the equation_systems part of a restart work; IIRC Exodus reads assume isoparametric Lagrange data.

But we probably ought to fix mesh.read("mesh.exo") in the case where mesh.exo has SPHERE elements in it.

**Comment by dknez** [comment]
> But we probably ought to fix mesh.read("mesh.exo") in the case where mesh.exo has SPHERE elements in it.

That already works, I've confirmed that with a test case.

**Comment by roystgnr** [comment]
Ready to merge, then?

**Comment by dknez** [comment]
Yep. I'll do it.

**Pull request merged**
