### PR TITLE
Add an interface for passing the transpose nullspace to PETSc

### PR DESCRIPTION
**Pull request by snschune**

### CODE REVIEW

**Comment by snschune** [comment]
I think this is all I need to do, but I gotta test it with Moose.

**Comment by jwpeterson** [comment]
:+1: although I'd prefer the underscored name `transpose_nullspace` and changing the near nullspace stuff `near_nullspace`, but the latter is already part of the public interface of `NonlinearSolver`...

**Comment by snschune** [comment]
>  although I'd prefer the underscored name transpose_nullspace and changing the near nullspace stuff to near_nullspace, but the latter is already part of the public interface of NonlinearSolver...

@jwpeterson  do you want this change?

**Comment by jwpeterson** [comment]
> @jwpeterson do you want this change?

I'd like to at least name the new one with an underscore.  If you make that change, I'll merge this, then it can be tested in your other MOOSE PR.

**Comment by snschune** [comment]
@jwpeterson does this look ok to you?

**Comment by jwpeterson** [comment]
Thanks!

**Comment by snschune** [comment]
Thanks.

**Comment by anilkunwar** [comment]
Hi All,
Is the libmesh compilation affected by this change as in this?
https://groups.google.com/forum/#!topic/moose-users/lV-fOw1i06I

Yours Sincerely,
Anil Kunwar

**Comment by jwpeterson** [comment]
@anilkunwar Yes, please don't start a second thread here, the one you already started on the moose users mailing list is sufficient.

**Pull request merged**
