### PR TITLE
Only run testCoreformGeom unit tests if PETSc is enabled and new enough

### PR DESCRIPTION
**Pull request by jwpeterson**
Refs #3803

### CODE REVIEW

**Comment by roystgnr** [comment]
Looks like we're missing the header that includes that macro?  (although we're getting it indirectly under most builds)

**Comment by roystgnr** [comment]
Thanks for catching this, and IMHO this is the right fix.  This is new enough stuff that I don't care about supporting runtime incompatibilities with old PETSc.

**Comment by jwpeterson** [comment]
Any idea what's going on with the failing MOOSE tests?
```
   ERROR misc/signal_handler.test_signal_parallel_recover FAILED (unknown dependency) [min_cpus=3]
   ERROR misc/signal_handler.test_signal_recover_debug FAILED (unknown dependency) [METHOD!=DBG]
   ERROR misc/signal_handler.test_signal_recover FAILED (unknown dependency)
```

**Review by roystgnr — APPROVED** [review]

**Comment by roystgnr** [comment]
Wait, I think I know what MOOSE PR would have triggered this.

**Comment by roystgnr** [comment]
https://github.com/idaholab/moose/pull/26588 went in 5 days ago; I'm betting that's the one.

**Comment by jwpeterson** [comment]
The remaining failures all seem to be unrelated to this change so I will merge now.

**Pull request merged**
