### PR TITLE
Bugfix in rb_data_deserialization.C

### PR DESCRIPTION
**Pull request by dknez**
Need to close the file descriptor once we're finised with it.

### CODE REVIEW

**Comment by roystgnr** [comment]
The capnp APIs only take raw file descriptors, not fstream or anything, so we can't use RAII here?

**Comment by dknez** [comment]
We followed example code such as on here:
https://capnproto.org/cxx.html#example-usage
See after "You might write code like".

They pass "int fd" to the functions, so I guess we need to use raw file descriptors.

**Comment by jwpeterson** [comment]
I think if this became a maintenance issue in the future, you could always write a simple custom wrapping class that calls `close(fd)` in its destructor... unfortunately there [doesn't appear to be a portable way of creating a std filestream from a file descriptor](https://stackoverflow.com/questions/2746168/how-to-construct-a-c-fstream-from-a-posix-file-descriptor).

**Comment by jwpeterson** [comment]
We don't have any libmesh PR testing with capnproto enabled, so I'm just going to merge this.

**Pull request merged**
