### PR TITLE
Fixes to find_nodal_neighbors() for 1D elements

### PR DESCRIPTION
**Pull request by jwpeterson**
The edge-based algorithm we were using didn't work with 1D elements, because they don't have edges.

### CODE REVIEW

**Comment by roystgnr** [comment]
Huh.  So how *were* 1D elements working before?

**Comment by jwpeterson** [comment]
They weren't... it was just returning zero neighbors for all the nodes.  MeshTools::find_nodal_neighbors() isn't called that much in 1D I guess.

**Comment by roystgnr** [comment]
If beggars can be choosers, I'd say add a unit test.  :+1: regardless.

**Comment by jwpeterson** [comment]
> On May 22, 2015, at 11:26 AM, roystgnr <notifications@github.com> wrote:
> 
> If beggars can be choosers, I'd say add a unit test.   regardless.
> 

I'll add the test case I used to develop it...
.

**Pull request merged**
