### PR TITLE
Add toggle for HDF5 for nemesis output

### PR DESCRIPTION
**Pull request by loganharbour**
FYI @MengnanLi91

### CODE REVIEW

**Review by roystgnr — APPROVED** [review]

**Comment by loganharbour** [comment]
Can I get a merge? I think you're used to approving and leaving be for people that have write :-)

**Comment by roystgnr** [comment]
Just kicked CI myself, and already it's saying Coverage failed.  Shouldn't it be pending until the gcov recipes run before it decides that?

**Comment by loganharbour** [comment]
Even better, you invalidated the wrong event:

https://civet.inl.gov/pr/17922/

If you look, the most recent event is all green. The changes just didn't push to GH.

**Comment by loganharbour** [comment]
> Just kicked CI myself, and already it's saying Coverage failed. Shouldn't it be pending until the gcov recipes run before it decides that?

This is because you invalidated old recipes. Coverage will be pending until its dependencies are met. When you invalidate everything, like you did, it sends a fail message for all events. Then, as they run they repopulate. But because coverage doesn't actually run until it's ready... it stays as failed until it runs.

**Review by jwpeterson — APPROVED** [review]

**Pull request merged**
