### PR TITLE
More PETSc 3.17 compatibility

### PR DESCRIPTION
**Pull request by roystgnr**
I'm not sure how much test coverage we have on these two files, but this was what it took to get compilation working for me.

### CODE REVIEW

**Comment by pbauman** [comment]
> This reminds me... we should consider whether we can remove the petscdmlibmeshimpl.C code, as I think it has been superseded by the code in petsc_dm_wrapper.h, which is also what the multigrid preconditioner/solver stuff is implemented on top of.

The MOOSE folks would be the ones to ask, I think. I'm not sure if there is additional functionality in the petscdmlibmeshimpl.C code or not. If they aren't using it, then I would suggest it be removed.

**Comment by jwpeterson** [comment]
@fdkong do you know whether MOOSE is using petscdmlibmeshimpl.C code internally? I think not... it was something added to libmesh a while ago by Dmitry.

**Comment by fdkong** [comment]
I think we do not really use that in moose

**Comment by jwpeterson** [comment]
OK, thanks for letting us know. I think it is only used in misc_ex7, which is a variational inequality solver. So I guess we'd have to either be willing to drop that example or somehow refactor it to use the pestc_dm_wrapper.h approach (not sure whether this is possible).

**Comment by fdkong** [comment]
It would be a good idea to check if we lose any capability or not before we remove this code

**Pull request merged**
