### PR TITLE
Fix recent unit tests with --enable-complex

### PR DESCRIPTION
**Pull request by roystgnr**
Apparently it's time for me to give up on getting BuildBot SingleBranchScheduler to work properly with github, and just reenable our Periodic scheduler for all the non-default configuration tests.

### CODE REVIEW

**Comment by jwpeterson** [comment]
Can we do a complex-enabled build sans PETSc?  It would be pretty easy for us to set up a complex target for moosebuild if we didn't also have to worry about having a complex-enabled PETSc in our binary package that no one would actually use.

**Comment by roystgnr** [comment]
Hmm...  We couldn't originally.  I'll bet Eigen supports complex Numbers, though.  I'll try it out.

**Comment by roystgnr** [comment]
My "make check" hasn't finished yet, but it's churning away successfully so far; apparently Eigen supports complex Numbers.

**Comment by jwpeterson** [comment]
With no changes on the libmesh side?  Nice...

**Pull request merged**
