### PR TITLE
int -> PetscBLASInt in BLAS/LAPACK routines.

### LINKED ISSUE #1187: Fails to build with 64bit indices blas
Hi,

In newer OpenBLAS and Intel MKL it is possible to have 64 indices, PETSc added the option:
--known-64-bit-blas-indices=true \
To live with that, when this flag is true PetscBLASInt is defined to long (on clang) and LibMesh will fail to compile the BLAS wrapper code in src/numerics/dense_matrix_blas_lapack.C

```
src/numerics/dense_matrix_blas_lapack.C:1147:34: note: in instantiation of member function 'libMesh::DenseMatrix<double>::_evd_lapack' requested here
template void DenseMatrix<Real>::_evd_lapack(DenseVector<Real> &,
                                 ^
/opt/petsc/include/petscblaslapack.h:150:19: note: candidate function not viable: no known conversion from 'int *' to 'PetscBLASInt *' (aka 'long *') for 3rd argument
PETSC_EXTERN void LAPACKgeev_(const char*,const char*,PetscBLASInt *,PetscScalar *,PetscBLASInt*,PetscReal*,PetscReal*,PetscScalar*,PetscBLASInt*,PetscScalar*,PetscBLASInt*,PetscScalar*,PetscBLASInt*,PetscBLASInt*);
                  ^
```

### PR DESCRIPTION
**Pull request by jwpeterson**
This should hopefully fix #1187 by @canesin, however I do not have a 64-bit indices BLAS to test this with myself.

### CODE REVIEW

**Comment by canesin** [comment]
It passed dense_matrix but stoped in transient_rb_construction

```
src/reduced_basis/transient_rb_construction.C:842:3: error: no matching function for call to 'dsyevr_'
  LAPACKsyevr_(&JOBZ, &RANGE, &UPLO, &eigen_size, &correlation_matrix[0],
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/slepc/include/slepcblaslapack.h:168:65: note: expanded from macro 'LAPACKsyevr_'
#define LAPACKsyevr_(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u) SLEPC_BLASLAPACK(syevr,SYEVR) ((a),(b),(c),(d),(e),(f),(g),(h),(i),(j),(k),(l),(m),(n),(o),(p),(q),(r),(s),(t),(u),1,1,1)

```                                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Build on: https://hub.docker.com/r/canesin/libmesh/builds/bnnwpkcgr7jdbptsbthiez8/

**Comment by jwpeterson** [comment]
> It passed dense_matrix but stoped in transient_rb_construction

That one should be fixed in 2154abc, I'm also searching for others now...

**Comment by jwpeterson** [comment]
I'm planning to merge this soon @canesin unless you found anything else...

**Comment by canesin** [comment]
@jwpeterson my test on this setting passed the build (I acctually had problems with linking so I was investigating - but from this side looks to be :+1: )
many thanks for working on weekends! was not expecting feedback until monday - LOL.

**Pull request merged**
