### PR TITLE
Generalizing all_tri to handle 3D, adding support for PRISMs

### PR DESCRIPTION
**Pull request by jwpeterson**
Roy's comments:
```
In theory this branch adds the ability to split prisms into tets (and makes it easier to add
a future capability to split pyramids and hexes into tets).

In practice the refactoring here may have even broken the ability to split quads into tris, 
and the whole thing needs more testing before merge.
```

### CODE REVIEW

**Comment by canesin** [comment]
Just a kick question, why is this not merged ?? Is this a preparation work for XFEM support ?

**Comment by jwpeterson** [comment]
It requires additional testing.  It extends the capability of all_tri(), which may be useful for XFEM.

**Comment by jwpeterson** [comment]
Ping @roystgnr.  I've added unit tests and I'm satisfied this is at least good enough to merge now.  There were rebase conflicts with your recent unique_ids changes which I *think* I incorporated correctly, but if you could take a look that would be good.  I'd like to get this merged, since it's a pain to rebase every year...

**Comment by roystgnr** [comment]
Sure you don't want to wait for the 2nd anniversary?

Looks sane still to me.

**Pull request merged**
