### PR TITLE
-Wunused-parameter does not make sense as a C flag.

### PR DESCRIPTION
**Pull request by jwpeterson**
This reverts part of d58277d84e which turned out to be a bit overzealous.

### CODE REVIEW

**Comment by roystgnr** [comment]
You can't have unnamed parameters in C, but if for some reason (compatibility with function pointer type?) you need to have unused parameters, you can still avoid the compiler warnings, most portably just by doing ```(void) unused_parameter_name;``` in the function body.

https://stackoverflow.com/questions/3599160/unused-parameter-warnings-in-c-code?rq=1

**Comment by roystgnr** [comment]
I'd prefer suggesting users do that rather than reverting the warning flag, but I'm happy either way.

**Comment by jwpeterson** [comment]
Hm... my idea was when bringing in a "contrib" package written in C to libmesh, we don't really want to see a bunch of unused parameter warnings *or* have to `(void) foo;` a bunch of variables to avoid them, so we might as well just not warn about them in the first place. 

Since people aren't regularly committing C code to libmesh itself, I don't think we need to be as vigilant about C warnings...

**Comment by roystgnr** [comment]
For contrib packages whose headers we include, I think ignore_warnings.h is the way to go.  For people linking a little new C code to libMesh and swiping our compiler flags (a use case I've been in) I think having more warnings added is useful.  But for people linking a *lot* of old C code to libMesh and swiping our compiler flags I can see how it might be annoying.

Hmm... for compiling the contrib packages themselves, though... we don't want to either fork or pester upstream about every single warning, and it's a hassle to even edit our Makefiles to selectively disable warnings, so maybe taking particularly-overzealous warning flags out of our CFLAGS entirely really is the way to go.

**Pull request merged**
