### PR TITLE
Pass original FEType object to shape()/shape_deriv() calls.

### PR DESCRIPTION
**Pull request by jwpeterson**
Otherwise the p-level will be bumped twice as the shape() and
shape_deriv() calls bump it internally.

### CODE REVIEW

**Comment by roystgnr** [comment]
Yikes, good catch!

Is this an ancient problem?  It doesn't look like it was introduced in #1981 and I can't recall anything else touching the same code recently.

I guess nothing triggered this because we have p refinement in some examples but those don't use compute_data?

**Comment by jwpeterson** [comment]
I will also add a unit test for this case so that it hopefully continues to work...

**Comment by jwpeterson** [comment]
Hmmm... looks like the new unit test might not run correctly in parallel? I will see if I can reproduce/fix that.

**Comment by jwpeterson** [comment]
In hindsight, obviously looping over all mesh nodes was a bad idea in parallel as a bunch of 
```
Assertion `_out_of_mesh_mode' failed.
```
were being thrown.

**Pull request merged**
