### PR TITLE
Cheaper adaptivity ex3 DiscontinuityMeasure

### PR DESCRIPTION
**Pull request by roystgnr**
This shaves off some runtime and adds slightly more coverage to the
unweighted quadrature rule option

### CODE REVIEW

**Comment by permcody** [comment]
Looks like you'll need to resend the payload to kick CIVET.

**Comment by permcody** [comment]
The power outage here was very serious - we still aren't at 100% after 5 days. Hopefully tomorrow!

**Comment by jwpeterson** [comment]
> The power outage here was very serious - we still aren't at 100% after 5 days.

osprey

There's your problem right there.

**Comment by permcody** [comment]
In all seriousness, I guess it was worse than that. Apparently some underground conduit carrying the big power cables to the EROB data center failed (by that I mean they stuck cameras in them and discovered they were full of dirt and rocks). Enough foreign debris made its way into those conduits to eventually short out those cables (that mechanism isn't fully understand or hasn't been relayed to us). 

They are attempting to bypass those conduits but I imagine they will be digging a big hole in the parking lot and replacing everything soon.

**Comment by permcody** [comment]
In other news the C3 data center is running smoothly - too bad we only have Sawtooth in there and that's not available for general use yet!

**Pull request merged**
