### PR TITLE
Nemesis localize fix

### PR DESCRIPTION
**Pull request by roystgnr**
This isn't a complete solution for #2067 (it fixes NemesisIO::write_element_data, which is relatively self-contained; MeshOutput::write_equation_systems is going to need a similar fix too), but it's enough to throw at CI and make sure I didn't break anything before proceeding to the more complicated half of the fix, and it's hopefully enough that @friedmud can measure *some* speedup.

### CODE REVIEW

**Comment by roystgnr** [comment]
Ha!  I didn't think we had any discontinuous Nemesis output test coverage within libMesh itself; I forgot that it's one of the code paths plot_error can take.

**Comment by roystgnr** [comment]
Going to add on the more complicated half of the fix here.  If CI reveals that it was *too* much more complicated then we could always backtrack and just merge at a3068c3 in the worst case.

**Comment by roystgnr** [comment]
Okay, *now* this might be a complete solution to #2067.  For Nemesis at least.  Anyone using .pvtk output on large problems might want to consider updating that to use the newest APIs too.

**Comment by roystgnr** [comment]
Planning to merge today unless anyone screams; I'll have other Nemesis changes in the future that I want to build on top of these.

**Comment by permcody** [comment]
Oops - I guess we don't have all the same error flags on for MOOSE and libMesh:
https://civet.inl.gov/job/439283/

**Pull request merged**
