### PR TITLE
VTK 9.3 compatibility fix

### PR DESCRIPTION
**Pull request by roystgnr**
I haven't had time to test this properly myself, but it's already biting @rebpoli in #3665, so let's see if this makes his builds any more happy or makes our CI builds any less happy.

### CODE REVIEW

**Comment by rebpoli** [comment]
I can test it later today.

Em sáb., 21 de out. de 2023 10:40, roystgnr ***@***.***>
escreveu:

**Comment by rebpoli** [comment]
It did not work. I still see this message:

checking for vtkConfigure.h... no
VTK header files not found!
<<< Configuring library without VTK support >>>
configure: error: *** VTK was not found, but --enable-vtk-required was
specified.
make: *** [/tmp/Makefile.libmesh:19: libmesh-dbg] Error 4

I fetched the latest version of libmesh with:

$ git clone https://github.com/libMesh/libmesh.git
$ git submodule update --init --recursive && mkdir build

Any idea?

Renato

Em sáb., 21 de out. de 2023 às 10:46, rebpoli ***@***.***>
escreveu:

**Comment by roystgnr** [comment]
> I fetched the latest version of libmesh with:

> $ git clone https://github.com/libMesh/libmesh.git
> $ git submodule update --init --recursive && mkdir build

But that's not this version of libMesh.  This PR hasn't been merged into devel yet, much less made it into master.

Could you try `git remote add roystgnr https://github.com/libMesh/libmesh.git` and `git checkout --track roystgnr/vtk93_fix`, then try configuring from that?

**Comment by rebpoli** [comment]
Ooops. Sorry. Will try right away.

Em dom., 22 de out. de 2023 às 12:52, roystgnr ***@***.***>
escreveu:

**Comment by rebpoli** [comment]
It works, thank you.

I could not run the "git track" command, so I went ahead with $ git pull
origin pull/3666/head

Regards,
Renato

Em dom., 22 de out. de 2023 às 18:32, rebpoli ***@***.***>
escreveu:

**Comment by rebpoli** [comment]
Sorry, I reported success too soon.

Compilation did not work:

  CXX      src/mesh/libmesh_dbg_la-vtk_io.lo
../src/mesh/vtk_io.C:43:10: fatal error: vtkConfigure.h: No such file or
directory
   43 | #include "vtkConfigure.h"
      |          ^~~~~~~~~~~~~~~~


Em dom., 22 de out. de 2023 às 19:53, rebpoli ***@***.***>
escreveu:

**Comment by roystgnr** [comment]
See, that's why I didn't want to merge without testing.  :-)

I saw that this made it through configure against a new vtk-7.3.0.rc1 install, so I figured that was worth a PR, but I didn't actually have time to compile afterwards.

I'll finish the fixes tomorrow morning.

**Comment by roystgnr** [comment]
Well, that was unexpected.  "What do we need to replace vtkConfigure.h with" in that context appears to be "nothing".  Try updating the branch and rebuilding now?  It's now compiling for me.

**Comment by rebpoli** [comment]
Now it compiles! Thank you.

BTW: I am using

git pull --no-rebase pull origin pull/3666/head

To apply the fix to the workcopy. Is that anything smarter? The --track did
not work (probably permission issue).

Em seg., 23 de out. de 2023 às 13:05, roystgnr ***@***.***>
escreveu:

**Comment by roystgnr** [comment]
Maybe `--track` only works with ssh URLs and not with https?  A plain git pull might be as good as you can do otherwise, then.

**Pull request merged**
