### PR TITLE
Make libmesh work with debug PETSc

### PR DESCRIPTION
**Pull request by jwpeterson**
This branch has now been reorganized and rebased, and I'm pretty confident it's working.  @roystgnr and @pbauman, if you want to try your own apps with this branch (PETSc debugging enabled or not) I'd appreciate it.

MOOSE also needs to be updated to work with this version of libMesh (see idaholab/moose#5569).

### CODE REVIEW

**Comment by jwpeterson** [comment]
MOOSE's libmesh submodule has now been updated to commit 8dab454bc55 on this branch.  I'd like to get this merged to master so that future libmesh updates in MOOSE (I believe @roystgnr's #625 will generate one) incorporate this commit.

**Comment by roystgnr** [comment]
As of 2309e40 I now get a PETSc error from adaptivity_ex3 when running "make check" with 4 or more processors.  I'll see if I can bisect any better than that; are the intermediate commits here (supposed to be) regression-free?

**Comment by roystgnr** [comment]
I get the same failure with SerialMesh.  103227d fails; d44d6ff works.  Trying with debug PETSc (3.5.2) now to see if I can figure out any more of what's going on.

**Comment by roystgnr** [comment]
Looks like it's another "more processors than elements"-case bug?  If so then it's not a disaster just a nuisance.  I should probably be able to fix it shortly.

**Pull request merged**
