### PR TITLE
Fix error reporting without LibMeshInit in use

### LINKED ISSUE #4022: `fparser_parse-*` executables seem to be slightly broken
The `fparser_parse-*` executables that get built with libMesh crash on mac and linux. I think I narrowed it down to
the error message

```
  libmesh_error_msg_if(argc < 2, "Usage: " << argv[0] << " function_to_eval [x] [y] [z] [t]");
```

which results in a blocking spin lock on Linux:

```
Program received signal SIGINT, Interrupt.
0x00007fffea4933a2 in pthread_spin_lock () from /lib64/libpthread.so.0
(gdb) bt
#0  0x00007fffea4933a2 in pthread_spin_lock () from /lib64/libpthread.so.0
#1  0x00007ffff5d2a68e in libMesh::Threads::spin_mutex::lock (this=0x7ffff7dc7100 <libMesh::Threads::spin_mtx>) at ./include/libmesh/threads_pthread.h:149
#2  0x00007ffff6be3fe0 in libMesh::Threads::lock_singleton_spin_mutex () at ../src/parallel/threads.C:34
#3  0x00007ffff5e0efc4 in libMesh::on_command_line (arg="--gdb") at ../src/base/libmesh.C:959
#4  0x00007ffff5e35bbe in libMesh::print_trace (out_stream=...) at ../src/base/print_trace.C:219
#5  0x00007ffff5e2d8c2 in libMesh::MacroFunctions::report_error (file=0x4140d7 "../src/apps/fparser_parse.C", line=32, date=0x4140cb "Nov 19 2024",
    time=0x4140c2 "22:08:08", os=...) at ../src/base/libmesh_common.C:85
#6  0x000000000040b713 in main (argc=1, argv=0x7fffffffe248) at ../src/apps/fparser_parse.C:32
```

and a similar issue on mac:

```
Target 0: (fparser_parse-dbg) stopped.
(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BREAKPOINT (code=1, subcode=0x188d89160)
  * frame #0: 0x0000000188d89160 libsystem_platform.dylib`_os_unfair_lock_recursive_abort + 36
    frame #1: 0x0000000188d842bc libsystem_platform.dylib`_os_unfair_lock_lock_slow + 320
    frame #2: 0x0000000107420768 libmesh_dbg.0.dylib`libMesh::Threads::spin_mutex::lock() + 24
    frame #3: 0x000000010842bb5c libmesh_dbg.0.dylib`libMesh::Threads::lock_singleton_spin_mutex() + 20
    frame #4: 0x0000000107550758 libmesh_dbg.0.dylib`libMesh::on_command_line(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>) + 116
    frame #5: 0x00000001075809b0 libmesh_dbg.0.dylib`libMesh::print_trace(std::__1::basic_ostream<char, std::__1::char_traits<char>>&) + 244
    frame #6: 0x00000001075756f4 libmesh_dbg.0.dylib`libMesh::MacroFunctions::report_error(char const*, int, char const*, char const*, std::__1::basic_ostream<char, std::__1::char_traits<char>>&) + 252
    frame #7: 0x00000001000028f0 fparser_parse-dbg`main + 208
    frame #8: 0x00000001889cb154 dyld`start + 2476
```

Expected result would be that teh error message is printed.

### PR DESCRIPTION
**Pull request by roystgnr**
And I cleaned up a bit of code while I was at it.

This fixes #4022 for me.

### CODE REVIEW

**Comment by roystgnr** [comment]
That timeout with threads looks suspicious.  I'll see if I can replicate.

**Comment by roystgnr** [comment]
Not even coming close to replicating it... 2 ranks with 2 threads each, 8 with 8, 2 with 32...

**Comment by roystgnr** [comment]
Nope, never mind, this is easy to replicate.

**Comment by roystgnr** [comment]
Well, I'm happy that fixed my deadlocks, but clearly my simple little cleanup wasn't as simple as I thought.  Not going to merge until @jwpeterson or @lindsayad have a chance to look it over, and if anybody has any suspicions or if nobody has time then I can just pull out the fix in the first commit to a separate PR and we can wait on the rest.

**Review by lindsayad — APPROVED** [review]

**Comment by lindsayad** [comment]
looks good to me

**Review by jwpeterson — APPROVED** [review]
Ideally we would not have a static var in `report_error()`, and then we wouldn't have to worry about race conditions in `report_error()`, is that right? I don't see an easy way to avoid the infinite recursion without the static variable, though, so this looks like the right fix to me.

**Pull request merged**
