### PR TITLE
Update MetaPhysicL

### PR DESCRIPTION
**Pull request by lindsayad**
- Support for std::complex functions for some classes
- Bugfix in DynamicSparseNumber*::operator[]
- More unit tests

### CODE REVIEW

**Comment by roystgnr** [comment]
Let's wait until @pbauman gets femputer back up before merging this one.

**Comment by jwpeterson** [comment]
Let me all double-check that running bootstrap in libmesh on this branch doesn't modify and autoconf files...

**Comment by jwpeterson** [comment]
> Let me also double-check

Looks good to me!

**Comment by roystgnr** [comment]
@pbauman seems to be AFK right now, and the only thing I'm worried about triggering on femputer is the -Werror stuff, so we'll risk a merge.

**Pull request merged**
