### PR TITLE
Don't use LIBMESH_OPTIONS in reduced basis ex5

### PR DESCRIPTION
**Pull request by roystgnr**
I could swear that my usual "block Jacobi + ILU4" combo has been
working fine here for years, but today I just get a convergence
failure with DIVERGED_INDEFINITE_PC.

Regressing libMesh a ways doesn't seem to help.  @pbauman is trying to
hunt down some PETSc behavior changes that hopefully will explain this
too, but in the meantime the default preconditioner settings work fine
and we should just use them.

### CODE REVIEW

**Comment by jwpeterson** [comment]
Is this a bugfix you want on 0.9.5 too?

**Comment by roystgnr** [comment]
Hmm... I hadn't thought about it, but yes, thanks.

**Comment by pbauman** [comment]
> I could swear that my usual "block Jacobi + ILU4" combo has been
working fine here for years, but today I just get a convergence
failure with DIVERGED_INDEFINITE_PC.
Regressing libMesh a ways doesn't seem to help. @pbauman is trying to
hunt down some PETSc behavior changes that hopefully will explain this
too

I haven't tried this example, but my own failing example is triggered moving from PETSc 3.5.4 to PETSc 3.6.0.

**Comment by jwpeterson** [comment]
Hmm.. this jogged my memory and I found this old commit message

```
    PETSc-3.6 changes the default value of -pc_factor_shift_type to
    'none', these tests require a -pc_factor_shift_type of 'nonzero' to
    work correctly....
```

So could you try the ILU4 flags with `-pc_factor_shift_type nonzero` and see if that makes a difference?

**Comment by pbauman** [comment]
FWIW, I was looking for this thread several days ago. The issues I'd encountered that were mentioned at the beginning of this thread turned out to be directly tied to the default change on the pc factor shift. My issue was fixed using `-pc_factor_shift_type nonzero`.

**Pull request merged**
