### PR TITLE
Add shape functions for NEDELEC_ONE FEs on TET10 mesh elements

### PR DESCRIPTION
**Pull request by alexanderianblair**
I've added a set of shape functions for NEDELEC_ONE elements on  TET10 meshes in 3D, based on the implementation in MFEM [here](https://mfem.github.io/doxygen/html/fe_8cpp_source.html), working to extend the range of FEs available in libMesh as in #1456. I've also extended the vector_fe/vector_fe_ex4 example to test the curl-curl problem on TET10s, just as was previously done on HEX20 and HEX27 mesh elements in 3D in #130.

There does appear to be some additional artifacts in the Paraview visualisations for these examples over each element, but H_curl error estimates seem reasonable compared to the case for hexehedral meshes (and solutions appear to converge to the right values as mesh size decreases). 

Any comments/recommendations welcome!

### CODE REVIEW

**Comment by jwpeterson** [comment]
Thanks, I will start the testing momentarily and send you an invite to join a group of developers that gets their PRs tested automatically.

**Comment by jwpeterson** [comment]
It might be good to also add a comment somewhere with a reference book or paper that these are from. I looked at the MFEM source but did not see an obvious reference there.

**Comment by alexanderianblair** [comment]
Sure, I'll add one in - the reference implementation is more specifically in mfem::Nedelec1TetFiniteElement::CalcVShape() in that source [here](https://mfem.github.io/doxygen/html/classmfem_1_1Nedelec1TetFiniteElement.html#a0f99dd4510c0a34894ad9e81e5dd1fd7).
Worth noting that MFEM has a slightly different node numbering scheme to libMesh, but that should be accounted for already in this commit!

**Comment by jwpeterson** [comment]
@pbauman Any comments on this? It extends your original work on the vector-valued FEs.

**Comment by pbauman** [comment]
I don't have time to verify shape functions, but it looks like the test is being used, so if the correct convergence rate is observed, then probably are good. The test only prints out the error, I manually confirmed the convergence rate when I did the quads and hexes. So I would encourage doing that. Otherwise, I'm super happy someone completed what I never did. Thanks @alexanderianblair!

**Review by roystgnr — APPROVED** [review]

**Comment by jwpeterson** [comment]
I ran vector_fe_ex4 with TET10s and got first-order convergence for both L2 and H(curl) error. I'm not sure whether these are the expected rates of convergence for the curl-curl problem, but with HEX20s for example I get 2nd-order convergence in L2.

vector_fe_ex4

**Comment by pbauman** [comment]
First order in HCurl is expected. Never did dig deeper to understand why L2 got second order on the hexes. At any rate, if you're getting the right convergence order in HCurl, that's pretty good evidence.

**Comment by alexanderianblair** [comment]
The first order H(curl) and L2 errors decreasing for the TET10s are expected, and are consistent with those seen in deal.ii [here](https://www.dealii.org/reports/nedelec/nedelec.pdf), FEMPAR [here](https://www.sciencedirect.com/science/article/pii/S096599781831113X) and referenced by FEniCS [here](https://fenicsproject.org/pub/book/book/fenics-book-2011-06-24.pdf). The first order H(curl) error is optimal as far as I'm aware (see, for example, [Monk](https://icerm.brown.edu/materials/Slides/tw-18-7/Finite_Element_Methods_for_Maxwells_Equations_%5D_Peter_Monk,_University_of_Delaware.pdf) and [Hiptmair at al.](https://www.sam.math.ethz.ch/sam_reports/reports_final/reports2009/2009-04_fp.pdf)). It's interesting that the L2 error decreases faster for HEX20s - as noted in the deal.ii [report](https://www.dealii.org/reports/nedelec/nedelec.pdf) above, whilst O(h) convergence is usually expected, the optimal convergence can be faster than that. I'm not sure why they seem to be giving second order here though either yet!

**Comment by jwpeterson** [comment]
> I'm not sure why they seem to be giving second order here though either yet!

I guess it could be some fortuitous cancellation happening because of the uniform grid on a cube... anyway good to hear that the results are generally as expected. Thanks also for those links. I think it would be good to get those into the documentation somewhere, maybe just throw them in vector_fe_ex4.

**Comment by jwpeterson** [comment]
I added those references to vector_fe_ex4 and merged. Thanks again!

**Pull request merged**
