### PR TITLE
DistributedMesh fixes

### PR DESCRIPTION
**Pull request by roystgnr**
We now handle cases where processors need multiple communication sweeps to get node ids correct, cases where coarsening away thin partitions was failing to correctly communicate newly ghosted elements to the other partitions on each side, and cases where I can't correctly write a receive_packed_range call without noticing that I've cut-and-pasted blatantly incorrect code.

This is passing basic parallel tests for me, and should be ready to merge.

I can no longer find any outstanding DistributedMesh bugs, but I'm still sweeping through test suites on varying processor counts to search.

### CODE REVIEW

**Comment by pbauman** [comment]
> I can no longer find any outstanding DistributedMesh bugs

Epic.

**Comment by roystgnr** [comment]
Well, DistributedMesh was totally solid at this time last year, too, so there wasn't too much to fix.  The current swaths of bug fixes have all been to fix DistributedMesh-without-ghosted-point-neighbors bugs, which weren't introduced until last summer when I realized just how much ridiculous over-ghosting we get if we try to retain all point neighbors on hierarchically refined grids.

**Comment by pbauman** [comment]
For some reason, I thought there was some longstanding bug you'd just squashed. Still happy  `DistributedMesh` is in good shape again, though.

**Comment by roystgnr** [comment]
I think "since August" is pretty long-standing for a bug that I could replicate as simply as "make check" on 24 processors.

In hindsight maybe I should have left point neighbors ghosting turned on until we had things working with it off.

On the other hand, it was very motivating to have @friedmud raving to everyone (with interactive "look at the results in top!" terminal window even) about how DistributedMesh has been cutting his RAM usage by 95%, and how everyone needs to switch to it ASAP...  If at that point the DistributedMesh landmines were buried by workarounds then I might have been too lazy to dig in and defuse them.

**Comment by permcody** [comment]
In other news, people searching the list for years to come will enjoy
reading remarks from Derek and unfortunately myself that you both "never"
need to use ParallelMesh and that you should simultaneously should "always"
use it for large runs...  Sigh...

**Comment by jwpeterson** [comment]
On Thu, Feb 2, 2017 at 8:00 AM, Cody Permann <notifications@github.com>
wrote:

> In other news, people searching the list for years to come will enjoy
> reading remarks from Derek and unfortunately myself that you both "never"
> need to use ParallelMesh and that you should simultaneously should "always"
> use it for large runs... Sigh...


We've always been at war with DistributedMesh.

-- 
John

**Comment by roystgnr** [comment]
It'll take a while until my ```for num in $(seq 1 24); do LIBMESH_RUN="mpirun -j $num" ...``` tests are done, but we're past the point where I was able to trigger errors previously, so I'm tempted to merge this ASAP.

I'll run it through GRINS on 12 processors too and if nobody's screamed by the time that finishes, I'll merge.

**Comment by roystgnr** [comment]
I can still trigger an assertion failure (inconsistent refinement flags) when using AdjointRefinementErrorEstimator on 7 or more processors.  It shouldn't affect opt mode runs, though (we always sync refinement flags just in case the user flagged things inconsistently; we just scream about it in devel/debug modes), and I'm not yet sure whether the problem is a bug we can fix or whether this is just an overzealous assertion we need to remove.

Every test I've thrown passes in opt mode, and the inconsistent flagging assertion is the only thing I've managed to trip in debug mode.

**Pull request merged**
