### PR TITLE
print_helper using 3D vector argument

### LINKED ISSUE #3380: 3D Vector Argument for libMesh::print_helper()
`libMesh::print_helper() ` is used by MOOSE for parsing input files. Recently, triple indexed/separated fields were found needed in MOOSE input syntax. To make that happen, `libMesh::print_helper(std::ostream & os, const std::vector<std::vector<std::vector<P> >>* param)` is needed.

### PR DESCRIPTION
**Pull request by miaoyinb**
closes #3380

### CODE REVIEW

**Comment by miaoyinb** [comment]
@GiudGiud FYI

**Comment by jwpeterson** [comment]
FYI @miaoyinb I sent you an invite to join a group that has its PRs tested automatically. Note that some of the testing may fail currently due to a change that is present in libmesh upstream that is not compatible with MOOSE, we're hopeful that will be updated soon.

**Comment by miaoyinb** [comment]
> FYI @miaoyinb I sent you an invite to join a group that has its PRs tested automatically. Note that some of the testing may fail currently due to a change that is present in libmesh upstream that is not compatible with MOOSE, we're hopeful that will be updated soon.

Got it. Thank you so much.

**Review by roystgnr — APPROVED** [review]
I dislike that we're flattening the output here rather than using some kind of delimiter between different sub (and subsub) vectors ... but we're *already* flattening the `vector<vector<P>>` case, so at least we're consistent.

**Comment by roystgnr** [comment]
The Test MOOSE failure is just "Test MOOSE python" again.

**Pull request merged**
