### PR TITLE
Prevent adaptivity_ex3 from being run in invalid configurations.

### PR DESCRIPTION
**Pull request by jwpeterson**
Refs #1472.

### CODE REVIEW

**Comment by jwpeterson** [comment]
This PR is being tested with `libmesh_CXXFLAGS = -std=c++11` in the environment.

The failure is during compilation of the unit tests:
```
../../tests/base/unique_ptr_test.C: In member function 'void UniquePtrTest::testMakeUnique()':
../../tests/base/unique_ptr_test.C:99:32: error: 'make_unique' is not a member of 'std'
     std::unique_ptr<int> foo = libmesh_make_unique<int>(42);
                                ^~~
../../tests/base/unique_ptr_test.C:99:49: error: expected primary-expression before 'int'
     std::unique_ptr<int> foo = libmesh_make_unique<int>(42);
                                                 ^~~
```
but I'm not sure why it fails, because the configure test of `std::make_unique` passes. I'll need to check it out on a system similar to the build box to figure out what's going on.

**Comment by BalticPinguin** [comment]
what do you think about adding 
```--- a/src/error_estimation/hp_coarsentest.C
+++ b/src/error_estimation/hp_coarsentest.C
@@ -236,12 +236,6 @@ void HPCoarsenTest::select_refinement (System & system)
           d2phi = &(fe->get_d2phi());
           d2phi_coarse = &(fe_coarse->get_d2phi());
         }
-#else
-      if (cont == C_ONE)
-        {
-           libmesh_error_msg("Minimisation of H2 error without second derivatives impossible.");
-           libmesh_not_implemented();
-        }
 #endif // defined (LIBMESH_ENABLE_SECOND_DERIVATIVES)

       // Iterate over all the active elements in the mesh
                                                                      ` ` `

as well? So we can prevent users from running into this issue with their own code...

**Comment by roystgnr** [comment]
The libmesh_not_implemented() in your suggestion would never get reached.  Otherwise, that does look like a good idea.  It won't prevent anyone from running into the issue but it would make it much easier for them to debug if they do.

**Comment by BalticPinguin** [comment]
oh, you are right :-) Than probably the error message is better to keep...

**Pull request merged**
