### PR TITLE
Upgrade MetaPhysicL to version 0.3.1

### PR DESCRIPTION
**Pull request by roystgnr**
https://github.com/roystgnr/MetaPhysicL/pull/22 would be good to
incorporate right away, assuming @lindsayad sees no problems.

### CODE REVIEW

**Comment by jwpeterson** [comment]
This was definitely bootstrapped using the libmesh autotools versions and not the one-off Ubuntu packages? I can double-check that if you want...

**Comment by roystgnr** [comment]
I checked my $PATH before bootstrap and I did a git diff in contrib/metaphysicl after, but yeah, I'd appreciate a double-check anyway.

**Comment by jwpeterson** [comment]
./bootstrap is clean for me so :+1:

**Comment by lindsayad** [comment]
I think this is good to go

**Pull request merged**
