### PR TITLE
Add new parameter to MeshExtrusion for user-defined sub ids

### PR DESCRIPTION
**Pull request by permcody**
This PR adds the capability for users to define how subdomain ids are assigned to new elements created during mesh extrusion.

I have an example in MOOSE ready to go but I'd be happy to create one in libMesh as well. Do we have anything else using extrusion in the examples right now?

### CODE REVIEW

**Comment by roystgnr** [comment]
Nothing in the examples currently uses build_extrusion.  If you'd add one that would be great, thanks!

**Comment by jwpeterson** [comment]
Just add a cppunit test if you want to add something...

**Comment by roystgnr** [comment]
Agreed, no need for a full-on-example here.

**Comment by jwpeterson** [comment]
I'm editing this branch to remove the multi_block.e mesh file which you don't appear to be using any more.  Will merge by hand.

**Comment by permcody** [comment]
Thanks. Forgot to rip that out

**Comment by jwpeterson** [comment]
Merged in 0dd5ae7.

**Pull request closed without merging**
