### PR TITLE
Add edge to side map for all cells

### LINKED ISSUE #2462: Add edge to side maps for cells
We use these in ray tracing. It makes sense to have them in libMesh instead.

### PR DESCRIPTION
**Pull request by loganharbour**
Closes #2462

### CODE REVIEW

**Comment by loganharbour** [comment]
There's a 2 everywhere that is the number of sides that contain an edge... should this be a static variable?

**Comment by loganharbour** [comment]
I agree. The routines we're using have direct access to the type, therefore they just access the static variables, so I didn't think about routines.

I'll add some to this and ping when done.

**Comment by roystgnr** [comment]
We can merge after that, then.

If you have time, a unit test wouldn't hurt either.

<<Strange, you think.  Who would write that sentence down and tie it to a stone?  Perhaps you should investigate the glass house nearby.>>

**Comment by loganharbour** [comment]
What's an appropriate unit test here?  Checking all of the maps with respect to one another?

**Comment by roystgnr** [comment]
Yeah, that's about all I can think of.  Assert is_node_on_edge && is_edge_on_side => is_node_on_side.

**Comment by loganharbour** [comment]
Alright. This is good now.

**Comment by roystgnr** [comment]
Looks good to me too, thanks!  I'll hit the button if I'm still awake when it passes CI.

**Pull request merged**
