### PR TITLE
DTKSolutionTransfer should store std::unique_ptrs

### PR DESCRIPTION
**Pull request by jwpeterson**
This one is not an API change but it's complicated by the fact that I don't have a Trilinos (let alone DTK) build so while the change should be pretty straightforward I'm not sure it actually compiles. Was hoping maybe there's an attachable CIVET recipe that could test this...

### CODE REVIEW

**Comment by jwpeterson** [comment]
> Was hoping maybe there's an attachable CIVET recipe that could test this...

Aaand there doesn't seem to be one. I would also be OK with deprecating/eventually deleting this code if it's no longer being used or maintained.

**Comment by jwpeterson** [comment]
Test failures are not related to this PR.

**Comment by jwpeterson** [comment]
The failing tests are being addressed in https://github.com/idaholab/moose/pull/20794

**Review by roystgnr — APPROVED** [review]

**Comment by roystgnr** [comment]
We really do need to get Trilinos back in CI.  It's too useful an alternative to deprecate, but it might not have been properly tested since BuildBot days.

**Pull request merged**
