### PR TITLE
Add geometric constants for EDGE elems

### LINKED ISSUE #2657: Add geometric constants for EDGE elem types
Add `num_sides`, `num_edges`, `nodes_per_side`, and `nodes_per_edge` to the EDGE derived types for consistency.

### PR DESCRIPTION
**Pull request by loganharbour**
Closes #2657

### CODE REVIEW

**Comment by loganharbour** [comment]
@roystgnr this is good.

I tried to find some edge methods that could use this to no avail.

**Comment by jwpeterson** [comment]
Seems fine to me but I'm curious about the distinction between 0 and `invalid_int`? If we say that an Edge has `num_edges=0` (seems reasonable) could we also just say it has `nodes_per_edge=0` for simplicity?

**Comment by loganharbour** [comment]
The thought here by @roystgnr was that if `num_edges = 0`, that `nodes_per_edge` should be some not-applicable value. Hence, the invalid_int.

I see reasons for both choices (invalid/0) - so I'll let you guys choose 😬

**Comment by jwpeterson** [comment]
My main concern would be some code that accidentally creates an array of size `Edge2::nodes_per_edge` but since there's no virtual API/accessor for it I guess that's pretty unlikely.

**Comment by roystgnr** [comment]
> My main concern would be some code that accidentally creates an array of size Edge2::nodes_per_edge

Ah, I see.  *My* concern had been code that's accidentally been called for the "edge of an edge", and making that loop forever rather than continue failing silently seemed like the best way to go.

I think anything trying to allocate an Elem2::nodes_per_edge array, but not as part of a loop over all 0 edges whose internals thereby don't get triggered, is probably likewise a "already broken so let's die ASAP where the breakage is easy to diagnose" case, in which case invalid_int is still the way to go, but I could be talked out of that.

**Pull request merged**
