### PR TITLE
Update metaphysicl

### PR DESCRIPTION
**Pull request by lindsayad**
Summary of changes:
  * Create metaphysicl_dbg_var to eliminate compiler warnings
  * Add unsigned long / long long support
  * Add long int type support
  * Fix Perl GetOptions unknown option error for mingw64
  * Fix warning with clang 7.x: Prevent copying when returning by name; use std::move

### CODE REVIEW

**Comment by roystgnr** [comment]
Uh-oh.  Looks like you used automake 1.15 instead of 1.16.1 to generate the v0.5.0_bootstrapped tag on MetaphysicL?  IIRC that'll cause libMesh builds to scream and die for users without autotools, when the libMesh build and the submodule build don't match.

**Comment by lindsayad** [comment]
Brutal. I'll fix that up

**Comment by jwpeterson** [comment]
You may already be aware of this, but if not, note that you can run `./bootstrap --build-autotools` in libmesh to make sure that you are up to date. They don't change that often.

**Comment by lindsayad** [comment]
Yea, just did that!

**Comment by lindsayad** [comment]
Good to merge?

**Comment by roystgnr** [comment]
Thanks!

**Pull request merged**
