### PR TITLE
Small changes to splitter to change the way the filenames are output

### PR DESCRIPTION
**Pull request by friedmud**
Splitter will now remove the original file extension.

I also did a bit of checking for the number of arguments for printing the help information.

### CODE REVIEW

**Comment by jwpeterson** [comment]
👍

**Comment by friedmud** [comment]
FYI: This is holding up https://github.com/idaholab/moose/pull/8472

**Comment by roystgnr** [comment]
Sorry; I'd noticed John's response in my inbox but didn't realize he hadn't merged it yet.  Looks great to me too.

**Comment by friedmud** [comment]
Thanks @roystgnr !

**Pull request merged**
