### PR TITLE
Fixes for local_*_indices methods

### PR DESCRIPTION
**Pull request by roystgnr**
And a new unit test from @YaqiWang which (prior to the fixes) triggered the #1841 problems that he caught.

If this works for his application code too then we declare victory; if not then IMHO even a partial fix would be a big improvement over the previous behavior.

### CODE REVIEW

**Comment by roystgnr** [comment]
FYI, although that unit test is showing up first in the list, git log tells me it is the last commit in the PR, as I intended to keep "make check" working on intermediate commits.  Not sure why github is showing me those commits in chronological order rather than post-interactive-rebase order.

**Comment by YaqiWang** [comment]
I will test this out.

**Comment by YaqiWang** [comment]
This appears fixing my issue.

**Comment by roystgnr** [comment]
I'll merge tonight, then.  Thanks for the help digging into this, and sorry for the delay fixing it!

**Comment by YaqiWang** [comment]
Thanks to you @roystgnr .

**Pull request merged**
