### PR TITLE
Better handling of corners when adding boundary ghost elements to tri…

### PR DESCRIPTION
**Pull request by svallaghe**
…angular meshes for subdivision elements

### CODE REVIEW

**Comment by jwpeterson** [comment]
Hmm.. since I don't really understand the algorithm just by looking at it, would it be possible for you to add a unit test that verifies it works for a simple test case?

**Comment by svallaghe** [comment]
The example miscellaneous11 is using that piece of code.
It's definitely not a unit test, but would it still be sufficient ?
Otherwise I'm not sure I can provide a unit test in a timely fashion.

**Comment by jwpeterson** [comment]
OK, I'll take a look at misc. ex11 before/after the patch.  As long as we have some code checked in that exercises the new algorithm that's fine.

**Comment by svallaghe** [comment]
Works for me! Thanks!

**Comment by jwpeterson** [comment]
misc ex11 produces the outputs below before and after the patch, respectively.  I take it this is doing the right thing?

Before patch:
before_patch

After patch:
after_patch

**Pull request merged**
