### PR TITLE
Re-bootstrap after #1822

### PR DESCRIPTION
**Pull request by roystgnr**
Can't believe we missed this...

### CODE REVIEW

**Comment by jwpeterson** [comment]
Hah, wow, my bad as well. Wait, this also means that @BalticPinguin probably never tested the actual changes unless he remembered to bootstrap locally. Also, it looks like GRINS doesn't like them. Might be time for a revert?

**Comment by roystgnr** [comment]
Definitely.  I'll see if I can replicate the failures.

**Comment by roystgnr** [comment]
Seems to be building fine for me...

**Comment by roystgnr** [comment]
And MOOSE for that matter.  Pinging @pbauman to see if he has any idea of what the GRINS CI might be doing differently.

**Comment by roystgnr** [comment]
Well, the problem is at config time.  PETSc is built with MPI, we reject that version of MPI for being too old, but then PETSc doesn't get rejected with it.  That's actually kind of hard to solve - we *want* to reject PETSc if it's using an MPI we can't use, but not if it's built without MPI at all...

**Comment by pbauman** [comment]
Below is what's coming out of the output. Looks like 'MPI_REAL' is getting redefined in `libmesh_common.h`

<pre>
CXX      mesh/unit_tests_devel-spatial_dimension_test.o
In file included from /femputer/pbauman/swstack/libs/petsc/3.7.4/gcc/6.2.0/mpich/3.1.4/openblas/0.2.18/opt/include/petscsys.h:130:0,
                 from /femputer/pbauman/swstack/libs/petsc/3.7.4/gcc/6.2.0/mpich/3.1.4/openblas/0.2.18/opt/include/petscbag.h:4,
                 from /femputer/pbauman/swstack/libs/petsc/3.7.4/gcc/6.2.0/mpich/3.1.4/openblas/0.2.18/opt/include/petsc.h:5,
                 from ../include/libmesh/petsc_macro.h:63,
                 from ../include/libmesh/dense_matrix.h:29,
                 from ../include/libmesh/diff_context.h:24,
                 from ../include/libmesh/fem_context.h:24,
                 from ../include/libmesh/fem_function_base.h:27,
                 from ../include/libmesh/system.h:28,
                 from ../include/libmesh/equation_systems.h:26,
                 from /femputer/pbauman/civet_build_testing_root/libMesh/tests/fe/fe_test.h:8,
                 from /femputer/pbauman/civet_build_testing_root/libMesh/tests/fe/fe_clough_test.C:2:
/femputer/pbauman/swstack/libs/mpich/3.1.4/gcc/6.2.0/include/mpi.h:193:0: error: "MPI_REAL" redefined [-Werror]
 #define MPI_REAL              ((MPI_Datatype)1275069468)
 
In file included from ../include/libmesh/libmesh.h:25:0,
                 from /femputer/pbauman/civet_build_testing_root/libMesh/tests/test_comm.h:1,
                 from /femputer/pbauman/civet_build_testing_root/libMesh/tests/fe/fe_test.h:4,
                 from /femputer/pbauman/civet_build_testing_root/libMesh/tests/fe/fe_clough_test.C:2:
../include/libmesh/libmesh_common.h:143:0: note: this is the location of the previous definition
 # define MPI_REAL MPI_DOUBLE
</pre>

**Comment by pbauman** [comment]
I'll try and reproduce locally tomorrow.

**Comment by pbauman** [comment]
Oh, the difference is I have `-Werror` on. :)

**Comment by BalticPinguin** [comment]
hmm; actually I did run bootstrap, but didn't run into these problems, for some reason.
I will check my test-configurations, but most probably the reason is that I combined old MPI with old compilers only.

@pbauman : just for me to understand the failing in the civet: You load mpich/3.1.4 but fail due to too low mpi-version; so you just manipulated the version-string to make it fail?

Sorry to all for all the inconveniences with my PR...

**Pull request closed without merging**
