### PR TITLE
Update FEM System ex1

### PR DESCRIPTION
**Pull request by canesin**
(forgot to force push on previous PR)

Fixed deprecation messages on API usage.
From my understanding of fem_system default mass_residual the contributions should actually be the negative -M(u)u_dot, so fixed signals. Visual changes are very minor, which is a major reason for being confusing.

New
fem_system_ex1_new

Old
fem_system_ex1_old

### CODE REVIEW

**Comment by jwpeterson** [comment]
I suspect you are looking at a (nearly) steady state solution here. If so, the sign on the transient term doesn't make any difference. @roystgnr would you mind weighing in on this change??

**Comment by roystgnr** [comment]
I would greatly mind weighing in on this change, because as best as I can tell, it highlights a bug I wrote, in an important example code, which has gone unfixed for nearly a decade, and the shame I'm experiencing right now is torturous.

My only concern right now is, was this the *only* bug?  I'd like to check the other terms' signs before we merge.

**Comment by roystgnr** [comment]
Convection is negative, as it should be since we pull it to the RHS.

Pressure is positive and diffusion negative, thanks to the integration by parts.

Forcing is positive by definition.

Pressure constraint is positive for symmetry.

Yeah, :+1: to merge.

**Comment by jwpeterson** [comment]
Thanks, I just invalidated the one CI test that failed, so we can wait for that to finish or not, there's no way this example can affect the running of MOOSE.

**Comment by jwpeterson** [comment]
Thanks @canesin!

**Pull request merged**
