### PR TITLE
Only build discontinuous solution vector when variable is active on subdomain

### PR DESCRIPTION
**Pull request by lindsayad**
Should hopefully resolve issue experienced on mailing thread here: https://sourceforge.net/p/libmesh/mailman/message/36400029/

### CODE REVIEW

**Comment by jwpeterson** [comment]
Looks reasonable to me, thanks @lindsayad!

**Comment by lindsayad** [comment]
Renato's exodus output:
lmerr

My exodus output:
pview

**Comment by lindsayad** [comment]
So stupid...I had overload a `vtkBlockColors` plot over the `p` plot. I'm now seeing the same results as Renalto.

Do not merge as is!

**Comment by lindsayad** [comment]
I think this looks more like it...
pview

**Comment by lindsayad** [comment]
Renato has confirmed that this works for him, so this is good to go

**Pull request merged**
