### PR TITLE
Remove redundant (and shadowing) fe

### PR DESCRIPTION
**Pull request by roystgnr**
This fixes a -Wshadow warning for me

### CODE REVIEW

**Comment by roystgnr** [comment]
Looks like this slipped through CI because "Test with complex numbers and infinite elements enabled" doesn't have PETSc enabled, much less SLEPc?  We should probably fix that if we can...

**Comment by jwpeterson** [comment]
We did this on purpose because there is no complex-enabled PETSc available in CIVET/the MOOSE package. If they decide to add one, we should definitely add a complex-PETSc target.

I actually kind of like this test target the way it is because it tests Eigen... and complex-valued Eigen at that, something that would get no coverage otherwise.

**Comment by jwpeterson** [comment]
BTW, I checked but this shadowing error isn't in v1.4.0, (misc_ex14 was updated after we branched) so this does not need to be cherry-picked.

**Comment by roystgnr** [comment]
> I actually kind of like this test target the way it is because it tests Eigen... and complex-valued Eigen at that, something that would get no coverage otherwise.

I forgot about that; good point.

**Pull request merged**
