### PR TITLE
Use Mesh::add_point to ensure new Node has a valid ID

### PR DESCRIPTION
**Pull request by dknez**

### CODE REVIEW

**Comment by roystgnr** [comment]
This is good, but @jwpeterson points out that the underlying flaw is a bug in ReplicatedMesh::add_node(); we should fix that too in another PR.

**Comment by jwpeterson** [comment]
@roystgnr I don't get why this compiles (maybe it is in a config we don't test?). We need to pass a `Point` to the `add_point()` routine but three values are passed here. I'm worried the second and third args are being converted to id and proc_id somehow.

**Comment by jwpeterson** [comment]
> (maybe it is in a config we don't test?)

Yeah, this is inside an `#if defined(LIBMESH_HAVE_CAPNPROTO)` section, and configure says:
```
<<< Required header files not found, Cap'n Proto support disabled. >>>
```

**Comment by roystgnr** [comment]
Whoa, that'll teach me to read diffs more closely.

> I'm worried the second and third args are being converted to id and proc_id somehow.

That'd have been caught via ```-Werror -Wconversion``` in our ```--enable-werror --enable-paranoid-warnings``` CI builds - if only at least one of those hadn't ifdef'ed out the broken code.

**Comment by jwpeterson** [comment]
I will push a fix for this, I have a capnp build locally.

**Comment by dknez** [comment]
Oops, thanks!

**Pull request merged**
