### PR TITLE
We can't check whether an element is_semilocal() unless it is active().

### PR DESCRIPTION
**Pull request by jwpeterson**
This is because Elem::is_semilocal() calls Elem::find_point_neighbors(),
which asserts that the Elem is active.  Note that we had a check for
"not_subactive" but this is apparently not the same thing as being
"active".

Refs #974.

### CODE REVIEW

**Comment by jwpeterson** [comment]
@roystgnr any yea/nay vote on this as a temporary fix until `Elem::is_semilocal` can be refactored?

**Comment by roystgnr** [comment]
What's the use case?  If there's something breaking in the library, then yeah, merge this until we can do something better.  If you need semilocal active iterators at the app level, I think what would be better would be to add semilocal_active_ iterators and use those so that you don't have to worry about the behavior changing under the hood at a later date.

**Comment by jwpeterson** [comment]
Nothing breaking in the library, no, but fixes an inconsistency for anyone who today writes a loop over semi_local iterators on a refined mesh.  They'll get either a segfault or assert as the code stands now.  I think @dschwen fixed his issue by looping over active elements and checking whether each is_semilocal, but not before he came to our cube complaining about libmesh bugs.

**Comment by dschwen** [comment]
Mister complainsy pants.

**Comment by roystgnr** [comment]
Okay, it looks like we're not using this in the library at all?  And anyone using it outside of the library is flirting with disaster?  Then yeah, let's change the semilocal_elements iterators into active_semilocal_elements iterators, let's drop the semilocal_elements iterators entirely for now, and let's reintroduce semilocal_elements iterators once we've fixed is_semilocal() and can accommodate them.

**Comment by jwpeterson** [comment]
> Then yeah, let's change the semilocal_elements iterators into active_semilocal_elements iterators, let's drop the semilocal_elements iterators entirely for now,

`semilocal_elements_begin()`/`end()` are currently being used in MOOSE so we can't drop them outright without also patching MOOSE.  How about for now we just make those existing functions return the same thing as the new `active_semilocal_elements_begin()`/`end()` until they can be patched?

**Comment by roystgnr** [comment]
Sounds good to me.  Thanks!

**Pull request merged**
