### PR TITLE
Cache FE in FEMContext::point_value()

### PR DESCRIPTION
**Pull request by roystgnr**
@friedmud, would you give this a try?  It's a minor design tweak rather than a good permanent solution but I'm hoping it'll be noticeably cheaper for you than the current code.

### CODE REVIEW

**Comment by roystgnr** [comment]
Refs #1442

**Comment by friedmud** [comment]
Will do

**Comment by roystgnr** [comment]
@jessecarterMOOSE reports a significant benefit:

> for one particular case in 2D using 8 cpus, after applying the patch, the time spent in reinit() after the patch was about 20%-25% less! (depending on the initial mesh size)

And IMHO even if he's on a corner case, that's worth an extra 80 lines of code complication, so unless someone screams I'll probably merge this to master this weekend.

**Comment by jessecarterMOOSE** [comment]
I'd like to test if that figure applies more generally for other cases, but I'm pleased with the speedups I've seen so far.

However, does this fix @friedmud 's original issue regarding memory usage? 

Or maybe the problems are one in the same. You know what they say - "time is memory", or something like that.

**Comment by roystgnr** [comment]
> However, does this fix @friedmud 's original issue regarding memory usage?

It's at least a step in the right direction, unless I misunderstood: the issue wasn't memory usage, it was memory usage *patterns*.  We weren't leaking memory, or using too much memory; what we were doing was hitting the heap memory allocator and deallocator far too frequently, thereby killing CPU performance.

**Comment by roystgnr** [comment]
I'm going to wait until after #1459 goes in before merging, though: I don't *expect* any conflicts between it and the other ready PRs, but a critical-feature addition is more urgent than performance fixes or convenience-feature additions, so best to get that one in first.

**Comment by jessecarterMOOSE** [comment]
Makes sense to me :+1:

**Pull request merged**
