### PR TITLE
enabling intel support (maybe)

### PR DESCRIPTION
**Pull request by lindsayad**
@roystgnr

### CODE REVIEW

**Comment by jwpeterson** [comment]
I guess we don't have any Intel testing on moosebuild, eh? @roystgnr maybe we could get access to that compiler for automated testing via TACC? Maybe they wouldn't mind a nightly build or something else unobtrusive and it would help us catch stuff like this.

**Comment by lindsayad** [comment]
Lol obviously this "fix" would break standard compliant compliant compilers

**Comment by lindsayad** [comment]
Yea @jwpeterson I guess you were already gone when MOOSE decided to abandon intel compiler support? [This thread](https://github.com/idaholab/moose/issues/12713) is actually pretty good

**Comment by jwpeterson** [comment]
It looks like you are colliding with the built-in function for adding together integers? Is the issue that Intel does not implement the enum as an int or something?
```
../src/base/dof_map.C:2375:56: error: use of overloaded operator '+' is ambiguous (with operand types 'libMesh::OrderWrapper' and 'int')
      fe_type.order = static_cast<Order>(fe_type.order + p_level);
                                         ~~~~~~~~~~~~~ ^ ~~~~~~~
./include/libmesh/fe_type.h:89:9: note: candidate function
  Order operator+(unsigned int rhs)
        ^
../src/base/dof_map.C:2375:56: note: built-in candidate operator+(int, int)
      fe_type.order = static_cast<Order>(fe_type.order + p_level);
                                                       ^
```


> This thread is actually pretty good

Thanks, I hadn't seen that. You can't spell "Intel Compilers" without ICE.

"Impact: A feeling of rejoice among our users" :laughing:

**Comment by jwpeterson** [comment]
But that raises the question: even if you fix this issue, isn't it hopeless to get Intel working with the rest of MOOSE?

**Comment by lindsayad** [comment]
This was the error with libmesh master:
```
In file included from ./include/libmesh/fe_base.h(26),
                 from ./include/libmesh/fem_context.h(27),
                 from ./include/libmesh/fem_function_base.h(26),
                 from /scratch/lindad/moose/scripts/../libmesh/src/apps/L2system.h(19),
                 from /scratch/lindad/moose/scripts/../libmesh/src/apps/calculator.C(28):
./include/libmesh/fe_abstract.h(443): error: more than one operator "+" matches these operands:
            built-in operator "arithmetic + arithmetic"
            function "operator+(const PetscInt={int} &, const PetscComplex &)"
            operand types are: const libMesh::OrderWrapper + const unsigned int
    Order get_order()  const { return static_cast<Order>(fe_type.order + _p_level); }
```
Intel thought the overload with only builtin operands was no more qualified apparently than a conversion of `unsigned int` to `std::complex<double`

**Comment by lindsayad** [comment]
> "Impact: A feeling of rejoice among our users" laughing

Hahaha Jason actually felt really bad/guilty about his ticket summary after Jeff Hammond responded.

> But that raises the question: even if you fix this issue, isn't it hopeless to get Intel working with the rest of MOOSE?

If we can fix the libMesh compile issues, I don't expect the MOOSE build issues to be any worse

**Comment by roystgnr** [comment]
> Hahaha Jason actually felt really bad/guilty about his ticket summary after Jeff Hammond responded.

Wow, no kidding.

I think if I had the ear of the Intel compiler guys, I'd beg for them to finally start defaulting to fp model precise instead of fast, and to make sure precise is truly perfectly IEEE754 compliant.  There's a NASA presentation to the effect of "how not to let intel screw up your floating point code" dating back to 2008, I first learned about it when it bit me somewhere around 2013, and I'm pretty sure it's *still* biting people to this day (there's a ticket on that big Covid19 sim code about irreproduceability with different compiler AVX options which looks awfully like how fp model "fast" manifests).

That doesn't really mess with us (so few users run in serial with 1 thread that we never demand to reproduce gold results to better than 1e-10 or whatever anyway) but I feel bad for each new generation of programmers who expect computers to do exactly what they're told to and is disillusioned for the first time.

**Comment by roystgnr** [comment]
I'm not going to be using --enable-werror with Intel any time soon, but looks like at least that's not their fault; they're complaining about a function hidden by CppUnit::TextTestRunner::run, reasonably at first glance.

**Comment by roystgnr** [comment]
Rebased on master; we were a couple hundred commits behind and I don't want to chase any red herrings.

**Comment by permcody** [comment]
Doesn't @pbauman work for Intel now? I'm sure he can personally solve all of our Intel compiler woes 😄

**Comment by roystgnr** [comment]
Paul's at AMD.  Their only influence over Intel compiler failures is via FTC lawsuits.

**Comment by jwpeterson** [comment]
Where's the AMD C++ compiler? amdic++

**Comment by pbauman** [comment]
**> Where's the AMD C++ compiler? amdic++**

(I'm assuming this was asked with some seriousness.)

This is almost the worst possible time to ask about AMD compilers (long story). Depending on who you talk to, there's 3--5 compilers. The short answer is that most everything is being (or is) upstreamed to LLVM/clang. The includes HIP support (GPU language that's very similar to CUDA), device OpenMP offload, and OpenCL. There is some CPU sauce (specifically for AMD CPUs) that is not currently (and may never be) upstreamed to LLVM. That compiler is based on/forked from LLVM/clang and called AOCC. You can download it for free.

**Comment by pbauman** [comment]
And my solution at U. Buffalo to Intel compiler woes was don't use the Intel compiler. :)

**Comment by permcody** [comment]
Oops - Mixing up AMD with Intel? Thems fightin' words....

**Comment by jwpeterson** [comment]
> (I'm assuming this was asked with some seriousness.)

That's when you know that a joke has really landed :laughing:

**Comment by lindsayad** [comment]
Just to share with the general audience, I can't even run `make check` successfully PETSc with Intel 2019. I [posted this](https://lists.mcs.anl.gov/pipermail/petsc-users/2020-May/041045.html) on the petsc mailing list, and their recommendation was to roll back to 2018. Nice

**Comment by roystgnr** [comment]
At least the PETSc people are specifically complaining about the Intel MPI.  A regression there isn't quite as embarrassing as in the compiler itself ... although you'd think that PETSc would be one of the first things they'd double check against...

**Comment by roystgnr** [comment]
@lindsayad, could you let me know what error f08536b fixed?  Even libMesh master compiles just fine for me against Intel 19.0 or 18.0, so long as I disable MetaPhysicL.

**Comment by lindsayad** [comment]
It fixed [this one](https://github.com/libMesh/libmesh/pull/2565#issuecomment-627423526). I don't even know where that second overload is coming from. This was with `CXX=mpiicpc`. What are you using?

**Comment by roystgnr** [comment]
```
$ contrib/bin/libmesh-config --cxx
mpicxx
roystgnr@zappa:(intel-compile) ~/libmesh/git/intel
$ mpicxx --version
icpc (ICC) 19.0.5.281 20190815
```

What version are you on?  And have you tried with just icpc without MPI?  I can't imagine the Intel 19 MPI being so bad that it actually breaks C++ parsing, but...

**Comment by lindsayad** [comment]
What MPI implementation are you using? I'm going to have to build my own
mpi since on our own intel module either comes with an `mpicxx` backed by
gcc or the Intel MPI:

lindad@lemhi2:~$ module load
impi/2019.3.199-iccifort-2019.3.199-GCC-8.2.0-2.31.1
lindad@lemhi2:~$ which mpicxx
/apps/local/easybuild/software/impi/2019.3.199-iccifort-2019.3.199-GCC-8.2.0-2.31.1/intel64/bin/mpicxx
lindad@lemhi2:~$ mpicxx --version
g++ (GCC) 8.2.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

lindad@lemhi2:~$ mpiicpc --version
icpc (ICC) 19.0.3.199 20190206
Copyright (C) 1985-2019 Intel Corporation.  All rights reserved.

**Comment by roystgnr** [comment]
OpenMPI 3.0.0, though I'm pretty sure I've built libMesh with intel and mpich2 recently enough that it would have hit any OrderWrapper weirdness.  I haven't used Intel MPI.

I do seem to have a few patch levels you don't on the Intel compiler, though.  Any chance this was a bug in your compiler version which they since fixed?

**Comment by lindsayad** [comment]
We'll find out!

**Comment by lindsayad** [comment]
Yea I still get the same garbage  with openmpi 3.0.0/intel 19.0.3.199 2019206
```
/scratch/lindad/moose/scripts/../libmesh/src/error_estimation/hp_coarsentest.C(515): error: more than one operator "+" matches these operands:
            built-in operator "arithmetic + arithmetic"
            function "operator+(const PetscInt={int} &, const PetscComplex &)"
            operand types are: const libMesh::OrderWrapper + unsigned int
              static_cast<Order>(fe_type.order + elem->p_level() + 1);
```
Woof. Time to talk to the hpc admins

**Comment by lindsayad** [comment]
Anyway it sounds like the issue isn't really us, so I'm closing this

**Comment by roystgnr** [comment]
The fix in 1f0de31 is our fault, but I'm going to have to add a slightly more extensive fix to handle Intel 20 (which our admin was installing right as you opened this ticket, by wacky coincidence) too, so I'll put that in a separate PR after I'm sure there are no other problems (aside from MetaPhysicL; not sure if I'm excited or afraid to see whether Intel 20 works with it) there.

I'm actually happy with adding reasonably small workarounds to fix "issue isn't really us" cases, but if my guess is right and the issue has been fixed in a patch release then "talk to the hpc admins" is better than any workaround.  If you can get the same error from 19.0.5 or later then we ought to try to work around it ourselves, but I'm really hoping that's not the case since I can't replicate the problem.

**Comment by lindsayad** [comment]
I was going to ask about MetaPhysicL...it sounded as if you ran into kind of a road-block on that one even with your newish Intel 2019. If that's the case, then we're really pretty much screwed in MOOSE because we require MetaPhysicL. It's not a big loss to me, but @permcody and Mark DeHart are going to be sad

**Comment by roystgnr** [comment]
I did, but I'm not yet convinced that there isn't a workaround there.

**Comment by roystgnr** [comment]
Experimenting with Intel 20 with --disable-metaphysicl, I'm seeing a segfault in our unit tests in opt mode that I don't hit in dbg or devel modes.  I'm trying out different compiler options to try and get to something I can debug, but I think my attitude toward the MetaPhysicL issue is going to *very* much depend on whether it turns out that icpc has heroically exposed undefined behavior we need to fix or whether it has just inconveniently broken in a hard-to-diagnose way.

**Comment by roystgnr** [comment]
Okay, I officially give up here.  I can't find any combination of flags with Intel 20 that gives me access to variables in gdb while still reproducing the segfault.  And what's worse, I can avoid the segfault just by adding cout debugging!  There'll be a huge mea culpa if we ever find undefined behavior in ```GenericProjector::SubProjector::construct_projection```, but unless or until that happens I'm going to sleep easy without wasting more time on what I'm now pretty confident is a compiler bug.

**Comment by lindsayad** [comment]
> Okay, I officially give up here. I can't find any combination of flags with Intel 20 that gives me access to variables in gdb while still reproducing the segfault. And what's worse, I can avoid the segfault just by adding cout debugging! There'll be a huge mea culpa if we ever find undefined behavior in `GenericProjector::SubProjector::construct_projection`, but unless or until that happens I'm going to sleep easy without wasting more time on what I'm now pretty confident is a compiler bug.

Thanks @roystgnr for looking into this. To be clear you were not able to compile with `--enable-metaphysicl` for *any* intel versions?

**Comment by roystgnr** [comment]
Actually, I can't remember whether I tried MetaPhysicL with Intel 20 or not.  IIRC, I disabled it to make sure Intel 19 worked with everything else, then I switched to 20, then I hit this Heisenbug with 20, then I spent days on that, then capillaries started bursting in my eyeballs, and now here we are.  I guess my official position on MetaPhysicL vs icpc 20 isn't "yes" or "no" so much as "I no longer care".

**Pull request closed without merging**
