### PR TITLE
Fixes for 2d Nédélec one implementation and provided example

### PR DESCRIPTION
**Pull request by nmnobre**
Hi,

Just a few small fixes pertaining Nédélec one elements.
To my untrained eyes - I've just started playing with libMesh - it seems like TRI7 wasn't being properly distinguished from TRI6.
Apologies if I got anything wrong. :)

Cheers,
-Nuno

### CODE REVIEW

**Comment by roystgnr** [comment]
This all looks good to me.  The failing "Test MOOSE min gcc" is an unrelated downstream problem we're clearing up; this should be good to merge once everything else is clear.

**Comment by nmnobre** [comment]
I think there might be something wrong with the output.
When trying to visualise the solution in Paraview, with TRI7 I can only see the boundaries, whereas with TRI6 I can see the whole domain as expected...

**Comment by nmnobre** [comment]
> I think there might be something wrong with the output of ex3.
> When trying to visualise the solution in Paraview, with TRI7 I can only see the solution at the boundaries, whereas with TRI6, QUAD8 and QUAD9 I can see the solution over the whole domain as expected...

I'm guessing that's why @pbauman wrote this way back then:
https://github.com/libMesh/libmesh/blob/4ae34d8f6c088ce992abcff8b31fef7077ae4c47/examples/vector_fe/vector_fe_ex3/vector_fe_ex3.C#L71-L73

The same happens with TET14. I'll revert the changes that allow the example to be run with TRI7, I'd just like to understand why this is a limitation? Do we need to forbid TRI7 and TET14 more assertively for Nedelec elements? What happens if someone tries to use them in their own problem specification? It _looks_ like a limitation when writing the output exodus file, but I can't seem to understand what's happening. :/

**Comment by jwpeterson** [comment]
I think the @pbauman comment may be referring to using `TRI6` vs `TRI3`? The `TRI7` element was added fairly recently by @roystgnr, and it's possible that there's some issue with the exo output for it. Can you let us know exactly how to reproduce the problem using vector_fe_ex3 and your branch?

**Comment by pbauman** [comment]
> I think the @pbauman comment may be referring to using TRI6 vs TRI3? 

Yeah, you need TRI6 because you need mid-edge nodes to use Nédélec elements.

**Comment by roystgnr** [comment]
I'd guess this is an Exodus output issue.  I have test coverage for internal correctness with `TRI7` but I don't think I've ever tried to visualize with it ... and it's possible that users haven't done that either.  There's not much point in using a `Tri7` by itself (the extra mid-element node does give you an extra bubble function to use for the geometric mapping, but for non-Lagrange FE shape functions we could already just store their mid-element shape function indices on the `Elem` itself); `Tri7` is mostly useful indirectly as a side element to allow higher-order 3D elements with triangular faces to have cubic and higher face DoFs.

**Comment by nmnobre** [comment]
> I think the @pbauman comment may be referring to using `TRI6` vs `TRI3`? The `TRI7` element was added fairly recently by @roystgnr, and it's possible that there's some issue with the exo output for it. Can you let us know exactly how to reproduce the problem using vector_fe_ex3 and your branch?

That actually makes a lot of sense, thank you. :)

To reproduce:
1) Build as per the readme;
2) Go to `<install_dir>/examples/vector_fe/ex3` and run `METHOD=dbg make`;
3) Run w/ `./example-dbg element_type=TRI6 -pc_type jacobi` and `mv out.e TRI6.e`;
4) Run w/ `./example-dbg element_type=TRI7 -pc_type jacobi` and `mv out.e TRI7.e`;
5) Open both `TRI6.e` and `TRI7.e` in Paraview and notice there's no bulk info for the latter.

**Comment by roystgnr** [comment]
> notice there's no bulk info for the latter

I'm not sure what that means, but I'm certainly noticing a mess.  If I use the IOSS Reader option in Paraview to open TRI7.e, I get a failure from vtkIOSSUtilities.cxx, "Element of topology 'tri7' with 7 nodes is not supported.".  If I use the Legacy ExodusII Reader option, I get garbage.  It's as if something isn't advancing fast enough through node indices, and so we're just getting a bunch of tangled triangles attached to half the nodes.

This is with Paraview 5.10.1 - what version (and what reader option) are you using?

**Comment by roystgnr** [comment]
I'm looking at the `ncdump` output of the most simple case, `grid_size=1`, and it looks fine to me.  Nodes all in the right places, `num_nod_per_el1 = 7`, connectivity matching the `TRI7` picture in https://sandialabs.github.io/seacas-docs/exodusII-new.pdf

**Comment by jwpeterson** [comment]
So dow we think this is a Paraview bug? When we previously had an issue with PRISM18 elements in #2882, [acbauer](https://github.com/acbauer) was able to get a fix into Paraview upstream for us.

**Comment by nmnobre** [comment]
> > notice there's no bulk info for the latter
> 
> I'm not sure what that means

The boundary data is visualisable and correct, everything else, i.e. on the inner points of the domain, is missing.

> This is with Paraview 5.10.1 - what version (and what reader option) are you using?

5.11.1, but I don't get an option to select a reader?

> Oh, and what Exodus version? I'm on a 5.22 build here.

Same, as provided with libMesh w/o any tricks.

> I'm looking at the ncdump output of the most simple case, grid_size=1, and it looks fine to me.

Oh I was wondering if something like that existed! I was using a hex editor... 😰
How does this work though, is an Exodus file format basically a netCDF file?

> So do we think this is a Paraview bug?

VisIt doesn't seem to like it either. They both use VTK though...

**Comment by roystgnr** [comment]
> The boundary data is visualisable and correct, everything else, i.e. on the inner points of the domain, is missing.

This sounds almost as if it's only plotting EDGE3 boundaries and just plain giving up on the TRI7s.  It's weird that you wouldn't get an error message, though.  Unless maybe you're just not an old person like me, so you're using one of those new-fangled "gooeys" to launch Paraview?  I actually only see the error message in the console from where I've been running `paraview foo.e`; in the Paraview window itself I just get what looks like an empty file loaded.

> 5.11.1, but I don't get an option to select a reader?

That requires a bit of hassle.  You have to go to Tools, Manage Plugins, and load (and/or set to auto-load) the LegacyExodusReader plugin there.  They managed a nice quick fix for the IOSS bug that had us figure this all out, but I'm still using the older Paraview (prebuilt Ubuntu package) so I'm still using the legacy reader.

> How does this work though, is an Exodus file format basically a netCDF file?

Depends on the version and configuration, but yeah, it's always either NetCDF or HDF5 under the hood.

**Comment by jwpeterson** [comment]
FYI @nmnobre I sent you an invite to join the group whose libMesh PRs are tested automatically. For now I will start them all manually.

**Comment by nmnobre** [comment]
> This sounds almost as if it's only plotting EDGE3 boundaries and just plain giving up on the TRI7s. It's weird that you wouldn't get an error message, though. Unless maybe you're just not an old person like me, so you're using one of those new-fangled "gooeys" to launch Paraview?

I am, I feel like a WIMP now. 😩

> That requires a bit of hassle. You have to go to Tools, Manage Plugins, and load (and/or set to auto-load) the LegacyExodusReader plugin there. They managed a nice quick fix for the IOSS bug that had us figure this all out, but I'm still using the older Paraview (prebuilt Ubuntu package) so I'm still using the legacy reader.

Thanks! I've enabled the LegacyExodusReader, and as you said, it looks like a mess:

Screenshot 2023-08-17 at 20 41 54

When I use the IOSS Reader, it's as if there's no data (I have to select the boundary sets to actually see something).

**Comment by roystgnr** [comment]
Okay, your experience and mine seem to match.  Should we file a Paraview bug report?  If I strip out variables/nodes/sidesets on a 2-triangle mesh, I get down to 60 lines of ncdump output, and yet it's still clear that we hit an assertion with IOSS and we're missing a triangle with the legacy display.

**Comment by nmnobre** [comment]
> Okay, your experience and mine seem to match. Should we file a Paraview bug report? If I strip out variables/nodes/sidesets on a 2-triangle mesh, I get down to 60 lines of ncdump output, and yet it's still clear that we hit an assertion with IOSS and we're missing a triangle with the legacy display.

Hang on, see https://gitlab.kitware.com/vtk/vtk/-/commit/f80cc5c6e206b3a9f0a442566cf4ceb3c4d8b8f8. It seems Paraview is just shipping with an old version of VTK w/o the newly added support for TRI7.

**Comment by roystgnr** [comment]
Ooh, that could do it.  I wouldn't want to bother to file a bug report for the legacy reader alone.

**Comment by roystgnr** [comment]
I'll hang on to my test cases, though; if you upgrade and it's still giving you problems then we can still report them after that.  With 75 lines we can get an 8-triangle file, and that's enough to exhibit tangling triangles, not just missing ones.

**Comment by nmnobre** [comment]
> Ooh, that could do it. I wouldn't want to bother to file a bug report for the legacy reader alone.

I'll try to build Paraview from source (wish me luck) and see if that sorts it!

**Comment by nmnobre** [comment]
Paraview @[31dbe2d6](https://gitlab.kitware.com/paraview/paraview/-/tree/31dbe2d6832af83b07449c6e764cd48c47d9ba70) w/ VTK @[40c19ea4](https://gitlab.kitware.com/vtk/vtk/-/tree/40c19ea4e8f67c0edd104b4578ba0bc8efcac4ed). 🎉

Plotted as points so you can see (maybe with some effort) all the nodes in their rightful place!

Screenshot 2023-08-17 at 23 30 17

**Review by jwpeterson — APPROVED** [review]
The changes in this PR look good to me, unless you wanted to add a comment somewhere in the example noting that the output will not look correct unless one is using a sufficiently new version of Paraview.

**Comment by nmnobre** [comment]
Unfortunately, TET14 isn't a thing in VTK, they only have TET15.
Maybe in the same way they treat TET10 and TET11 the same, they could also treat TET14 and TET15 the same...
Or conversely, why do we have TET14 and not TET15, but then have no HEX26 but do have HEX27?

**Comment by roystgnr** [comment]
The root answer to "why don't we have" is usually either "someone made a contrary assumption in like 2007 and now we'd break a hundred classes if we changed it" (e.g. anisotropic h refinement) or "Roy's lazy" (e.g. probably everything else).

The proximate answer in the case of TET14 vs TET15, though, is that TET14 gives us mid-side nodes, which we need if we want to support FE types with degrees of freedom whose support is restricted to the two element sharing a side, but TET15 only adds a central node, which we don't need because we can already store bubble function degrees of freedom on the element itself.  Technically we could also get away with HEX26 the same way, but we have HEX27 because people do like the full triquadratic LAGRANGE mapping functions, and for LAGRANGE we keep all our DoFs nodal.

**Pull request merged**
