### PR TITLE
fatol and frtol are going away in the next PETSc release

### LINKED ISSUE #723: Build failure with PETSc master
When I try to build the newest libmesh GIT source together with PETSc master, I get the following error:

<pre>
src/solvers/tao_optimization_solver.C: In constructor ‘libMesh::TaoOptimizationSolver<T>::TaoOptimizationSolver(libMesh::OptimizationSystem&)’:
src/solvers/tao_optimization_solver.C:418:11: error: ‘TAO_CONVERGED_FATOL’ was not declared in this scope
   _reason(TAO_CONVERGED_FATOL/*==0*/) // Arbitrary initial value...
           ^
src/solvers/tao_optimization_solver.C: In instantiation of ‘void libMesh::TaoOptimizationSolver<T>::solve() [with T = double]’:
src/solvers/tao_optimization_solver.C:654:16:   required from here
src/solvers/tao_optimization_solver.C:502:26: error: too many arguments to function ‘PetscErrorCode TaoSetTolerances(Tao, PetscReal, PetscReal, PetscReal)’
   ierr = TaoSetTolerances(_tao,
                          ^
In file included from /home/tmac/usr/stow/petsc-real-dbg/include/petsc.h:27:0,
                 from ./include/libmesh/petsc_macro.h:93,
                 from ./include/libmesh/petsc_vector.h:31,
                 from src/solvers/tao_optimization_solver.C:28:
/home/tmac/usr/stow/petsc-real-dbg/include/petsctao.h:172:29: note: declared here
 PETSC_EXTERN PetscErrorCode TaoSetTolerances(Tao, PetscReal, PetscReal, PetscReal);
                             ^
Makefile:15865: recipe for target 'src/solvers/libmesh_dbg_la-tao_optimization_solver.lo' failed
make[2]: *** [src/solvers/libmesh_dbg_la-tao_optimization_solver.lo] Error 1
make[2]: Leaving directory '/home/tmac/src/upstream/libmesh'
</pre>

It is probably due to PETSc commit e52336c:

https://bitbucket.org/petsc/petsc/diff/include/petsctao.h?diff2=e52336cb213e&at=hzhang/matpackage-erroriffpe

### PR DESCRIPTION
**Pull request by jwpeterson**
@dknez, looks like we currently set `frtol`, should we maybe change to setting `grtol`?

Relevant [diff](https://bitbucket.org/petsc/petsc/diff/include/petsctao.h?diff2=e52336cb213e).

Closes #723.

### CODE REVIEW

**Comment by dknez** [comment]
Sure, let's change to grtol. As long as the examples behave the same, I'm happy.

**Comment by jwpeterson** [comment]
I checked and neither of the examples' behavior changes with the tolerance changed to grtol under PETSc 3.6.1 release.  I'll take another look in the next release.  Presumably that will be 3.7.0 since they are changing interfaces...

**Comment by dknez** [comment]
OK, sounds good. Thanks for taking care of this.

**Comment by pbauman** [comment]
Oh wait, sorry. I was looking at maint and not at master. It looks like it's in master but didn't get in the 3.6.3 release. I'll make a PR to bump the number then.

**Pull request merged**
