### PR TITLE
Implement doubly-checked lock for _get_array

### PR DESCRIPTION
**Pull request by lindsayad**
This removes the condition variable and `notify_all` and allows us to
remove the `std::atomic` on `_values_read_only`. This reports
ThreadSanitizer clean and is in the spirit of what @friedmud initially
implemented

### CODE REVIEW

**Review by jwpeterson — APPROVED** [review]
I think this ticks all the boxes: 
:heavy_check_mark:  similar to what we had before in terms of performance
:heavy_check_mark:  simpler/cleaner than what we had before
:heavy_check_mark:  ThreadSanitizer safe
but the `std::memory_order` stuff is very complicated IMO, I don't pretend to understand exactly what is going on here.

**Comment by lindsayad** [comment]
I want to take a little time to understand *why* it's safe to read from `_values_read_only` on thread A towards the top of the method when in my mind a writer thread B may be writing to `_values_read_only` later in the method. E.g. the only way I don't see there being a race is if there's a guarantee that if the `acquire` happens on thread A before the `release` on thread B, then thread A is guaranteed to not see the memory writes of thread B ... but I have only ever seen articles about the reverse, e.g. it's guaranteed that if `release` happens on thread B before `acquire` happens on thread A, then A is guaranteed to see all the writes from thread B

**Comment by lindsayad** [comment]
Or at least `ThreadSanitizer` regards this as safe, but I'm wondering if it's a false negative

**Comment by lindsayad** [comment]
Sigh... the program below does indeed report ThreadSanitizer unclean for read and write to `payload`, so it is as @friedmud said ... ThreadSanitizer can report as clean when there's still a possibility for a race. If you replace the arguments to `fib` with 0 and remove the assert, then the program registers as clean, e.g. false negative.
```c++
#include <thread>
#include <atomic>
#include <mutex>
#include <cassert>

std::mutex cv_m;
std::atomic<bool> done = false;
bool payload = false;

int
fib(int n)
{
  if (n <= 1)
    return n;
  return fib(n - 1) + fib(n - 2);
}

void
foo(const int thread_id)
{
  const bool initially_done = done.load(std::memory_order_acquire);
  assert(!initially_done);

  if (!initially_done)
  {
    // Make thread 1 wait longer, but make both threads wait such that initially_done should be                       
    // false for both                                                                                                 
    if (thread_id)
      fib(42);
    else
      fib(30);

    const auto val = payload;
  }

  if (!initially_done)
  {
    std::lock_guard<std::mutex> lock(cv_m);
    if (!done.load(std::memory_order_relaxed))
    {
      payload = true;
      done.store(true, std::memory_order_release);
    }
  }
}

int
main()
{
  std::thread t0(foo, 0), t1(foo, 1);
  t0.join();
  t1.join();
}
```
So even though this PR has reported as ThreadSanitizer clean in my testing, it should be subject to races for `_values_read_only` whenever `acquire` happens before `release`.

**Comment by lindsayad** [comment]
So basically I can never completely trust thread debugging tools 😭

**Comment by lindsayad** [comment]
So I think that we should actually still be good here because we only read `_values_read_only` if `_array_is_present`, e.g. we should not run into issue if we `acquire` before `release`. If we `acquire` before `release` and `!_array_is_present`, then we don't perform any reads of `_values_read_only` (that would then race with writes to `_values_read_only`). And if we `acquire` before `release` and `_array_is_present`, then we read `_values_read_only` but there are no writers to `_values_read_only` so no race. Our situation is akin to this code
```c++
int
fib(int n)
{
  if (n <= 1)
    return n;
  return fib(n - 1) + fib(n - 2);
}

void
getArray(const int thread_id)
{
  const bool initially_array_is_present = array_is_present.load(std::memory_order_acquire);
  assert(!initially_array_is_present);

  // Make thread 1 wait longer, but make both threads wait such that initially_array_is_present                       
  // should be false for both                                                                                         
  if (thread_id)
    fib(31);
  else
    fib(30);

  if (initially_array_is_present)
    const auto value = values_read_only;

  if (!initially_array_is_present)
  {
    std::lock_guard<std::mutex> lock(cv_m);
    if (!array_is_present.load(std::memory_order_relaxed))
    {
      values_read_only = true;
      array_is_present.store(true, std::memory_order_release);
    }
  }
```
where again I've made sure with the calls to `fib` that there would be a read-write race for `values_read_only` ***if*** the read wasn't protected by `initially_array_is_present`. If you don't protected the read of `values_read_only`, I checked and you get the `ThreadSanitizer` errors. So with this, I'm going to convert this back from draft

**Comment by roystgnr** [comment]
I also like the look of this ... and I'd also really like to see @friedmud's opinion before merging.

Should we create a unit test that constructs a petsc vector, reads an iteration count (or falls back on a tiny default), and just does that many `get_array()` and/or `get_array_read()` calls?  So then we could quickly try out something like `LIBMESH_OPTIONS='--re GetArray --get_array_n 500000 --n_threads 64' time make check -C tests` whenever we're afraid of a possible threaded performance regression?

**Comment by lindsayad** [comment]
I assume you'd want to interweave some operations that involve setting `_array_is_present = false`

**Comment by roystgnr** [comment]
Huh, yeah.  I should have thought a little harder before typing.  I'm actually not sure what kind of access pattern you'd want most, though, to maximize the contention triggered.

**Comment by friedmud** [comment]
I like this pattern - it's much cleaner than before and should still be very performant.  Thanks for doing all the work on this @lindsayad !

**Pull request merged**
