### PR TITLE
BoundaryInfo::add_elements()

### PR DESCRIPTION
**Pull request by roystgnr**
Since we should now support fun tricks with mixes of "interior" and "boundary" elements on the same mesh, let's add an easy way to put them into the same mesh.

This passes the FIN-S test suite, which was at least exhaustive enough of BoundaryInfo::sync() to catch bugs in my initial refactoring attempts.

### CODE REVIEW

**Comment by roystgnr** [comment]
No, wait; I can still get this to trigger a regression.

**Comment by roystgnr** [comment]
Looks like that was actually a bug introduced in #584

Everything seems to be working again; I'll merge tonight absent objections.

**Comment by jwpeterson** [comment]
IMO these three patches should be squashed together.  The first is a placeholder, the second adds implementation with bugs, the third fixes those bugs.

**Comment by roystgnr** [comment]
I'll squash the first two together.  But I'm afraid the third doesn't fix bugs from the first two, it fixes a bug I missed from a previous PR...

**Comment by jwpeterson** [comment]
> I'll squash the first two together. But I'm afraid the third doesn't fix bugs from the first two, it fixes a bug I missed from a previous PR...

I see, sorry, I missed your final comment there, somehow. Sounds good.

**Pull request merged**
