### PR TITLE
Fix missing includes in --disable-optional builds

### PR DESCRIPTION
**Pull request by jwpeterson**
The libmesh_make_unique macro is still required even with fparser disabled.

### CODE REVIEW

**Comment by jwpeterson** [comment]
This seems like it should have been caught by "Test No Optional" previously, but maybe that doesn't really disable fparser for some reason...

**Comment by jwpeterson** [comment]
Oh, most likely it was uncovered by shuffling around of headers in #2219.

**Comment by roystgnr** [comment]
Wow, thanks for catching these.  I should have been smart enough to try Test No Optional on #2219.

**Comment by roystgnr** [comment]
But wait, what's going on with all those LIBMESH_HAVE_PETSC wrappers?  I could swear I've run through the unit tests with Eigen sparse solvers recently.

**Comment by jwpeterson** [comment]
> But wait, what's going on with all those LIBMESH_HAVE_PETSC wrappers? I could swear I've run through the unit tests with Eigen sparse solvers recently.

Yes, technically you can run those unit tests as long as *any* linear solver is available. So the logic should be
```
 #if defined(LIBMESH_HAVE_PETSC) || defined(LIBMESH_HAVE_EIGEN) || defined...
```
but I was "compiling by CIVET" last night so I just went for the quick and dirty solution of checking for one particular linear solver package...

**Comment by roystgnr** [comment]
Ah, gotcha.  Let's wrap that logic into a single LIBMESH_HAVE_SOLVER, though, so we can keep the extra test coverage with non-PETSc solvers?  I know we'll only use it once in a blue moon, but it was pretty useful for me just recently.

**Comment by jwpeterson** [comment]
> Let's wrap that logic into a single LIBMESH_HAVE_SOLVER,

This sounds like it would be useful. It feels like it would naturally fit into libmesh_config.h, but we'd need configure to somehow write it for us. Maybe in libmesh_common.h?

**Comment by roystgnr** [comment]
Oh, I hate m4 too much to want to do this in configure.  I was just thinking
```
#if defined(LIBMESH_HAVE_PETSC) || defined(LIBMESH_HAVE_EIGEN) || defined...
#define LIBMESH_HAVE_SOLVER 1
#endif
```

I'd been picturing it in linear_solver.h, but I guess some of the nonlinear solver headers encapsulate that away?  libmesh_common.h seems too extreme.  system.h, since we're generally wondering whether we can expect anything out of system.solve()?

**Comment by jwpeterson** [comment]
> since we're generally wondering whether we can expect anything out of system.solve()?

In this case, the error comes from the constructor of `LinearImplicitSystem`, when it tries to call `LinearSolver<Number>::build()`. So, yeah, system.h would most likely be included anywhere that we'd reasonably want to use the macro.

**Pull request merged**
