### PR TITLE
Update eigen from 3.2.9 -> 3.3.9

### PR DESCRIPTION
**Pull request by lindsayad**
This will be necessary for #2842 because 3.2.9 contains some code deprecated in C++11 (and technically removed post C++11...GCC seems to allow it but clang does not)

### CODE REVIEW

**Comment by lindsayad** [comment]
wth this builds for me locally

**Review by roystgnr — APPROVED** [review]

**Comment by roystgnr** [comment]
> This will be necessary for #2842

Well ... in the interest of honesty: one option we have would be to change the default settings in #2842 so that we search for C++11 only, meaning that users will only get C++14 or C++17 if they explicitly request it or if they manually set flags for it or if they use a compiler that defaults to it.  That would still be sufficient for our own users, but without the risk of breaking things for users who don't have C++17-compatible code yet.  I think there's a good case to be made for taking this option.

However, with the current "try out C++17 first" settings we have an easy way to get CI to yell at us for our own (and our dependencies') C++17-incompatible code, and I'd like to take this opportunity to fix it all, for the sake of people who deliberately want to turn on C++17, whether we end up enabling C++17 by default or not.

**Comment by jwpeterson** [comment]
I'm getting a diff when I run ./bootstrap after this PR was merged:

```
diff --git a/contrib/eigen/3.3.9/Makefile.in b/contrib/eigen/3.3.9/Makefile.in
index b3f5de47a..cd48d6c26 100644
--- a/contrib/eigen/3.3.9/Makefile.in
+++ b/contrib/eigen/3.3.9/Makefile.in
@@ -97,18 +97,17 @@ ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
 am__aclocal_m4_deps =  \
        $(top_srcdir)/m4/autoconf-submodule/acsm_code_coverage.m4 \
        $(top_srcdir)/m4/autoconf-submodule/acsm_compiler_control_args.m4 \
-       $(top_srcdir)/m4/autoconf-submodule/acsm_cxx_compiler_standard.m4 \
        $(top_srcdir)/m4/autoconf-submodule/acsm_mpi.m4 \
        $(top_srcdir)/m4/autoconf-submodule/acsm_scrape_petsc_configure.m4 \
        $(top_srcdir)/m4/autoconf-submodule/acsm_summarize_env.m4 \
        $(top_srcdir)/m4/autoconf-submodule/acsm_test_sanitize_flags.m4 \
-       $(top_srcdir)/m4/autoconf-submodule/ax_cxx_compile_stdcxx.m4 \
        $(top_srcdir)/m4/autoconf-submodule/ax_prefix_config_h.m4 \
        $(top_srcdir)/m4/autoconf-submodule/ax_split_version.m4 \
        $(top_srcdir)/m4/ac_cxx_rtti.m4 $(top_srcdir)/m4/all_static.m4 \
        $(top_srcdir)/m4/ax_boost_base.m4 \
        $(top_srcdir)/m4/ax_check_compile_flag.m4 \
        $(top_srcdir)/m4/ax_compiler_vendor.m4 \
+       $(top_srcdir)/m4/ax_cxx_compile_stdcxx_11.m4 \
        $(top_srcdir)/m4/ax_gcc_archflag.m4 \
        $(top_srcdir)/m4/ax_gcc_x86_cpuid.m4 \
        $(top_srcdir)/m4/ax_openmp.m4 $(top_srcdir)/m4/ax_pthread.m4 \
@@ -317,8 +316,6 @@ GXX_VERSION = @GXX_VERSION@
 GZSTREAM_INCLUDE = @GZSTREAM_INCLUDE@
 GZSTREAM_LIB = @GZSTREAM_LIB@
 HAVE_CXX11 = @HAVE_CXX11@
-HAVE_CXX14 = @HAVE_CXX14@
-HAVE_CXX17 = @HAVE_CXX17@
 HAVE_DOT = @HAVE_DOT@
 HAVE_GCOV_TOOLS = @HAVE_GCOV_TOOLS@
 HDF5_CFLAGS = @HDF5_CFLAGS@
```
I think some of your other m4 changes made it in to this PR? I'll see if I can fix...

**Comment by jwpeterson** [comment]
I pushed a fix in 8f0c7eae0, but I guess it wasn't a big deal since none of the Makefiles or configure got broken by adding a non-existent m4 file to that Makefile list.

**Comment by roystgnr** [comment]
As we were discussing on the other ticket:

> For the complex-enabled testing (which uses Eigen Sparse solvers because PETSc is disabled in that config)
Before Eigen PR: 1 hour 50 minutes
After Eigen PR: 5 hours 53 minutes

Running things at home, it looks like the solves are proceeding fast enough, but in some cases *Jacobian assembly* is a problem.  I can run the same example-opt in fem_system_ex5 with PETSc and have it finish in 6 seconds (including 1.2 seconds of assembly) or with --use-eigen and have it finish in 400 seconds with Eigen (392 seconds of which is in Jacobian assembly).

**Comment by jwpeterson** [comment]
> For the complex-enabled testing (which uses Eigen Sparse solvers because PETSc is disabled in that config)
> Before Eigen PR: 1 hour 50 minutes
> After Eigen PR: 5 hours 53 minutes

FWIW, the 5 hours I quoted previously seems to be something of an outlier, the average time seems to be closer to 3 hours 20 minutes. Maybe different build node hardware causes that difference. Either way, updating Eigen added over an hour to the testing.

**Comment by lindsayad** [comment]
Ok I'm compiling some profiles. I accidentally profiled with pre-this-PR...but that will be good to see what slowed down!

**Comment by roystgnr** [comment]
Well that's interesting.  7a8ea6d06 was pre-this-PR, right?  But I'm still seeing near-400-second assembly times for a fem_system_ex5 example-opt Eigen run.  Perhaps we were always doing something wrong with our Eigen matrix sparsity pattern handling (at least in that example) but Eigen's handling it even worse now?

**Comment by lindsayad** [comment]
Pre eigen upgrade:
old-eigen-fem
Post eigen upgrade
new-eigen-fem

**Comment by lindsayad** [comment]
Yea `SparseMatrix::reserveInnerVectors` has ballooned 25x

**Comment by lindsayad** [comment]
Screenshot from 2021-02-04 12-15-20

**Comment by jwpeterson** [comment]
In the old graph there was a function called `SparseMatrix::insertUncompressed` that seems to be missing in the new graph. So I'd say they refactored `SparseMatrix::insert` at some point between the old an new versions... the two code snippets you posted look almost identical to me, except that `m_data.index` and `m_data.value` take way way longer in the new version.

I'm wondering if we should really be calling `reserveInnerVectors()` so much... maybe we are doing something wrong there.

**Comment by lindsayad** [comment]
The graphs can be a little confusing...sometimes intermediate calls get left out in one graph and not another. `insertUncompressed` is still getting called in both versions. I think this is the "offending" Eigen commit:
```
commit a9df28c95b42401fe4ac86313b85872200d05e4c
Author: Gael Guennebaud <g.gael@free.fr>
Date:   Fri Mar 13 21:00:21 2015 +0100

    SparseMatrix::insert: switch to a fully uncompressed mode if sequential insertion is not possible (otherwise an arbitrary large amount of memory was preallocated in some cases)

diff --git a/Eigen/src/SparseCore/SparseMatrix.h b/Eigen/src/SparseCore/SparseMatrix.h
index 0ba7e111a..4c3a47959 100644
--- a/Eigen/src/SparseCore/SparseMatrix.h
+++ b/Eigen/src/SparseCore/SparseMatrix.h
@@ -1172,8 +1172,12 @@ typename SparseMatrix<_Scalar,_Options,_Index>::Scalar& SparseMatrix<_Scalar,_Op
     return (m_data.value(p) = 0);
   }
   
-  // make sure the matrix is compatible to random un-compressed insertion:
-  m_data.resize(m_data.allocatedSize());
+  if(m_data.size() != m_data.allocatedSize())
+  {
+    // make sure the matrix is compatible to random un-compressed insertion:
+    m_data.resize(m_data.allocatedSize());
+    this->reserveInnerVectors(Array<StorageIndex,Dynamic,1>::Constant(2*m_outerSize, convert_index(m_outerSize)));
+  }
   
   return insertUncompressed(row,col);
 }
```

**Comment by jwpeterson** [comment]
Wait... how did you figure that out so quickly?

**Comment by lindsayad** [comment]
Uhm reverting that commit definitely wasn't the correct solution. I've been stuck at `Assembling the System` for multiple minutes now. So I did not figure it out so quickly :laughing:

**Comment by jwpeterson** [comment]
OK, but I mean how did you find that particular commit from 6 years ago so quickly?

**Comment by lindsayad** [comment]
Just `git log -S reserveInnerVectors`

**Comment by lindsayad** [comment]
Ok `insertUncompressed` is unchanged to my eyes between versions, but `insert` has changed drastically. Old `insert`:
```c++
    Scalar& insert(Index row, Index col)
    {
      eigen_assert(row>=0 && row<rows() && col>=0 && col<cols());

      if(isCompressed())
      {
        reserve(Matrix<Index,Dynamic,1>::Constant(outerSize(), 2));
      }
      return insertUncompressed(row,col);
    }
```
New insert, which includes that `reserveInnerVectors` call that takes all our simulation time:
```c++
typename SparseMatrix<_Scalar,_Options,_StorageIndex>::Scalar& SparseMatrix<_Scalar,_Options,_StorageIndex>::insert(Index row, Index col)
{
  eigen_assert(row>=0 && row<rows() && col>=0 && col<cols());
  
  const Index outer = IsRowMajor ? row : col;
  const Index inner = IsRowMajor ? col : row;
  
  if(isCompressed())
  {
    if(nonZeros()==0)
    {
      // reserve space if not already done
      if(m_data.allocatedSize()==0)
        m_data.reserve(2*m_innerSize);
      
      // turn the matrix into non-compressed mode
      m_innerNonZeros = static_cast<StorageIndex*>(std::malloc(m_outerSize * sizeof(StorageIndex)));
      if(!m_innerNonZeros) internal::throw_std_bad_alloc();
      
      memset(m_innerNonZeros, 0, (m_outerSize)*sizeof(StorageIndex));
      
      // pack all inner-vectors to the end of the pre-allocated space
      // and allocate the entire free-space to the first inner-vector
      StorageIndex end = convert_index(m_data.allocatedSize());
      for(Index j=1; j<=m_outerSize; ++j)
        m_outerIndex[j] = end;
    }
    else
    {
      // turn the matrix into non-compressed mode
      m_innerNonZeros = static_cast<StorageIndex*>(std::malloc(m_outerSize * sizeof(StorageIndex)));
      if(!m_innerNonZeros) internal::throw_std_bad_alloc();
      for(Index j=0; j<m_outerSize; ++j)
        m_innerNonZeros[j] = m_outerIndex[j+1]-m_outerIndex[j];
    }
  }
  
  // check whether we can do a fast "push back" insertion
  Index data_end = m_data.allocatedSize();
  
  // First case: we are filling a new inner vector which is packed at the end.
  // We assume that all remaining inner-vectors are also empty and packed to the end.
  if(m_outerIndex[outer]==data_end)
  {
    eigen_internal_assert(m_innerNonZeros[outer]==0);
    
    // pack previous empty inner-vectors to end of the used-space
    // and allocate the entire free-space to the current inner-vector.
    StorageIndex p = convert_index(m_data.size());
    Index j = outer;
    while(j>=0 && m_innerNonZeros[j]==0)
      m_outerIndex[j--] = p;
    
    // push back the new element
    ++m_innerNonZeros[outer];
    m_data.append(Scalar(0), inner);
    
    // check for reallocation
    if(data_end != m_data.allocatedSize())
    {
      // m_data has been reallocated
      //  -> move remaining inner-vectors back to the end of the free-space
      //     so that the entire free-space is allocated to the current inner-vector.
      eigen_internal_assert(data_end < m_data.allocatedSize());
      StorageIndex new_end = convert_index(m_data.allocatedSize());
      for(Index k=outer+1; k<=m_outerSize; ++k)
        if(m_outerIndex[k]==data_end)
          m_outerIndex[k] = new_end;
    }
    return m_data.value(p);
  }
  
  // Second case: the next inner-vector is packed to the end
  // and the current inner-vector end match the used-space.
  if(m_outerIndex[outer+1]==data_end && m_outerIndex[outer]+m_innerNonZeros[outer]==m_data.size())
  {
    eigen_internal_assert(outer+1==m_outerSize || m_innerNonZeros[outer+1]==0);
    
    // add space for the new element
    ++m_innerNonZeros[outer];
    m_data.resize(m_data.size()+1);
    
    // check for reallocation
    if(data_end != m_data.allocatedSize())
    {
      // m_data has been reallocated
      //  -> move remaining inner-vectors back to the end of the free-space
      //     so that the entire free-space is allocated to the current inner-vector.
      eigen_internal_assert(data_end < m_data.allocatedSize());
      StorageIndex new_end = convert_index(m_data.allocatedSize());
      for(Index k=outer+1; k<=m_outerSize; ++k)
        if(m_outerIndex[k]==data_end)
          m_outerIndex[k] = new_end;
    }
    
    // and insert it at the right position (sorted insertion)
    Index startId = m_outerIndex[outer];
    Index p = m_outerIndex[outer]+m_innerNonZeros[outer]-1;
    while ( (p > startId) && (m_data.index(p-1) > inner) )
    {
      m_data.index(p) = m_data.index(p-1);
      m_data.value(p) = m_data.value(p-1);
      --p;
    }
    
    m_data.index(p) = convert_index(inner);
    return (m_data.value(p) = 0);
  }
  
  if(m_data.size() != m_data.allocatedSize())
  {
    // make sure the matrix is compatible to random un-compressed insertion:
    m_data.resize(m_data.allocatedSize());
    this->reserveInnerVectors(Array<StorageIndex,Dynamic,1>::Constant(m_outerSize, 2));
  }
  
  return insertUncompressed(row,col);
}
```

**Comment by lindsayad** [comment]
Based on the doxygen, we probably need to be reserving before calling `coeffRef` I'm guessing, so like @roystgnr said we're probably not communicating our sparsity pattern correctly
```
    /** \returns a reference to a novel non zero coefficient with coordinates \a row x \a col.
      * The non zero coefficient must \b not already exist.
      *
      * If the matrix \c *this is in compressed mode, then \c *this is turned into uncompressed
      * mode while reserving room for 2 x this->innerSize() non zeros if reserve(Index) has not been called earlier.
      * In this case, the insertion procedure is optimized for a \e sequential insertion mode where elements are assumed to be
      * inserted by increasing outer-indices.
      * 
      * If that's not the case, then it is strongly recommended to either use a triplet-list to assemble the matrix, or to first
      * call reserve(const SizesType &) to reserve the appropriate number of non-zero elements per inner vector.
      *
      * Assuming memory has been appropriately reserved, this function performs a sorted insertion in O(1)
      * if the elements of each inner vector are inserted in increasing inner index order, and in O(nnz_j) for a random insertion.
      *
      */
```

**Comment by jwpeterson** [comment]
We do call `reserve()` in EigenSparseMatrix::init()
```
_mat.reserve(Eigen::Matrix<numeric_index_type, Eigen::Dynamic, 1>::Constant(m_in,nnz));
```
Maybe our `nnz` is way off or something.

I'm also wondering about this compressed vs. uncompressed distinction... I don't see any reference to it in our stuff so maybe we aren't accounting for that correctly.

**Comment by lindsayad** [comment]
Who wants to dig into it? I don't want us all to be duplicating effort. I'm guessing we probably want to get this addressed so that we can compile with all c++14 compilers (as opposed to reverting). @jwpeterson I think this was more motivated by an INL push to allow c++14/c++17 code in MOOSE, so don't feel like you have to be the one who spends time on it.

**Comment by jwpeterson** [comment]
OK, I was not planning on digging into it in detail, just throwing out half-baked ideas.

**Comment by lindsayad** [comment]
That's how I do all my work in Seattle...half-baked :smile:

**Comment by lindsayad** [comment]
At the time we call `reserve` Eigen thinks we are compressed, so @jwpeterson one of your half-baked ideas seems promising

**Comment by jwpeterson** [comment]
> one of your half-baked ideas seems promising

halfbaked

**Comment by lindsayad** [comment]
Fix in #2851

**Pull request merged**
