### PR TITLE
Update Nanoflann

### LINKED ISSUE #1563: Update nanoflann.hpp
Please let's try to get a more up to date nanoflann header into libmesh. The one in contrib seems to be five years behind. I'll see if the current one works as a drop in replacement. The API has some subtle but useful changes.

### PR DESCRIPTION
**Pull request by dschwen**
Let's run this through the test system...

Closes #1563

### CODE REVIEW

**Comment by jwpeterson** [comment]
FYI the GRINS-devel failures are not going to be related to your PR.

**Comment by dschwen** [comment]
Thanks, I was a bit puzzled by those.

**Comment by pbauman** [comment]
Yes, that is because I started covering the test mentioned #1559 and a fix hasn't been made yet.

**Comment by pbauman** [comment]
If it would make everyone feel warmer and fuzzier and I can change that part of the recipe to allow to fail. I just didn't want it to get lost.

**Comment by dschwen** [comment]
Btw. @jwpeterson this dumps the entire nanoflann distribution into contrib. It adds 130k lines, which seems excessive. Did nanoflann just grow that much or did you leave out stuff previously. Technically we just need the header and a handful of tests.

**Comment by jwpeterson** [comment]
> Did nanoflann just grow that much or did you leave out stuff previously.

The original nanoflann import was ef53f149e6fa. It did not contain all the .dat files you are checking in, so maybe we don't really need those. The testing suite looks like it got a bit more extensive.

**Comment by jwpeterson** [comment]
> If it would make everyone feel warmer and fuzzier and I can change that part of the recipe to allow to fail. I just didn't want it to get lost.

I think we can keep the red X for now, but we run the risk of introducing additional GRINS-devel failures without people noticing, simply because they assume it's always the fem_system_ex2 thing.

**Comment by dschwen** [comment]
I threw out a ton of stuff (160k lines). We are not running the tests in `make check` (just the examples).

**Comment by dschwen** [comment]
There is actually a libmesh check failing (Example fem_system_ex2).

**Comment by jwpeterson** [comment]
> There is actually a libmesh check failing (Example fem_system_ex2).

Yes, this is the GRINS-devel failure. It only runs if you have VTK enabled, which you must have on your system.

**Comment by pbauman** [comment]
If we squash f2d6c08 and 4a5ff6e, will that remove the files from the history so we don't bloat it?

**Comment by dschwen** [comment]
@pbauman, yeah, I'll squash. Just put it as a separate commit while we're still discussing this.

**Comment by pbauman** [comment]
Sounds good, just wanted to make sure.

**Comment by jwpeterson** [comment]
> So is everyone fine with the pruning I did?

I think we have Nanoflann tests in MOOSE, so if this passes those I'd say the update is probably OK.

> Do we need to ad a notice that we removed files from the nanoflann upstream?

IANAL but I think it's OK to *not* include pieces of BSD 2-clause licensed software that you distribute, provided that you maintain the copyright notices, list of conditions, etc. as required by the license.

**Comment by dschwen** [comment]
Ok. MOOSE passed, so I'll go ahead and squash.

**Pull request merged**
