### PR TITLE
Use VecGhostGetGhostIS instead of VecGetLocalToGlobalMapping

### PR DESCRIPTION
**Pull request by lindsayad**
Refs the development that Fande did in [petsc/petsc#5016](https://gitlab.com/petsc/petsc/-/merge_requests/5016)

### CODE REVIEW

**Comment by roystgnr** [comment]
Whoa, you got that up to date and they merged it finally?  That's excellent!

Not sure what's failing here, though.  Is this one of those "our PETSc macros don't play well with between-release PETSc versions" things again?

**Comment by lindsayad** [comment]
Looks like https://civet.inl.gov/job/1863560/ is still using a non-petsc-release hash

**Comment by roystgnr** [comment]
Yeah; hopefully we just fixed that in https://github.com/idaholab/civet_recipes/pull/1534

Kicking now to see.

**Comment by lindsayad** [comment]
Going to do some recording here. Not the perfect fit but not the worst fit. For the `griffin/examples/small_ptt/run_cmfd.i` input with 32 processes.

### With PETSc and libMesh changes

For 3rd generated heap profile on process 0:
```
ROUTINE ======================== VecCreateGhostWithArray in /home/lindad/projects/moose/petsc/src/vec/vec/impls/mpi/pbvec.c
         0    10.77MB (flat, cum) 15.03% of Total
         .          .    668:  PetscCheck(n != PETSC_DECIDE, PETSC_COMM_SELF, PETSC_ERR_ARG_OUTOFRANGE, "Must set local size");
         .          .    669:  PetscCheck(nghost != PETSC_DECIDE, PETSC_COMM_SELF, PETSC_ERR_ARG_OUTOFRANGE, "Must set local ghost size");
         .          .    670:  PetscCheck(nghost >= 0, PETSC_COMM_SELF, PETSC_ERR_ARG_OUTOFRANGE, "Ghost length must be >= 0");
         .          .    671:  PetscCall(PetscSplitOwnership(comm, &n, &N));
         .          .    672:  /* Create global representation */
         .     3.22kB    673:  PetscCall(VecCreate(comm, vv));
         .          .    674:  PetscCall(VecSetSizes(*vv, n, N));
         .     4.57MB    675:  PetscCall(VecCreate_MPI_Private(*vv, PETSC_TRUE, nghost, array));
         .          .    676:  w = (Vec_MPI *)(*vv)->data;
         .          .    677:  /* Create local representation */
         .          .    678:  PetscCall(VecGetArray(*vv, &larray));
         .     3.22kB    679:  PetscCall(VecCreateSeqWithArray(PETSC_COMM_SELF, 1, n + nghost, larray, &w->localrep));
         .          .    680:  PetscCall(VecRestoreArray(*vv, &larray));
         .          .    681:
         .          .    682:  /*
         .          .    683:       Create scatter context for scattering (updating) ghost values
         .          .    684:  */
         .   907.34kB    685:  PetscCall(ISCreateGeneral(comm, nghost, ghosts, PETSC_COPY_VALUES, &from));
         .          .    686:  PetscCall(ISCreateStride(PETSC_COMM_SELF, nghost, n, 1, &to));
         .     5.30MB    687:  PetscCall(VecScatterCreate(*vv, from, w->localrep, to, &w->localupdate));
         .          .    688:  PetscCall(ISDestroy(&to));
         .          .    689:
         .          .    690:  w->ghost                            = from;
         .          .    691:  (*vv)->ops->getlocaltoglobalmapping = VecGetLocalToGlobalMapping_MPI_VecGhost;
         .          .    692:  PetscFunctionReturn(PETSC_SUCCESS);
```

**Comment by lindsayad** [comment]
So this saves ~25% of PETSc ghost vector memory

**Comment by roystgnr** [comment]
I'm actually pretty surprised we use it often enough to see 25% memory reduction.  This is basically a copy-constructor-from-raw-PETSc-Vec?  How often are we using *that*, even in Griffin?

I'd have expected most of our ghosted vectors to be coming about via the init at https://github.com/libMesh/libmesh/pull/3695/files#diff-02e477137f63941d1b89c1e27f49571046918f5df3fff4a2d2ca9e0ea0081c5aR747

**Comment by YaqiWang** [comment]
Does the saving increase with more processors? I remembered that the ghosted vector costs 4-5 times more memory than a parallel vector for a case with 576 processors few years ago. We used to have 4 ghosted vectors plus 3 parallel vector, now we reduced these to one ghosted vector and 3 parallel vectors.

**Comment by roystgnr** [comment]
I assume that coverage failure is some artifact of our repeatedly juggling recipes.

I'm good to merge this as-is, on the theory that 25% is better than nothing, but we could hold off while we figure out whether we're missing vectors and whether we can fix that.

**Review by roystgnr — APPROVED** [review]

**Comment by lindsayad** [comment]
> I'm actually pretty surprised we use it often enough to see 25% memory reduction. This is basically a copy-constructor-from-raw-PETSc-Vec? How often are we using _that_, even in Griffin?

We don't use it at all in this profile. That's why I emphasized this:

> So the _PETSc_ change saves ~25% of PETSc ghost vector memory

and said 

> I do not think we actually leverage the constructor that I modified here in this PR very often

although it would probably have been more clear if I had said: "I do not think we actually leverage the constructor that I modified here in this PR at all in this particular profiled case, nor very often in general."

**Comment by lindsayad** [comment]
> Does the saving increase with more processors?

I'd have to add up the use across all processes which I haven't done yet. I suppose that would be easiest to do with the `perf_graph`?

In terms of the savings on a per process basis, it is higher savings with less processes since you have more ghosts per process and since we've axed the global to local map we don't have to pay for any of the ghosts in that map anymore

With 16 processes:

### New petsc

```
ROUTINE ======================== VecCreateGhostWithArray in /home/lindad/projects/moose/petsc/src/vec/vec/impls/mpi/pbvec.c
         0    17.41MB (flat, cum) 17.69% of Total
         .          .    668:  PetscCheck(n != PETSC_DECIDE, PETSC_COMM_SELF, PETSC_ERR_ARG_OUTOFRANGE, "Must set local size");
         .          .    669:  PetscCheck(nghost != PETSC_DECIDE, PETSC_COMM_SELF, PETSC_ERR_ARG_OUTOFRANGE, "Must set local ghost size");
         .          .    670:  PetscCheck(nghost >= 0, PETSC_COMM_SELF, PETSC_ERR_ARG_OUTOFRANGE, "Ghost length must be >= 0");
         .          .    671:  PetscCall(PetscSplitOwnership(comm, &n, &N));
         .          .    672:  /* Create global representation */
         .     3.22kB    673:  PetscCall(VecCreate(comm, vv));
         .          .    674:  PetscCall(VecSetSizes(*vv, n, N));
         .     8.55MB    675:  PetscCall(VecCreate_MPI_Private(*vv, PETSC_TRUE, nghost, array));
         .          .    676:  w = (Vec_MPI *)(*vv)->data;
         .          .    677:  /* Create local representation */
         .          .    678:  PetscCall(VecGetArray(*vv, &larray));
         .     3.22kB    679:  PetscCall(VecCreateSeqWithArray(PETSC_COMM_SELF, 1, n + nghost, larray, &w->localrep));
         .          .    680:  PetscCall(VecRestoreArray(*vv, &larray));
         .          .    681:
         .          .    682:  /*
         .          .    683:       Create scatter context for scattering (updating) ghost values
         .          .    684:  */
         .     1.26MB    685:  PetscCall(ISCreateGeneral(comm, nghost, ghosts, PETSC_COPY_VALUES, &from));
         .          .    686:  PetscCall(ISCreateStride(PETSC_COMM_SELF, nghost, n, 1, &to));
         .     7.59MB    687:  PetscCall(VecScatterCreate(*vv, from, w->localrep, to, &w->localupdate));
         .          .    688:  PetscCall(ISDestroy(&to));
         .          .    689:
         .          .    690:  w->ghost                            = from;
         .          .    691:  (*vv)->ops->getlocaltoglobalmapping = VecGetLocalToGlobalMapping_MPI_VecGhost;
         .          .    692:  PetscFunctionReturn(PETSC_SUCCESS);
```

### Old petsc

```
ROUTINE ======================== VecCreateGhostWithArray in /home/lindad/projects/old-petsc/petsc/src/vec/vec/impls/mpi/pbvec.c
         0    24.70MB (flat, cum) 24.30% of Total
         .          .    637:  PetscCheck(n != PETSC_DECIDE, PETSC_COMM_SELF, PETSC_ERR_ARG_OUTOFRANGE, "Must set local size");
         .          .    638:  PetscCheck(nghost != PETSC_DECIDE, PETSC_COMM_SELF, PETSC_ERR_ARG_OUTOFRANGE, "Must set local ghost size");
         .          .    639:  PetscCheck(nghost >= 0, PETSC_COMM_SELF, PETSC_ERR_ARG_OUTOFRANGE, "Ghost length must be >= 0");
         .          .    640:  PetscCall(PetscSplitOwnership(comm, &n, &N));
         .          .    641:  /* Create global representation */
         .     3.22kB    642:  PetscCall(VecCreate(comm, vv));
         .          .    643:  PetscCall(VecSetSizes(*vv, n, N));
         .     8.55MB    644:  PetscCall(VecCreate_MPI_Private(*vv, PETSC_TRUE, nghost, array));
         .          .    645:  w = (Vec_MPI *)(*vv)->data;
         .          .    646:  /* Create local representation */
         .          .    647:  PetscCall(VecGetArray(*vv, &larray));
         .     3.22kB    648:  PetscCall(VecCreateSeqWithArray(PETSC_COMM_SELF, 1, n + nghost, larray, &w->localrep));
         .          .    649:  PetscCall(VecRestoreArray(*vv, &larray));
         .          .    650:
         .          .    651:  /*
         .          .    652:       Create scatter context for scattering (updating) ghost values
         .          .    653:  */
         .          .    654:  PetscCall(ISCreateGeneral(comm, nghost, ghosts, PETSC_COPY_VALUES, &from));
         .          .    655:  PetscCall(ISCreateStride(PETSC_COMM_SELF, nghost, n, 1, &to));
         .     7.59MB    656:  PetscCall(VecScatterCreate(*vv, from, w->localrep, to, &w->localupdate));
         .          .    657:  PetscCall(ISDestroy(&to));
         .          .    658:  PetscCall(ISDestroy(&from));
         .          .    659:
         .          .    660:  /* set local to global mapping for ghosted vector */
         .     8.55MB    661:  PetscCall(PetscMalloc1(n + nghost, &indices));
         .          .    662:  PetscCall(VecGetOwnershipRange(*vv, &rstart, NULL));
         .          .    663:  for (i = 0; i < n; i++) indices[i] = rstart + i;
         .          .    664:  for (i = 0; i < nghost; i++) indices[n + i] = ghosts[i];
         .     1.19kB    665:  PetscCall(ISLocalToGlobalMappingCreate(comm, 1, n + nghost, indices, PETSC_OWN_POINTER, &ltog));
         .          .    666:  PetscCall(VecSetLocalToGlobalMapping(*vv, ltog));
         .          .    667:  PetscCall(ISLocalToGlobalMappingDestroy(&ltog));
         .          .    668:  PetscFunctionReturn(PETSC_SUCCESS);
         .          .    669:}
         .          .    670:
```

**Comment by lindsayad** [comment]
> I do not think we actually leverage the constructor that I modified here in this PR at all in this particular profiled case, nor very often in general

In my brain, I commented on this before. We do these kinds of construction quite frequently. If you look in `libmesh_petsc_snes_residual` we wrap the incoming PETSc residual vector

**Pull request merged**
