### PR TITLE
Added assertion to mesh refinement class.

### PR DESCRIPTION
**Pull request by hrittich**
Just an assertion against a trap I just fell into.

### CODE REVIEW

**Comment by jwpeterson** [comment]
Huh, the MOOSE debug-mode test failures seem to be due to your (what I thought was) benign new assert. I'm not sure why the mesh wouldn't be prepared in these situations; perhaps it's because it was just uniformly refined?

materials/stateful_prop.adaptivity:
```
Assertion `_mesh.is_prepared()' failed.

Stack frames: 14
0: libMesh::print_trace(std::ostream&)
1: libMesh::MacroFunctions::report_error(char const*, int, char const*, char const*)
2: libMesh::MeshRefinement::_refine_elements()
3: libMesh::MeshRefinement::uniformly_refine(unsigned int)
4: MooseMesh::findAdaptivityQpMaps(libMesh::Elem const*, libMesh::QBase&, libMesh::QBase&, std::__debug::vector<std::__debug::vector<QpMap, std::allocator<QpMap> >, std::allocator<std::__debug::vector<QpMap, std::allocator<QpMap> > > >&, std::__debug::vector<std::pair<unsigned int, QpMap>, std::allocator<std::pair<unsigned int, QpMap> > >&, int, int, int)
5: MooseMesh::buildRefinementMap(libMesh::Elem const&, libMesh::QBase&, libMesh::QBase&, int, int, int)
6: MooseMesh::buildRefinementAndCoarseningMaps(Assembly*)
7: FEProblemBase::initialSetup()
8: Transient::init()
9: MooseApp::executeExecutioner()
10: MooseApp::run()
11: /opt/civet/build_0/moose/test/moose_test-dbg() [0x41a708]
12: __libc_start_main
13: /opt/civet/build_0/moose/test/moose_test-dbg() [0x41a3d9]
[0] ../src/mesh/mesh_refinement.C, line 1464, compiled Jan 16 2019 at 10:58:52
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
```

materials/stateful_prop.spatial_adaptivity:
```
Assertion `_mesh.is_prepared()' failed.

Stack frames: 14
0: libMesh::print_trace(std::ostream&)
1: libMesh::MacroFunctions::report_error(char const*, int, char const*, char const*)
2: libMesh::MeshRefinement::_refine_elements()
3: libMesh::MeshRefinement::uniformly_refine(unsigned int)
4: MooseMesh::findAdaptivityQpMaps(libMesh::Elem const*, libMesh::QBase&, libMesh::QBase&, std::__debug::vector<std::__debug::vector<QpMap, std::allocator<QpMap> >, std::allocator<std::__debug::vector<QpMap, std::allocator<QpMap> > > >&, std::__debug::vector<std::pair<unsigned int, QpMap>, std::allocator<std::pair<unsigned int, QpMap> > >&, int, int, int)
5: MooseMesh::buildRefinementMap(libMesh::Elem const&, libMesh::QBase&, libMesh::QBase&, int, int, int)
6: MooseMesh::buildRefinementAndCoarseningMaps(Assembly*)
7: FEProblemBase::initialSetup()
8: Transient::init()
9: MooseApp::executeExecutioner()
10: MooseApp::run()
11: /opt/civet/build_0/moose/test/moose_test-dbg() [0x41a708]
12: __libc_start_main
13: /opt/civet/build_0/moose/test/moose_test-dbg() [0x41a3d9]
[0] ../src/mesh/mesh_refinement.C, line 1464, compiled Jan 16 2019 at 10:58:52
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
```

**Comment by jwpeterson** [comment]
I don't have time to look into this more deeply at the moment, but it would appear that in MOOSE the `Mesh` is not prepared before `uniformly_refine()` gets called. Evidently this has not been an issue before, but it was for a Mesh you were using? Can you let us know specifically what error you ran into? That may help us decide whether an extra `prepare_for_use()` is technically needed in MOOSE, although it can be a bad thing to call `prepare_for_use()` more often than necessary... (@permcody would ask: Why are you always preparing? Just go!)

**Comment by hrittich** [comment]
@jwpeterson I was using the following code to load and refine a mesh.

    GmshIO io(mesh);
    io.read(filename.c_str());
    MeshRefinement mesh_refinement(mesh);
    mesh_refinement.uniformly_refine(refinements);

The corresponding error message was:

    Assertion `node_pid != DofObject::invalid_processor_id' failed.
    node_pid = 4294967295                                                                                                          
    DofObject::invalid_processor_id = 4294967295

**Comment by roystgnr** [comment]
Hmm... so ```is_prepared()``` should be a *sufficient* condition for refinement, but it isn't a *necessary* condition?

I don't actually see what the *necessary* preparation is, though, based on the reports here.  @hrittich is seeing a complaint about an unpartitioned node somewhere (a stack trace would be very helpful for figuring out where), but @jwpeterson points us to MooseMesh::findAdaptivityQpMaps, where as best as I can tell they were happily doing adaptivity on an unpartitioned ReplicatedMesh!  Maybe the failure @hrittich saw was on a DistributedMesh, where in my synchronization code I might have lazily assumed nothing was left unpartitioned?

**Comment by hrittich** [comment]
@roystgnr Yes, I am using a distributed mesh. The stack trace is as follows.

    Assertion `node_pid != DofObject::invalid_processor_id' failed.
    node_pid = 4294967295
    DofObject::invalid_processor_id = 4294967295


    Stack frames: 11
    0: libMesh::print_trace(std::ostream&)
    1: libMesh::MacroFunctions::report_error(char const*, int, char const*, char const*)
    2: [...] libmesh_devel.so.0(+0x820704) [0x7ffff74df704]
    3: libMesh::MeshCommunication::make_new_node_proc_ids_parallel_consistent(libMesh::MeshBase&)
    4: libMesh::MeshCommunication::make_new_nodes_parallel_consistent(libMesh::MeshBase&)
    5: libMesh::MeshRefinement::_refine_elements()
    6: libMesh::MeshRefinement::uniformly_refine(unsigned int)
    7: [...] main(+0x274c5) [0x55555557b4c5]
    8: [...] main(+0x22aa8) [0x555555576aa8]
    9: __libc_start_main
    10: [...] main(+0x23d1a) [0x555555577d1a]
    [0] ./include/libmesh/parallel_ghost_sync.h, line 589, compiled Jan 18 2019 at 11:19:41

In my humble opinion, I would say, it is better to document and expect the mesh to be prepared before using a mesh refinement than to say that it depends on the situation. For me, as a user, it is not really transparent, whether the mesh needs to be prepared before refinement or not.

How expensive is Mesh::prepare, anyways?

**Comment by jwpeterson** [comment]
> where in my synchronization code I might have lazily assumed nothing was left unpartitioned?

From the stack trace posted, this looks like it might be the case. I suppose it's not very satisfying, but what if we change the proposed assert to 
```
libmesh_assert(_mesh.is_prepared() || _mesh.is_replicated());
```
in the meantime? That should both satisfy the MOOSE tests and prevent unexpected failures in the `DistributedMesh` case?

**Comment by hrittich** [comment]
I have changed the assertion as @jwpeterson proposed. I also have added a little documentation.

**Comment by jwpeterson** [comment]
OK, good to see that this passed. I'll wait to see if @roystgnr has any further comments before merging though.

**Comment by roystgnr** [comment]
Sorry I've been vanished this weekend.  New version looks perfect, thanks!

**Pull request merged**
