### PR TITLE
Subdomain expansion, new branch

### PR DESCRIPTION
**Pull request by roystgnr**
One more attempt to trigger CI

### CODE REVIEW

**Comment by roystgnr** [comment]
Still no pass.  Unless we're getting lucky elsewhere there might be something in this PR tripping things?  I'll kick it one more time just in case we're getting bitten by a race condition (I'm pretty sure we *have* a race condition in one new unit test, in fact, but I've never triggered it on less than 3 processors and it manifests for me as a nice failure message not a SIGKILL), then I'll try bisecting this.

**Comment by roystgnr** [comment]
Since other branches are passing, I'm going to try bisecting here a bit and see if we can narrow down what commit was causing this one to fail.  The original subomain_expansion branch has all the commits; I'll be stripping off and adding on to this one.

**Comment by roystgnr** [comment]
That was a pass on https://github.com/libMesh/libmesh/pull/2690/commits/6624e69af4af0e03ebf262eecff503ff8f39623f - for future reference in case I accidentally clear the green check with a later force push.

**Comment by roystgnr** [comment]
And then a quick failure from f8109f7

**Comment by roystgnr** [comment]
And then a pass from 29323bd.  There might be a bit of a red herring here, if f8109f7 created a problem that a later commit fixed.  But those later commits should reorder cleanly, and we don't yet have test coverage in here depending on f8109f7, so I'll try bisecting with that one commit left out.

**Comment by roystgnr** [comment]
Okay, then - df9624a includes every commit *except* f8109f7, and that passes.  I'll try one last time with the whole set to make sure it's failing.

**Comment by roystgnr** [comment]
Still failing, but now with actual assertion failures instead of SIGKILL, and I can actually reproduce the failures now without getting sidetracked by the other unit test bugs, so I'm finally optimistic here.

**Comment by roystgnr** [comment]
Hopefully I've got it now.  The fixup for the last commit here is supposed to be backwards compatible in cases other than the one (h-refinement with high-p elements) that broke, but @dewenyushu is going to want to double-check and make sure I didn't just regress the subdomain expansion capability that motivated this PR in the first place.

**Comment by dewenyushu** [comment]
> Hopefully I've got it now. The fixup for the last commit here is supposed to be backwards compatible in cases other than the one (h-refinement with high-p elements) that broke, but @dewenyushu is going to want to double-check and make sure I didn't just regress the subdomain expansion capability that motivated this PR in the first place.

Hi @roystgnr , thanks for checking with me! I just tested this PR with my existing test cases for subdomain expansion. Everything looks fine so far!

**Review by jwpeterson — APPROVED** [review]

**Pull request merged**
