### PR TITLE
More generic `index_range`

### LINKED ISSUE #3377: More permissive `index_range` function
Any reason `index_range` just has a limited set of (partial) specializations?

It would be useful to have something like

```
template <typename T>
auto
index_range(const T & sizable)
{
  return IntRange<decltype(sizable.size())>(0, sizable.size());
}
```

To allow iterating over e.g. Communicators and MooseArrays. Basically anything that has a `.size()` function.

### PR DESCRIPTION
**Pull request by dschwen**
Closes #3377

### CODE REVIEW

**Review by jwpeterson — APPROVED** [review]

**Comment by dschwen** [comment]
```
    FAIL moosesqa/test.reports/SQADocumentReport FAILED (CRASH)
    FAIL mooseutils/tests.civet_results FAILED (CRASH)
```

I don't think these failures are related to this PR.

**Comment by jwpeterson** [comment]
Still have the unrelated Test moose python failure:
```
    FAIL moosesqa/test.reports/SQADocumentReport FAILED (CRASH)
    FAIL mooseutils/tests.civet_results FAILED (CRASH)
```

**Comment by jwpeterson** [comment]
> I don't think these failures are related to this PR.

Agreed, ignore my other comment which I made before refreshing the page. Is there any ETA on when those tests will be fixed/temporarily skipped?

**Comment by roystgnr** [comment]
Any idea what's going on now here?

https://civet.inl.gov/job/1152677/

```
/data/civet0/build/moose/framework/src/utils/Units.C: In function 'std::ostream& operator<<(std::ostream&, const MooseUnits&)':
/data/civet0/build/moose/framework/src/utils/Units.C:569:42: error: call of overloaded 'index_range(const std::vector<std::pair<MooseUnits::BaseUnit, int> >&)' is ambiguous
  569 |   for (const auto i : index_range(u._base))
      |                                          ^
In file included from /data/civet0/build/moose/framework/build/header_symlinks/Units.h:12,
                 from /data/civet0/build/moose/framework/src/utils/Units.C:10:
/data/civet0/build/moose/framework/build/header_symlinks/MooseTypes.h:970:1: note: candidate: 'auto index_range(const T&) [with T = std::vector<std::pair<MooseUnits::BaseUnit, int> >]'
  970 | index_range(const T & sizable)
      | ^~~~~~~~~~~
In file included from /data/civet0/build/moose/framework/build/header_symlinks/MooseTypes.h:29,
                 from /data/civet0/build/moose/framework/build/header_symlinks/Units.h:12,
                 from /data/civet0/build/moose/framework/src/utils/Units.C:10:
/data/civet0/build/libmesh/installed/include/libmesh/int_range.h:107:6: note: candidate: 'auto libMesh::index_range(const T&) [with T = std::vector<std::pair<MooseUnits::BaseUnit, int> >]'
  107 | auto index_range(const T & sizable)
      |      ^~~~~~~~~~~
```

Obviously the compiler isn't going to be able to disambiguate those, but how is it killing new PRs and didn't kill this PR?

**Comment by jwpeterson** [comment]
`for (const auto i...)` 

Does that declare the loop counter constant?

**Comment by roystgnr** [comment]
We've got duplicate index_range in MOOSE now too.  I'm putting in a PR there.

**Pull request merged**
