### PR TITLE
Only get_elem() if FEMContext has_elem().

### PR DESCRIPTION
**Pull request by pbauman**
Need to guard calls to get_elem() with has_elem() calls. App code is still broken, so I don't know if I've hit all the places yet so don't merge this yet.

### CODE REVIEW

**Comment by roystgnr** [comment]
Looks great so far.  Sorry I didn't run the GRINS suite and catch these; I forgot we don't have any FEMContext+Scalar coverage in the libMesh suite yet.

**Comment by pbauman** [comment]
OK, those are the last two I hit. When MooseBuild and others are happy, this should be good to merge.

**Comment by roystgnr** [comment]
No libmesh_PR_test_dbg recipe is running?

**Comment by roystgnr** [comment]
Never mind; my browser hadn't updated yet.

**Comment by roystgnr** [comment]
Looks good to merge after that finishes.

**Pull request merged**
